### ISSUE TITLE
Installation Fails on Visual Studio 2019 Enterprise 16.0.2

### ISSUE THREAD

**Issue by Nibell** [code-cracker/code-cracker#1025]
#Bug

The error still persists on VS 2019 Enterprise 16.0.2.

````csharp
This extension cannot be installed because the following references are missing
Microsoft.VisualStudio.Component.CoreEditor
Microsoft.VisualStudio.Component.Roslyn.LanguageServices
````
Not fixed in Bug [#1019](https://github.com/code-cracker/code-cracker/issues/1019)

**Comment by alex529** [comment]
Same issue appears on happens on Visual Studio Professional 2019 16.0.3

**Comment by Thieum** [comment]
it is fixed in #1019, but there is no new release that includes the fix atm.
A way to have the extension in VS2019 is to build it yourself from source.

![image](https://user-images.githubusercontent.com/944894/57391646-eef67480-718c-11e9-8bc8-9d672289e3a2.png)

@carloscds Would it be possible create a new release on github at least? 

[The VS marketplace ](https://marketplace.visualstudio.com/items?itemName=GiovanniBassi-MVP.CodeCrackerforC)displays the current version as compatible with VS2019, wich is not, so maybe we should push a new version that is?

Or at least in the [VSIX Gallery](http://vsixgallery.com/)?

**Comment by carloscds** [comment]
@Thieum Sorry for this, but I'm waiting to @giggio generate a new version!

**Comment by Thieum** [comment]
@carloscds no problem, I understand :)

**Comment by Flying--Dutchman** [comment]
@carloscds Any update on this issue? Would the release from 20.05 work with vs2019?
Anything i can help with?

**Comment by carloscds** [comment]
@giggio CAn you generate new version please ?

**Comment by RealDotNetDave** [comment]
+1!

**Comment by luanholiv** [comment]
+1

**Comment by AqlaSolutions** [comment]
+1

**Comment by jwooley** [comment]
Is this still an issue? It installs on 16.3 which is the latest RTM.

**Comment by carloscds** [comment]
Yes, because @giggio need to generate a new version.

**Comment by Flying--Dutchman** [comment]
@carloscds There is no new release since the 20th of May 2018... Is anyone of the team able to create the Visual Studio Extension without @giggio ?

Even if it isn't uploaded to the marketplace.

**Comment by carloscds** [comment]
@Flying--Dutchman Sorry for this, but @giggio does not answer anymore. We can create another VSIX and Nuget repo. What do you think about ?

**Comment by Flying--Dutchman** [comment]
Maybe, we could create a "release" branch or work with tags to automaticly push new VISX to Gallery at least directly from AppVeyor.
--> http://vsixgallery.com/guide/dev/

**Comment by carloscds** [comment]
@Flying--Dutchman I can create a VSIX and put at release folder here,what do you think?

**Comment by carloscds** [comment]
@Flying--Dutchman I have a new version of VSIX: https://marketplace.visualstudio.com/items?itemName=CodeCracker2019.CodeCracker2019

**Comment by Flying--Dutchman** [comment]
Great! Thank you very much.

**Comment by TymurGubayev** [comment]
> @Flying--Dutchman I have a new version of VSIX: https://marketplace.visualstudio.com/items?itemName=CodeCracker2019.CodeCracker2019

Could you please make a 2019 VisualBasic release too?

**Comment by carloscds** [comment]
Hi @TymurGubayev I guess that only @giggio has access to VB Extension.
