### ISSUE TITLE
Changing DiagnosticID

### ISSUE THREAD

**Issue by namdt1992** [code-cracker/code-cracker#1034]
I'd like to change the "CC", such as CC0001, CC0002,... of the
DiagnosticId of Code Cracker.

I've tried editing CC in statement
$"CC{(int)diagnosticId :D4}" to a prefix I want, but it didn't work.
After changing, the Code Cracker library still show errors and
warnings, but didn't view diagnosticId and category (such as
Refactoring, Design,...) either.
That statement is in:

namespace CodeCracker
{
   public static class Extensions
   {
       public static string ToDiagnosticId(this DiagnosticId
diagnosticId) => $"CC{(int)diagnosticId :D4}";
... } }

Could anyone share me how to change it?

Thank you very much,
Cheers,
Nam

**Comment by namdt1992** [comment]
@giggio , can you help me?
Thanks,

**Comment by carloscds** [comment]
@namdt1992 Put your errors here please.

**Comment by namdt1992** [comment]
hi @carloscds, I've solved this issue. the error is from Visual Studio 2019. After restarting Visual Studio instead of restarting solution, DiagnosticIds changes at I expect.
Thank you very much,
