### ISSUE TITLE
CC0029 should not be reported for Dispose(bool)

### ISSUE THREAD

**Issue by sharwell** [code-cracker/code-cracker#107]
Currently CC0029 is reported if `Dispose(bool)` does not contain a call to `GC.SuppressFinalize`. This is not correct; the call to `GC.SuppressFinalize` should be in the method which implements `IDisposable.Dispose()` (which may be an explicit implementation of the interface method).

This is a sub-task of #95.

**Comment by giggio** [comment]
Bug confirmed.
