### ISSUE TITLE
CC0029 should not be reported for some types with private constructors

### ISSUE THREAD

**Issue by sharwell** [code-cracker/code-cracker#110]
If a type does not have any publicly accessible constructors *and* the type does not have any user-defined finalizers, then CC0029 should not be reported for that type. A type does not have any publicly accessible constructors if any of the following are true:

1. The type has at least one user-defined instance constructor, *and* all user-defined instance constructors are marked `private`.
2. The type is a nested type which is marked `private`, *and* either there are no other nested types which extend the type or the analysis for user-defined finalizers is expanded to consider all such derived types.
3. The type is nested within another type which meets condition 2.

This is a sub-task of #95.

**Comment by giggio** [comment]
Bug confirmed.
