### ISSUE TITLE
ArgumentExceptionAnalyzer ignores several code constructs

### ISSUE THREAD

**Issue by sharwell** [code-cracker/code-cracker#112]
Currently `ArgumentExceptionAnalyzer` assumes the exception is thrown within a method. Several other code constructs have parameters:

* Lambda expressions (both parenthesized and simple)
* Indexer properties
* Certain accessors (`set`, `add`, and `remove`) have an implicit `value` parameter

**Comment by giggio** [comment]
Lambda expressions were solved on a367d9de. I am fine without analyzing indexer properties or event accessors. @code-cracker/owners If you disagree please reopen the issue.
