### ISSUE TITLE
Compute value of an expression and replaces it whenever it's possible 

### ISSUE THREAD

**Issue by ElemarJR** [code-cracker/code-cracker#117]
`Console.WriteLine(1 + 1)` becomes `Console.WriteLine(2)`

This is `Hidden` and `Refactoring`.
Diagnostic Id: `CC0082`

**Comment by giggio** [comment]
I will work on it.

**Comment by giggio** [comment]
Ok, I am blocked on this one. I can't arbitrarily run an expression at runtime. The main problem is that `Assembly.Load(byte[])` does not exist for PCLs.
I have contacted the C# team and will wait on their answer. Maybe this is possible through some other route.

**Comment by giggio** [comment]
I am no longer blocked. I was able to use `SemanticModel.GetConstantValue`. See https://github.com/giggio/code-cracker/commit/aad7d83d56e991616cc6d1f0b1ad87994eea5432#diff-8eb73e3de1fa78edc82aabe102165778R49.
