### ISSUE TITLE
Use auto property when possible

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#12]
````csharp
private int _value;
public int Value
{
    get { return _value; }
    set { _value = value; }
}
````

Becomes:

````csharp
public int Value { get; set; }
````

With initializer, if it is C#6:

This:

````csharp
private int _field = 42;
public int Field
{
    get { return _field; }
    set { _field = value; }
}
````

Becomes:

````csharp
public int Field { get; set; } = 42;
````

If it is not C#6 and there is a field initializer, no diagnostic is created.

If `set` has a modifier (`private`, etc), use it accordingly.

If there is a reference to the field, change it to reference the property.

Severity: `Information`
Diagnostic id: `CC0017`
Category: `Style`

**Comment by giggio** [comment]
@viniciushana It's been a while, how is this coming?

**Comment by viniciushana** [comment]
Kinda late, that issue of dealing with public fields made it somewhat complicated. I gotta adapt my implementation to the changes made to the project and then work on that specific issue.
