### ISSUE TITLE
Use String.Empty instead ""

### ISSUE THREAD

**Issue by ElemarJR** [code-cracker/code-cracker#120]
````csharp
var a = "";
````

Becomes 

````csharp
var a = string.Empty;
````

`Style`, `Info`

Diagnostic Id: `CC0084`
Severity: Hidden
Category: Style

**Comment by andrecarlucci** [comment]
It would be nice to have the option to change to String.Empty too.
To be honest, I find "" more readable than String.Empty, but that's personal taste ;)

**Comment by giggio** [comment]
I also prefer `""`. :)

**Comment by giggio** [comment]
@andrecarlucci Just create an issue doing the opposite!

**Comment by carloscds** [comment]
Is it ok to develop ?

**Comment by giggio** [comment]
Still missing diagnostic id..

**Comment by carloscds** [comment]
Ok, I will put it.

**Comment by giggio** [comment]
@carloscds I changed the label to working, I assume you are working on it, right?

**Comment by carloscds** [comment]
@giggio Correct, it's mine :-)
