### ISSUE TITLE
Convert Nullable<T> to T?

### ISSUE THREAD

**Issue by ElemarJR** [code-cracker/code-cracker#123]
The Nullable type has been defined not using the C# shorthand. For example, Nullable<DateTime> has been used instead of the preferred DateTime?

A violation of this rule occurs whenever the Nullable type has been defined without using the shorthand C# style.

To fix a violation of this rule, use the shorthand version of the nullable type ie. int?, DateTime?, etc.

````csharp
Nullable<int> a;
````

becomes

````csharp
int? a;
````

This is category `Style` and severity level `Info`.
Diagnostic id: `CC0050`

**Comment by giggio** [comment]
I was working on this one and just found out that `IDE0001` from Roslyn core is already fixing it: https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Diagnostics/Analyzers/IDEDiagnosticIds.cs
I am closing it as duplicate.
