### ISSUE TITLE
Screenshots of Analyzers and code fixers  "in action"

### ISSUE THREAD

**Issue by ElemarJR** [code-cracker/code-cracker#136]
I think that a good way to start some end-user documentation is to capture screenshots.

Like https://github.com/DotNetAnalyzers/NullParameterCheckRefactoring

We could create a `screenshots`, with a subfolder named with the analyzer ID.

**Comment by giggio** [comment]
We have discussed, we will keep using http://code-cracker.github.io/ for docs. We will move "contributing" pages and related back to this repo, on the home page.
