### ISSUE TITLE
Remove async and return task directly

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#151]
Sometimes an async method might only do some some sync work and then at the end await on another async method. Like this:

````csharp
async Task FooAsync()
{
    DoSomething();
    await SomethingElseAsync();
}
````

To optimize the generated code we could simply return the task from `SomethingElseAsync`. So the previous code becomes:

````csharp
Task FooAsync()
{
    DoSomething();
    return SomethingElseAsync();
}
````

This is the decompiled C# generated on the first case (optmized, release settings):

````csharp
		private Task FooAsync()
		{
			Program.<FooAsync>d__1 <FooAsync>d__;
			<FooAsync>d__.<>4__this = this;
			<FooAsync>d__.<>t__builder = AsyncTaskMethodBuilder.Create();
			<FooAsync>d__.<>1__state = -1;
			AsyncTaskMethodBuilder <>t__builder = <FooAsync>d__.<>t__builder;
			<>t__builder.Start<Program.<FooAsync>d__1>(ref <FooAsync>d__);
			return <FooAsync>d__.<>t__builder.Task;
		}
````

Where in the second case it stays pretty much the same, there is no need to generate the state machine. I was actually expecting the compiler to be smarter, but it is not.

Category: `Performance`
Severity: `Info`
Diagnostic id: `CC0051`

**Comment by giggio** [comment]
@code-cracker/owners This has been discusses a long time ago, I am moving it to `Ready`.

**Comment by thorgeirk11** [comment]
Is it ok if I try to tackle this ?

**Comment by giggio** [comment]
Go for it.
Remember to fork from the `vnext` branch, not from `master`.

**Comment by thorgeirk11** [comment]
Is there a place where I can change the info displayed when navigated to the error page for the this diagnostic id?

That is to add an error page for https://code-cracker.github.io/diagnostics/CC0051.html

**Comment by giggio** [comment]
Worked on #497.
