### ISSUE TITLE
Should we accept PR with no related issue?

### ISSUE THREAD

**Issue by ElemarJR** [code-cracker/code-cracker#155]
Hello everyone.

I would like to find a "lower the entry barrier" for CodeCracker collaborators. What do you think about start to accept PR with no related issues? Sometimes people have a great idea and just implement it for personnal use (remember, CodeCracker is free for modification, right?). Why not to share it with the world?

Why have we to restrict this kind of collaboration?

I've been thinking a lot about it after this PR (https://github.com/code-cracker/code-cracker/pull/149) from @diegodfsd

**Comment by ElemarJR** [comment]
I think this issue could be closed. Am I right?

**Comment by carloscds** [comment]
@ElemarJR I think yes.

**Comment by diegodfsd** [comment]
Hello guys.

I will go fix the things in the next week. You can close this PR and when I
finish it I open another PR.

On Sun, Jan 4, 2015 at 12:58 PM, Carlos dos Santos <notifications@github.com
> wrote:

> @ElemarJR <https://github.com/ElemarJR> I think yes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/code-cracker/code-cracker/issues/155#issuecomment-68635570>
> .
>



-- 


*Diego Dias*Analista Desenvolvedor
Microsoft Certified Applications Developer
Microsoft Certified Technology Specialist WCF .Net 4.0 - Charter Member
<http://www.microsoft.com/learning/en/us/certification/cert-program-membership.aspx>
11-8931.1768

**Comment by giggio** [comment]
@ElemarJR @carloscds Ok, let's close. I am understanding we are fine with getting PRs for things that don't have an open or ready issue, but this is riskier, as we just might deny the idea. Right?
So, when one of those happens we just add the github labels and move on.

**Comment by giggio** [comment]
@diegodfsd Ok, we will wait for your new PR.
