### ISSUE TITLE
InvalidCastException in CC0016 and CC0031

### ISSUE THREAD

**Issue by felipebz** [code-cracker/code-cracker#175]
The following code throws an InvalidCastException in CC0016 (CopyEventToVariableBeforeFire) and CC0031 (UseInvokeMethodToFireEvent).

```c#
using System;

public class Main
{
    public void Execute()
    {
        var tuple = new Tuple<int, Action>(1, null);
        tuple.Item2();
    }
}
```

These analyzers are trying to convert the InvocationExpressionSyntax.Expression object to IdentifierNameSyntax, but in this case the Expression property is a MemberAccessExpressionSyntax.

**Comment by sqdavid** [comment]
Hello guys, Assuming that all the analysis works right, I think changing " ((IdentifierNameSyntax)invocation.Expression).Identifier.Text " in line 48/49 of the respective files by " invocation.Expression.ToString() " will solve the issue.

**Comment by giggio** [comment]
@sqdavid Wanna try to fix it? Just add a test to show the error and submit a PR.

**Comment by giggio** [comment]
@sqdavid I fixed. You were right about the spot. I will push it soon.

**Comment by sqdavid** [comment]
great =)
