### ISSUE TITLE
Validate IPAddress.Parse from System.Net

### ISSUE THREAD

**Issue by andrecarlucci** [code-cracker/code-cracker#188]
This:
`
 System.Net.IPAddress.Parse("wrong ip");
`

Will be marked as an Error. 
Category is Usage.
Diagnostic id is CC0064

**Comment by andrecarlucci** [comment]
I'll do it :)

**Comment by giggio** [comment]
Great!

**Comment by ravpacheco** [comment]
Hi guys, 

would be great if we could supress this error.

Now if I make

    var correctIP = "0.0.0.0";
    System.Net.IPAddress.Parse(correctIP);

I receive a error.
What you think ?

**Comment by giggio** [comment]
@ravpacheco yes, it is a bug. I created issue #571 to fix it.

**Comment by giggio** [comment]
@ravpacheco In the meantime, you can disable it by adding:

````csharp
var correctIP = "0.0.0.0";
#pragma warning disable CC0064
System.Net.IPAddress.Parse(correctIP);
#pragma warning restore CC0064
````

**Comment by ravpacheco** [comment]
@giggio great. Thanks!
Congratulations this project is awesome! \o/
