### ISSUE TITLE
Null Reference BUG on ForInArrayAnalyzer (CC0006)

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#193]
See line 313 of the build log:
https://ci.appveyor.com/project/code-cracker/code-cracker/build/1.0.0.241#L313
To repro, just open [corefx](https://github.com/dotnet/corefx) and build.

Here is the full log:

> 1083   info AnalyzerDriver: The Compiler Analyzer 'CodeCracker.Style.ForInArrayAnalyzer' threw an exception with message 'Object reference not set to an instance of an object.'. 

**Note**:
Exact cause still to be determined, as soon as anyone investigates we can update title and description to be clearer.

**Comment by felipebz** [comment]
I am working on this.

**Comment by giggio** [comment]
@felipebz Ok, it is yours!

**Comment by felipebz** [comment]
Just for the record, the code in corefx causing this bug is this loop: https://github.com/dotnet/corefx/blob/0fcf5ca8c18b1cc72e6ea200745eb77fe9ff9d3b/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableStack%601.cs#L238
