### ISSUE TITLE
Test NameOfCodeFixProvider with keyword

### ISSUE THREAD

**Issue by sharwell** [code-cracker/code-cracker#198]
Two tests should be added in support of C# code using the `@identifier` syntax:

1. Test with a parameter name which is a C# keyword (e.g. `@object`)
2. Test with a parameter name which is *not* a C# keyword (e.g. `@obj`)

@baks is working on it.

**Comment by baks** [comment]
Looks easy for somebody new like me :)
@giggio  I take this one

**Comment by giggio** [comment]
Closed on #331.
