### ISSUE TITLE
Remove trailling whitespace

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#201]
If a line ends with a space or tab and it is not a string, then raise a diagnostic and offer a fix to remove it.

I will use an interpunct (·) to represent trailling whitespace and a tab character (↹) to represent tabs. So this:

````csharp
var i = 1;·
var j = 2;↹
````

Becomes

````csharp
var i = 1;
var j = 2;
````

Multiple characters are removed as well.

So this:

````csharp
var i = 1;·····
var j = 2;↹↹↹
````

Becomes

````csharp
var i = 1;
var j = 2;
````

Severity: `Info`
Category: `Style`
Diagnostic id: `CC0065`

**Comment by giggio** [comment]
This is not `Ready` yet, but I want to work on it immediatelly because I want it for myself! :)
@code-cracker/owners can one you review it so I can start?

**Comment by carloscds** [comment]
@giggio Ideia is remove unused spaces ?

**Comment by paulomorgado** [comment]
I've always done this with find&replace. I think this is an abuse of the diagnostics infrastructure.

I really think this should be an IDE task, not compiler.

**Comment by giggio** [comment]
@carloscds the idea is to remove spaces after code, to the right. I use [Trailling Whitespace Visualizer](https://visualstudiogallery.msdn.microsoft.com/a204e29b-1778-4dae-affd-209bea658a59) to show it to me.
See:
![image](https://cloud.githubusercontent.com/assets/334958/5693464/029e05a8-9905-11e4-9de6-3463d6398e5f.png)

**Comment by giggio** [comment]
@paulomorgado Not everyone writing C# is doing it on an IDE anymore. :) Why is this an abuse? People can turn it off if they want. Do you think it should come off by default?
