### ISSUE TITLE
Virtual method call in constructor

### ISSUE THREAD

**Issue by andrecarlucci** [code-cracker/code-cracker#203]
This:

```csharp
    public class Person
    {
        public Person(string foo) {
            DoFoo(foo);
        }

        public virtual void DoFoo(string foo) { ... }
    }
```

Category: `Usage`
Diagnostic Id: `CC0067`
Severity: `Warning`

**Comment by andrecarlucci** [comment]
I'll do it!

**Comment by sharwell** [comment]
Should this be in the **Usage** category since it is a duplicate of [CA2214](http://msdn.microsoft.com/en-us/library/ms182331.aspx)?

**Comment by andrecarlucci** [comment]
I got this from resharper, I didn't notice it was also on Code Analysis. 
So yes, it should. I edited there, thanks @sharwell !

**Comment by giggio** [comment]
Go for it, @andrecarlucci.

**Comment by giggio** [comment]
@andrecarlucci How is this coming?

**Comment by andrecarlucci** [comment]
I finally finished (this saturday) my project with Intel and have some free
time :)

André Carlucci
twitter/andrecarlucci
Microsoft MVP
Intel Innovator
www.andrecarlucci.com

**Comment by giggio** [comment]
Anxiously awaiting for your PR! :)
