### ISSUE TITLE
Convert Design fixes to VB

### ISSUE THREAD

**Issue by jwooley** [code-cracker/code-cracker#205]
Convert the Analyzers and Code Fixes in the Design folder to VB

**Comment by giggio** [comment]
@jwooley Why only the design folder? https://github.com/code-cracker/code-cracker/tree/master/src/CSharp/CodeCracker/Design

**Comment by jwooley** [comment]
I was trying to break this down by pieces rather than having a single task for all VB conversions. I already have most of the design ones fixed and started on the perf ones anyway. I didn't want to create work items for each analyzer/fix/test combo at this time. We can handle it which ever way you want of course. I'm not as familiar with this board structure yet.

**Comment by carloscds** [comment]
@jwooley Thanks Jim.

**Comment by giggio** [comment]
@jwooley Ok, I hadn't understand. So you are already working on it?

**Comment by jwooley** [comment]
I have started working on some of them if for no other reason to help me learn more. I haven’t checked anything in as I was waiting to hear if work was approved on it. It looks like Adam Speight may be doing some similar work as well.

**Comment by AdamSpeight2008** [comment]
I was but I think my Visual Studio installation is FUBAR-ed,

**Comment by giggio** [comment]
@jwooley Try to create a Pull Request as soon as possible so we can help you. A big bag PR is harder to work on.
@AdamSpeight2008 don't use the 2013 version, it won't work. A lot has changed.
You can reset the VS 2015 experimental instance with this command:

````bat
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VSSDK\VisualStudioIntegration\Tools\Bin\CreateExpInstance.exe" /Reset /VSInstance=14.0 /RootSuffix=Roslyn
````

**Comment by AdamSpeight2008** [comment]
@giggio Previously tried it. So fresh install it was.

**Comment by AdamSpeight2008** [comment]
By use [this](https://github.com/code-cracker/code-cracker/issues/214#issuecomment-69655421) proposal. By simply changing the language referred to in inheritance, it'll reveal the aspects of the code that need to be changed for compatibility.

**Comment by giggio** [comment]
@jwooley I will close this issue, you can continue to submit PRs for each analyzer individually as you have been doing!
