### ISSUE TITLE
Remove unreachable code

### ISSUE THREAD

**Issue by ElemarJR** [code-cracker/code-cracker#21]
This:

````csharp
void Foo()
{
    return;
    var a = 1; //unreachable
}
````

Will have the `var` line declaration marked as `WellKnownDiagnosticTags.Unnecessary`.
And will become:

````csharp
void Foo()
{
    return;
}
````

Should work for any possible unreachable code, like statements after `throw`, `else` that will never be reached, etc.

Category: `Usage`
Diagnostic id: `CC0055`
Severity: `Info`

**Comment by giggio** [comment]
I will work on it.
