### ISSUE TITLE
BUG on PrivateSetAnalyzer when there are no accessors

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#217]
This code will throw:

````csharp
class Foo
{
    public int Bar { }
}
````

The throw happens on this line:

https://github.com/code-cracker/code-cracker/blob/master/src/CSharp/CodeCracker/Style/PropertyPrivateSetAnalyzer.cs#L44

**Comment by giggio** [comment]
@carloscds This is yours, I think it is a simple fix. Can you check?

**Comment by carloscds** [comment]
@giggio Fixed. I will submit as new PR.

**Comment by giggio** [comment]
Fixed on #218.
