### ISSUE TITLE
CTP5 nuget "The assembly <...> does not contain any analyzers"

### ISSUE THREAD

**Issue by ljw1004** [code-cracker/code-cracker#229]
I installed VS2015 CTP5. I created a VB console app. I added a NuGet reference to the bilingual CodeCracker nuget package. But when I build, it claims not to find any analyzers [see screenshot]
![no-analyzers](https://cloud.githubusercontent.com/assets/3316258/5862523/84623282-a227-11e4-95ab-5d280269c23d.png)

**Comment by giggio** [comment]
Yes, we don't have any analyzers yet on VB. We need our VB enthusiasts to help us with those. Some people started working on it, but no PR yet. I am waiting on @jwooley, @BrunoMaestro, @AdamSpeight2008 and @ElemarJR. I think they all have something to show, but still nothing is here yet.

**Comment by jwooley** [comment]
I'm trying to resolve two errors in unit tests and then I should have a PR with Design and Performance analyzer/code providers.

**Comment by giggio** [comment]
Nice, @jwooley!

**Comment by jwooley** [comment]
I submitted a pull request for this update. It may need some modifications to incorporate some changes from the main trunk. I welcome code reviews on these as they are the first fixes I've done at this scale.

**Comment by giggio** [comment]
I am working on it. I will finish it over the weekend for sure. I fixed some details on it, but from the look I took at this morning it looks good. You put a lot of effort there, even if I find minor details I believe I will accept it and we can work on them as the project progresses.

**Comment by jwooley** [comment]
@giggio As long as you don't have any test errors or issues with the base class implementation, I would recommend taking these and then adding individual issues to fix specific analyzer/code fix implementations as necessary so that we don't have to deal with such massive pull requests in the future.

@ljw1004 I welcome any feedback you have on the implementation. Roslyn has a very large surface area and I'm sure there are areas where I could be doing things easier.

**Comment by giggio** [comment]
@ljw1004 Build `alpha3-0331` is up on myget with the analyzers that @jwooley worked on. We will publish `alpha3` at the end of the month.

**Comment by giggio** [comment]
Version 1.0.0-alpha3 is up on nuget now, with the VB analyzers.

**Comment by carloscds** [comment]
Good!
