### ISSUE TITLE
Use ConfigureAwait(false) on awaited task

### ISSUE THREAD

**Issue by thomaslevesque** [code-cracker/code-cracker#235]
Best practice dictates that `ConfigureAwait(false)` should always be used in library code, unless the async operation specifically needs to resume on the original `SynchronizationContext`. So I think it would be useful to create an analyzer for this.

- Level: not sure whether the level should be *Information* or *Warning*.
- Code fix: obviously, call `ConfigureAwait(false)` on the awaited task

**Scenario**

    await FooAsync();

becomes 

    await FooAsync().ConfigureAwait(false);

Another thing to consider: should the analyzer warn only on the first awaited task in the method, or all of them? Unless I'm mistaken, if `ConfigureAwait(false)` is used on the first `await`, it's not necessary to use it on the others, since we have already "lost" the `SynchronizationContext`, so there isn't a SC to capture anyway.

Diagnostic Id: `CC0070`
Severity: `Hidden` (Refactoring)
Category: `Reliability`

**Comment by giggio** [comment]
This makes sense for codecracker code itself, but how would we know if the code we are analyzing is library code or not?

**Comment by sharwell** [comment]
@giggio You don't, but the user does and can disable the diagnostic if it doesn't apply to the project they are working on.

**Comment by thomaslevesque** [comment]
> You don't, but the user does and can disable the diagnostic if it doesn't apply to the project they are working on.

Yes, that's what I had in mind

**Comment by giggio** [comment]
I think this is inverted, it should be disabled by default, and if the project is a library the programmer can turn it on. Most projects are not libraries, by definition, right?
What severity do you have in mind? Info? And what category?

**Comment by thomaslevesque** [comment]
> I think this is inverted, it should be disabled by default, and if the project is a library the programmer can turn it on. Most projects are not libraries, by definition, right?

Well, it depends... Most of my solutions contain one or two application projects, and many class library projects. *Some* class libraries don't need `ConfigureAwait(false)` (the UI-related ones), but the others do.

Also, what bothers me is that if the analyzer is disabled by default, it won't be easily discoverable: people will not enable it unless they know it exists.

> What severity do you have in mind? Info? And what category?

**Severity**: *Information* would probably be the best choice. Not using `ConfigureAwait(false)` doesn't necessarily make the code wrong, but:
- it can alter performance because of the overhead of switching back to the captured context
- if the caller synchronously waits for the task to complete (using `.Wait() ` or `.Result`), it can cause a deadlock. It's the caller's fault, so we probably shouldn't warn in the library code, but we can still inform about it.

**Category**: I'm not sure... this diagnostic is both about performance and reliability (because of the deadlock issue). I guess we should pick the most serious one: reliability.

**Comment by giggio** [comment]
I am still not sure we should add this to CodeCracker, as it's diagnostic is correct only part of the time.
@code-cracker/owners What do you think?

**Comment by thomaslevesque** [comment]
> I am still not sure we should add this to CodeCracker, as it's diagnostic is correct only part of the time.

Well, if a diagnostic needs to be always correct to be included in CodeCracker, I can think of many others that shouldn't be in it either... Most of them can't possibly be always correct, because it depends on context, opinion, etc. For instance, there are legitimate usages for an empty catch block; yet, CodeCracker reports it as an error... it's certainly not always correct.

**Comment by carloscds** [comment]
If user can suppress any analyzer for class, project or file. Analyzer can be active by default and developer decides when and how deactivate it.

**Comment by giggio** [comment]
@thomaslevesque the analyzer should be correct most of the time. Users can suppress it any time in a variety of ways, when it does not meet what they need. They can change the severity for the whole project or solution, they can disable it for a method, class, namespace, etc. When the diagnostic is correct only part of the time, but we still want the code fix, we are treating it as a refactoring. As since refactorings can't be deployed through nuget, we are using hidden analyzers.
Maybe we could have this one be a hidden analyzer, so the user has the ability to CTRL DOT and it will insert it for him/her, but could change it to info, warning or error for some specific project by editing the .ruleset. What do you think?

**Comment by thomaslevesque** [comment]
@giggio, OK, I get your point. I agree, we can make it a hidden analyzer.

I'm willing to work on this; I'll submit a pull request when it's done.

**Comment by giggio** [comment]
@thomaslevesque Perfect. I will set set it to working then. I have updated the issue's description with the info we discussed, plus a diagnostic id. I set it to reliability (you can read the categories description on #97).

**Comment by thomaslevesque** [comment]
OK, thanks. Any idea about the other point I raised in the first message?

> Another thing to consider: should the analyzer warn only on the first awaited task in the method, or all of them? Unless I'm mistaken, if ConfigureAwait(false) is used on the first await, it's not necessary to use it on the others, since we have already "lost" the SynchronizationContext, so there isn't a SC to capture anyway.

**Comment by giggio** [comment]
I think we should discuss that directly with the C# team. I am not sure. @sharwell @carloscds Do you know?

**Comment by sharwell** [comment]
@thomaslevesque Within a single method, after the first time you use `ConfigureAwait(false)` you will not execute any continuation on the original synchronization context prior to returning from the method. Since this is counter-intuitive for many developers, I would actually recommend issuing a warning for any `await` operation that does not using `ConfigureAwait(false)` following an `await` operation that *does* use `ConfigureAwait(false)`. Note that this would apply to any `async` method (library code or final application).

```csharp
Control control = ...;
control.Background = new SolidColorBrush(Colors.Blue);
await Task.Delay(500); // no warning
control.Background = new SolidColorBrush(Colors.Red);
await Task.Delay(500); // possible warning¹
await Task.Delay(500).ConfigureAwait(false); // no warning
await Task.Delay(500); // warning: implicit ConfigureAwait(false) should be explicit
control.Background = new SolidColorBrush(Colors.Green); // will throw exception²
```

¹ This would be an advanced warning because no code was executed between returning from an `await` that did not use `ConfigureAwait(false)` and entering the next `await` which *does* use `ConfigureAwait(false)`. Since it's unlikely to apply in real scenarios.

² Users might think this is fine because the previous `await` did not use `ConfigureAwait(false)`. Issuing a warning will catch cases where the earlier call to `ConfigureAwait(false)` is off the top of the current window, and also cases where a new `await` operation in an existing method changes the behavior of calls later in the method.

**Comment by giggio** [comment]
@sharwell I did not understand the justification for the first warning. The second one makes sense.

I agree with Sam that this is not at all obvious and we should warn the programmer so they know they have to add a `ConfigureAwait` on all of the awaits to make them explicit.

**Comment by sharwell** [comment]
@giggio The first warning is a performance warning only. It's easy to see that the code between that line and the next one did not need to execute on the method's synchronization context, because there is no code between the two.

**Comment by thomaslevesque** [comment]
> Within a single method, after the first time you use ConfigureAwait(false) you will not execute any continuation on the original synchronization context prior to returning from the method. Since this is counter-intuitive for many developers, I would actually recommend issuing a warning for any await operation that does not using ConfigureAwait(false) following an await operation that does use ConfigureAwait(false). Note that this would apply to any async method (library code or final application).

I understand your point, but don't really agree... Sure, it makes it explicit that you don't want to resume on the original synchronization context; but in this case I would personally prefer implicitness. Having `ConfigureAwait(false)` littered all over the method doesn't help readability, and is actually redundant (since the code behaves the same way without it). So, *ideally*, I would prefer to warn only on the first await.

Unfortunately, I just realized that this ideal isn't possible... Take this code for instance:
```csharp
async Task FooAsync(bool b)
{
    if (b)
        await DoSomethingAsync().ConfigureAwait();
    await DoSomethingElseAsync();
}
```
Depending on the value of `b`, the second await will resume on the original context (if `b` is false), or not (if `b` is true)... so there is no way to know if we should use `ConfigureAwait(false)` in the second case.

So I think the only sensible thing to do here is to trigger the diagnostic on all awaited tasks. We *could* check if there is a `ConfigureAwait(false)` that belongs to all execution paths, and not trigger the diagnostic in this case... but it would make the analyzer much more complex.

**Comment by thomaslevesque** [comment]
OK, I implemented the analyzer and code fix; the unit tests pass, as well as the test against corefx.

However the fix doesn't appear... if the level is set to Hidden, the light-bulb doesn't appear, and if it is set to Warning, the light-bulb doesn't show the fix (only the option to suppress the diagnostic). I must have missed something, but I can't find what... I'm still new at writing analyzers.

Do you have any idea what would be wrong? The current code is here:
https://github.com/thomaslevesque/code-cracker/tree/issue235/src/CSharp/CodeCracker/Reliability

**Comment by thomaslevesque** [comment]
OK, just tried again after restarting VS, and now it works as expected... I think it's because I tried to replace the analyzer from the NuGet package with the one from the output folder, to test CodeCracker on itself. I'll create the PR now.
