### ISSUE TITLE
False positive on CC0049 ("You can remove this comparison")

### ISSUE THREAD

**Issue by thomaslevesque** [code-cracker/code-cracker#236]
Consider this code in a WPF app:

            var dlg = new OpenFileDialog {Filter = "GIF files|*.gif"};
            if (dlg.ShowDialog() == true)
            {
                ...
            }

CodeCracker seems to think that the `== true` is redundant, but it's not, because `ShowDialog()` returns a `Nullable<bool>`, not a `bool`. Removing the comparison would cause a compile error.

@thomaslevesque is working on it. PR #239

**Comment by AdamSpeight2008** [comment]
It shouldn't. by

**Comment by thomaslevesque** [comment]
> It shouldn't.

should'nt cause a compiler error, you mean? Well it does... and that's not something new in Roslyn, it was the same in the old compiler.

> the if condition accepts an expression whos evaluation is bool or castable to bool.

Yes, if it is *implicitly* castable to bool... it's not the case for `Nullable<bool>`, it only has an explicit conversion to bool.

**Comment by AdamSpeight2008** [comment]
So it'll need to check if the first parameter is `Bool?` and the second parameter `Bool`. To skip it.
The `Bool` is being implicitly widened (upcast) to `Bool?`

**Comment by thomaslevesque** [comment]
> So it'll need to check if the first parameter is Bool? and the second parameter Bool. To skip it.

Better yet: check that both operands are of type `bool`, and nothing else. Otherwise it can get ugly pretty fast...The condition of an `if` statement doesn't actually need to be of type `bool`. According to the C# 5 spec, it has to be a *boolean-expression* (§7.20):

> A boolean-expression E is required to be able to produce a value of type bool, as follows: 
•	If E is implicitly convertible to bool then at runtime that implicit conversion is applied.
•	Otherwise, unary operator overload resolution (§7.3.3) is used to find a unique best implementation of operator true on E, and that implementation is applied at runtime.
•	If no such operator is found, a binding-time error occurs.

So you have several cases to consider :
(assuming the right-hand-side operand is a compile-time constant of type `bool`)

1. if the left-hand-side operand is of type `bool`: you can remove the comparison
2. if the LHS is implicitly convertible to `bool`: you can remove the comparison
3. if the LHS overloads the `==` operator for `bool`: you *cannot* remove the comparison (unless you're in case 2)
4. if the LHS overloads the `true` operator, you can remove the comparison

Actually, in cases 2 and 4 it's not even safe to do it. There are contrived cases where `if (foo)` isn't the same as `if (foo == true)`, or other similar surprises. It can happen if operators (equality/inequality with bool, implicit conversion to bool, true/false operators) are not implemented consistently. See [this evil code](https://gist.github.com/thomaslevesque/fb0d689042deb52b747c) for instance.

IMO, trying to cover all those cases would be a good way to lose your sanity ;). So, the safest option is probably to keep it simple and only handle the case where both operands are `bool`.

Also, I noticed that the current implementation is not symmetric. it should work if the operands are reversed: `if (true == myBoolVariable)` can be simplified to `if (myBoolVariable)`.

>     if( res?.Value )

No, this is not valid. When you use `?.` on a nullable value type, you access the value directly if there is one. So it would mean the same as : `if (res.HasValue ? res.Value.Value : null)`, which is not valid.

Another valid way to write it would be `if (dlg.ShowDialog() ?? false)`, but it's more confusing than `if (dlg.ShowDialog() == true)` IMO...

(wow, this comment got a lot longer than I intended...)

**Comment by giggio** [comment]
I have confirmed the bug. It is ready and up for grabs. I will create another issue about the simetry problem.

**Comment by viniciushana** [comment]
@giggio go take some rest you maniac! :)

**Comment by thomaslevesque** [comment]
> It is ready and up for grabs.

I see what needs to be changed; I'll take it if you want (and #238 as well; since it affects the same analyzer, I might as well kill two birds with one stone)
