### ISSUE TITLE
Issues with CC0047 "Consider use a 'private set'"

### ISSUE THREAD

**Issue by thomaslevesque** [code-cracker/code-cracker#237]
This warning seems to be triggered on all public properties. For instance:

        private bool _autoStart = true;
        public bool AutoStart
        {
            get { return _autoStart; }
            set
            {
                _autoStart = value;
                OnPropertyChanged("AutoStart");
            }
        }

In this case, it is incorrect, because the property is used in a XAML binding. I don't think CodeCracker can detect that, but the class is public, so it shouldn't make assumptions about how it will be used. The assembly could be referenced by something else that relies on the setter being public. IMO this warning should never appear on properties of a public class.

Another issue is that the warning appears twice for each property: the first occurrence has no additional description, and the second one also says "Use private set for automatic properties". But these properties are not auto-properties...

**Comment by carloscds** [comment]
@thomaslevesque Property can be public for get and private for set. There any many sample that on I need private set but public get.

**Comment by thomaslevesque** [comment]
> @thomaslevesque Property can be public for get and private for set. There any many sample that on I need private set but public get.

Yes, I'm aware of this, but it doesn't change what i was saying. If the property is used in a two-way binding, it needs to be public. And the setter might also be used by external code, so you can't just assume that it could be private. You could if the class were internal (because then you could know of all usages of the property setter), but not if it's public.

**Comment by carloscds** [comment]
@thomaslevesque It's make sense. But we don't know all project if developer and analyzer make a suggestion, only this. It's not an error, it's a hidden analyzer, like a refactoring. If developer choose to change to private set, we think that he know your solution and possible problems for this kind of change.

**Comment by thomaslevesque** [comment]
> It's not an error, it's a hidden analyzer

I would be fine with it if it was hidden, but it's not... at least not by default:

![screenshot](http://i.imgur.com/eYZA4UK.png)

I find it quite obtrusive for a hidden analyzer ;)
Was it intended to be hidden?

**Comment by carloscds** [comment]
According with sourcecode, this analyzer is hidden. Look at source (https://github.com/code-cracker/code-cracker/blob/master/src/CSharp/CodeCracker/Style/PropertyPrivateSetAnalyzer.cs)  line 25. Initially this analyzer was not hidden, but we think that is less intrusive in this way.

**Comment by thomaslevesque** [comment]
Oh I see; that's because I'm using the NuGet package, which dates back to December 15th...
OK then; it's fine if it's hidden.

**Comment by carloscds** [comment]
@thomaslevesque Great! Thanks for your colaboration!

**Comment by giggio** [comment]
@thomaslevesque we will update the nuget in a few days.
