### ISSUE TITLE
Remove unused parameters

### ISSUE THREAD

**Issue by ElemarJR** [code-cracker/code-cracker#24]
This:

````csharp
int Foo(int a, int b)
{
    return a;
}
````

Becomes:

````csharp
int Foo(int a)
{
    return a;
}
````

Don't offer a diagnostic if:

* The method is an interface implementation or an override.
* It is a constructor on a serializable object (see pattern [here](http://msdn.microsoft.com/en-us/library/ms973893.aspx)).
* It is an event handler (`object` and then an `EventHandler`).

This is a `Warning`, Category `Usage`.
Diagnostic id: `CC0057`

**Comment by giggio** [comment]
This was one of the most fun ones to work on. The code fix alters the whole solution.
