### ISSUE TITLE
Introduce field from constructor

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#241]
This is a refactoring.

The idea is that on a constructor parameter you CTRL DOT and get a "Introduce field" dialog, that will create a field and assign the value from the parameter to the field.

So this:

````csharp
class Foo
{
  public Foo(string bar)
  {
  }
}
````

Becomes:

````csharp
class Foo
{
  private readonly string bar;
  public Foo(string bar)
  {
    this.bar = bar;
  }
}
````

If the field is already assigned then no diagnostic is offered.
If the field is already present, it is just assigned to.
If the type does not match (e.g. parameter is `string`, existing field is `int`, a new field with `1` postfixed is added, like that:

````csharp
class Foo
{
  private int bar;
  public Foo(string bar)
  {
  }
}
````

Becomes:

````csharp
class Foo
{
  private int bar;
  private readonly string bar1;
  public Foo(string bar)
  {
    this.bar1 = bar;
  }
}
````

Diagnostic Id: `CC0071`
Severity: `Hidden` (refactoring)
Category: `Refactoring`

**Comment by carloscds** [comment]
@giggio It's mine!

**Comment by giggio** [comment]
I knew this one was not going to stay up for too long. It is too useful. :)

**Comment by carloscds** [comment]
@giggio It's done. But I have a little change:

So this:

````csharp
class Foo
{
  public Foo(string bar)
  {
  }
}
````

Becomes:

````csharp
class Foo
{
  private readonly string _bar;
  public Foo(string bar)
  {
    this._bar = bar;
  }
}
````
This avoid change name of parameter if there is a field with same name.

**Comment by giggio** [comment]
@carloscds I don't agree with the underline. I will comment on the PR.

**Comment by carloscds** [comment]
@giggio I have submit a fix for this and a comment on the PR.
