### ISSUE TITLE
Use enum for diagnostic ids (VB)

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#244]
Similar to #228 but for VB.

@jwooley is working on it.

**Comment by jwooley** [comment]
I can take care of this.

**Comment by giggio** [comment]
Cool, @jwooley, it is yours. Right now we are going to duplicate the `DiagnosticId` enum, later we can unify them in a single assembly that C# and VB will depend on.

**Comment by jwooley** [comment]
Pull request submitted.
