### ISSUE TITLE
If method does not return a Task it shouldn't end with "Async"

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#245]
This is the opposite of #178:

````csharp
void FooAsync() { }
````

Becomes:

````csharp
void Foo() { }
````

The `async` keyword is not necessary for the method to have the `Async` postfix. All it needs to be async is to return a `Task`.
When renaming the method, all references have to be renamed as well and no code should break.
Should work on interfaces as well.

Category: `Style`
Diagnostic Id: `CC0072`
Severity: `Info`

**Comment by carloscds** [comment]
It's mine.

**Comment by giggio** [comment]
Ok, are you working on it already? When you start move it to Working. I ask because you were working on another one. :)

**Comment by carloscds** [comment]
@giggio Let's go code!
