### ISSUE TITLE
Unify DiagnosticId class on a separate assembly

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#248]
Right now it is doubled on VB and C# projects. It would nice to have a "core" project.

**Comment by jwooley** [comment]
I'd be happy to help out as well. There are a number of other helpers/extension methods that would be good candidates for centralizing as long as the centralized library doesn't take a dependency on either the C# or VB specific CodeAnalysis libraries/workspaces. I would also recommend making a CodeCracker.Test.Shared library which could possibly take the dependency on both the VB and C# libraries and include the Helpers and Verifiers.

**Comment by jwooley** [comment]
Another thing to consider if centralizing this would be to put the DiagnosticID implementation into a resource to support language translations for the description/messages/etc.

**Comment by giggio** [comment]
@jwooley We are going slowly on this items on purpose, so we have time to discuss them. This would be a small first step on creating a common dependency. Let's do that first, and see how it goes. I agree that there is a lot of work after that. :)

**Comment by carloscds** [comment]
@giggio I think that for test purpose at this moment it[s a good idea.

**Comment by giggio** [comment]
Ok, we have just finished discussing, I will create a CodeCracker.Common project and include in the project. I will move the DiagnosticId and Helper into this new assembly and add it to both solutions.
