### ISSUE TITLE
[Bug] CC0057 Displayed even if the parameter is used.

### ISSUE THREAD

**Issue by thorgeirk11** [code-cracker/code-cracker#255]
![cc0057 bug](https://cloud.githubusercontent.com/assets/2693474/6053487/e03715b8-acd7-11e4-8f18-8603ce6a7c2a.png)

As can be seen the warning is displayed in a constructor that passes the argument to the parent.

**Comment by thorgeirk11** [comment]
Sorry It is the same as #251

**Comment by giggio** [comment]
Exactly.
