### ISSUE TITLE
CC0031 Formatting bug on comments

### ISSUE THREAD

**Issue by thorgeirk11** [code-cracker/code-cracker#257]
![cc0031 bug](https://cloud.githubusercontent.com/assets/2693474/6053718/f0306a02-acda-11e4-87eb-a9ec695c2b30.png)

When there is a comment right above the invocation the formating of the code fix is abit off. 
```C#
// Calling Callback
OnDoneCallback();
```
Results in:
```C#
var handler =
    // Calling Callback
    OnDoneCallback;
if (handler != null)
    handler();
```

**Comment by giggio** [comment]
Bug confirmed.
