### ISSUE TITLE
BUG on CC0021 (NameOf) when using attribute

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#258]
This will incorrectly generate `CC0021` on the firstLine:

````csharp
[InlineData("typeName")]
public void Foo(string typeName)
{
}
````

Attributes should not be checked on the `NameOfAnalyzer`.

**Comment by sharwell** [comment]
Does `NameOfAnalyzer` only check parameter names? This is a valid us of `nameof`:

```csharp
[InlineData(nameof(Foo))]
public void Foo(string typeName) { }
```

**Comment by giggio** [comment]
@sharwell yes, AFAIK. But we could expand it. :)
