### ISSUE TITLE
Expand NameOf Analyzer to work with any identifier in scope

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#263]
Right now `CC0021` is only working with function parameters. It should work with any analyzer in Scope, so class names, functions names, etc.
Code fix does not need to be updated, it should work as is.

**Comment by jwooley** [comment]
Should be updated in c# and VB

**Comment by baks** [comment]
I recently worked on #198 concerning NameOfAnalyzer so if possible I could take this one.

**Comment by giggio** [comment]
@baks Ok, go ahead, it is yours. If you find the problem from #198 problem here just update it as well.
I invited you to the collaborators team so I can assign it to you.

**Comment by baks** [comment]
@giggio Thank you for invitation

**Comment by giggio** [comment]
VB is pending, issue #341 was opened so we don't forget.
