### ISSUE TITLE
Proposal: Add code fixes for VB6 legacy methods

### ISSUE THREAD

**Issue by jwooley** [code-cracker/code-cracker#265]
Optional code fixes for VB only:
Replace the old non-short circuiting IIF with the new ternary If(true,truepart, falsepart)
Replace Mid/Left/Right with string.Substring
Inline local declaration (VB and C#)
Replace string concatenation for multi-line strings with VB 14 multi-line strings
Others that should be considered?

**Comment by paulomorgado** [comment]
@jwooley, is the `String.Substring` a full replacement for `Mid`/`Left`/`Right`?

**Comment by giggio** [comment]
@jwooley I am all for it, but only for those that have a perfect match on the BCL. AFAIK, most of those methods do a lot of work. Can't we end up breaking code?
I like the IIF replacement, it has performance impacts.
We could also replace the convertions, CType, etc.
Also, can you update your description with some code snippets we can look at?

**Comment by paulomorgado** [comment]
Maybe some can be converted with the aid of the `?.` operator.

**Comment by giggio** [comment]
What do you mean, Paulo?

**Comment by paulomorgado** [comment]
I was wondering if this as something that could be safely translated to `?.Substring(...)`. But I don't know idiomatic VB that much.

**Comment by giggio** [comment]
@jwooley We have discussed about this item, and we find that it makes sense. But this issue would be too big. Go ahead and create issues with descriptions for each of the suggestions and we can work on each of them individually.
