### ISSUE TITLE
Review AllowMembersOrderingCodeFixProvider.Base to avoid running analyzis on ComputeFixesAsync method

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#273]
Right now `AllowMembersOrderingCodeFixProvider.Base.cs` is running a lot of analysis on the `ComputeFixesAsync` method. Ideally this would run on a different task, passed to the `CodeAction.Create` method.
This is because when the user has the cursor over the text span that generated a diagnostic, `ComputeFixesAsync` is always called, even if the user does not click on the light bulb or `ctrl .`, so running a lot of analysis on that method can make Visual Studio slower even if the user has not yet selected the fix yet.

**Comment by codecrackerbuild** [comment]
Build passed! Details: https://ci.appveyor.com/project/code-cracker/code-cracker/build/1.0.0.402

**Comment by codecrackerbuild** [comment]
Teste

**Comment by jwooley** [comment]
Let me know if you need assistance with applying the changes to the VB translation as well.

**Comment by giggio** [comment]
@code-cracker/owners I reviewed the analyzer, but there is not much to be done. I cleaned it up on 1bf139a8e6b5afef77e1c2dccc9bf752f8a7bd7d, but as you can see, nothing really changed.
I have confirmed that the `ComputeFixesAsync` method is being called whenever the analyzer reports a diagnostic and the user has the cursor over the class identifier. A diagnostic is only reported if the type has at lest 2 members, so new classes, which tend to change name, accessability, etc more often, will not get the diagnostic. But every single time the user passes over that initializer (or its trivia, etc) will the code fix runs. If we add 5 other ordering providers, we will get 5 code fix providers being called all the time when the user is navigating the source, and 5 extensive analysis/document/syntax tree manipulation goes on.
Because of that I am considering that, as soon as we start to get more ordering providers, we could simply disable them all and let the user enable as they wish. Or maybe we should measure the impact of having all these fixes running, but we don't have a way to do that yet. What I don't want is to have CodeCracker slowing down Visual Studio.

What do you think?

**Comment by carloscds** [comment]
@giggio Maybe we can check diagnostics before continue.
