### ISSUE TITLE
CC0031 Bug in switch statement ?

### ISSUE THREAD

**Issue by thorgeirk11** [code-cracker/code-cracker#275]
```C#
switch (true)
{
    default:  return Callback();
}
```
Results in:
```C#
switch (true)
{
default:
    var handler = Callback;
    if (handler != null)
        handler();
}
```
Notice that the break statement is missing and the control flow has altered.

Is this a bug or just the way it should be ?

**Comment by giggio** [comment]
@thorgeirk11 I just tried to repro and the code fix worked as expected:

![image](https://cloud.githubusercontent.com/assets/334958/6204940/25af41b0-b543-11e4-9aac-6b0ff0503792.png)

Are you using VS 2015 CTP 5 and the latest CodeCracker version?

I am closing this issue for now. We need to be able to repro. If you can offer the complete code where you got the issue than we can fix it! :)
