### ISSUE TITLE
RemovePrivateMethodNeverUsedAnalyzer (CC0068) throwing cast exception

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#276]
`RemovePrivateMethodNeverUsedAnalyzer` is throwing when analyzing Mono Cecil:

````
The Compiler Analyzer 'CodeCracker.Usage.RemovePrivateMethodNeverUsedAnalyzer' threw an exception with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.MemberAccessExpressionSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.IdentifierNameSyntax'.'. 
````

See details on 395: build https://ci.appveyor.com/project/code-cracker/code-cracker/build/1.0.0.395

The analyzer is being disabled so the build does not fail anymore.

@julianosaless is fixing it.

**Comment by giggio** [comment]
@julianosaless can you work on this one?

**Comment by julianosaless** [comment]
@giggio OK I will work :)
