### ISSUE TITLE
Align Equals on Variable Assignment statements

### ISSUE THREAD

**Issue by GersonDias** [code-cracker/code-cracker#29]
When I have:

````csharp
var var1 = 2;
var longNameVar = 4;
````

I wanna fix to:

````csharp
var var1        = 2;
var longNameVar = 4;
````

to improve readability.

This is a `Hidden` diagnostic.
Diagnostic Id is: `CC0041`
Category is: `Style`.

**Comment by giggio** [comment]
@GersonDias Are you still planing to work on this one?

**Comment by GersonDias** [comment]
@giggio I'm a little busy, but I will work on that!

**Comment by giggio** [comment]
@GersonDias How is this coming? Are you still going to work on it?

**Comment by GersonDias** [comment]
@giggio unfortunately I wont have time to work in this. You can put this back to backlog... free for grabs.

**Comment by AlbertoMonteiro** [comment]
@GersonDias you can do this with this extension https://visualstudiogallery.msdn.microsoft.com/7179e851-a263-44b7-a177-1d31e33c84fd

Btw I also agree @viniciushana

**Comment by carloscds** [comment]
@AlbertoMonteiro IMHO if there is an extension for this, it´s not necessary create an analizer too.

**Comment by giggio** [comment]
Should we close this?

**Comment by GersonDias** [comment]
Yep! Let's focus on more important things!
Em 5 de jan de 2016 9:05 AM, "Giovanni Bassi" <notifications@github.com>
escreveu:
