### ISSUE TITLE
BUG: Method not used (CC0068) fails to check partial classes

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#290]
If a method is referenced on a partial class, but on a different document (and syntax tree) CC0068 will be generated incorrectly.
Affects C# and VB.

**Comment by ElemarJR** [comment]
How would you like to fix this one. The easy way is make it works only with no partial class. What do you think?

**Comment by giggio** [comment]
@ElemarJR Not necessary. All you need to do is, when checking the method's parent type, if it has the `partial` modifier, get the symbol, and ask for `typeSymbol.DeclaringSyntaxReferences`, then on each type node, continue the verification.

**Comment by ElemarJR** [comment]
I'm back! Is my PR good enough? Could I do that in VB?

**Comment by giggio** [comment]
Great!
