### ISSUE TITLE
BUG: Create code fix for update ReadonlyFieldCodeFixProvider so that the code does not break on public fields

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#293]
See discussion on #292, specifically this comment: https://github.com/code-cracker/code-cracker/pull/292#issuecomment-77065161

The code fix from `NoPrivateReadonlyFieldAnalyzer` (CC0074) is handled by the same code fix provider from the private analyzer, on `ReadonlyFieldCodeFixProvider`. As the `CC0074` is only generated at the end of the compilation stage, it will produce a diagnostic that might be later fixed by the user but won't be notice until the next compilation ends. That might take time. In the mean time, the user might apply the code fix, breaking his/her code.

This only happens for the non private analyzer, the other analyzer works perfectly because it is private, and the analysis context is smaller.

The code fix should be updated, or another one created, so that it runs the analysis again before producing any change, to make sure it is still necessary. Another option is to update the analyzer to not incur in the problem anymore, but that is unlikely to be feasible.

After this is fixed `CC0074` should be enabled by default.

**Comment by carloscds** [comment]
@giggio I need to wait for a Roslyn bug fix: https://github.com/dotnet/roslyn/issues/1831

**Comment by giggio** [comment]
@carloscds With the `RC2` release the roslyn bug might have been fixed. Can you check?

**Comment by giggio** [comment]
@carloscds I think I know how to fix this. I am taking a look at it right now.

**Comment by giggio** [comment]
@carloscds 
I just tried verifying if the field was still readonly before offering a fix. It kind of worked, but not as I expected. See 77b62ba for how I tried it in my private branch.
What happens is that Visual Studio is caching the code fix registration. So, if I were to ask for a code fix, but not apply it, then go and add an assignment to the field, and then ask again before the next compilation ends, the code fix is cached and is still offered, and if the user applies it then, the code will break.
I propose that we either:

1. remove `NoPrivateReadonlyFieldAnalyzer` and remove `CC0074` or,
2. remove the ability for `ReadonlyFieldCodeFixProvider` to fix its diagnostic, `CC0074`.

And then close this issue.

I also want to point out that any code fix that wants to work on a diagnostic that is raised by an analyzer which depends on collecting info during the compilation and registers a diagnostic at the end will suffer the same problem and we should avoid them.

**Comment by giggio** [comment]
@carloscds @ElemarJR I need your opinion here. Otherwise I will remove this analyzer. We need to fix this to the 1.0 release.

**Comment by carloscds** [comment]
@giggio @ElemarJR It doesn't have any news in Roslyn about this. I guess that we can close it.

**Comment by giggio** [comment]
Closed on 0acb2cf. It is again enabled, but will not be incorrectly fixed.
