### ISSUE TITLE
Regex performance: use static Regex.IsMatch

### ISSUE THREAD

**Issue by akamud** [code-cracker/code-cracker#297]
We could diagnose code using Regex in a way that gives poor performances.

Creating a new Regex every time will give you a bad performance:

```C#
public static bool IsValidCurrency(string currencyValue)
{
  string pattern = @"\p{Sc}+\s*\d+";
  Regex currencyRegex = new Regex(pattern);
  return currencyRegex.IsMatch(currencyValue);
}
```

If this method is called multiple times, you should be using the [static `Regex.IsMatch`](https://msdn.microsoft.com/en-us/library/sdx2bds0%28v=vs.110%29.aspx) method, as that can be [cached](https://msdn.microsoft.com/en-us/library/gg578045(v=vs.110).aspx) and won't be interpreted every time you call the method, it will give you better performance.
This is quite common on email address validation during registration, or validating user input (like the currency example above or Zip codes).

Code fix:
```C#
public static bool IsValidCurrency(string currencyValue)
{
  string pattern = @"\p{Sc}+\s*\d+";
  return Regex.IsMatch(currencyValue, pattern); 
}
```
I created a [project](https://github.com/akamud/RegexPerformanceExamples/blob/master/RegexPerformanceExamples/Program.cs) showing the difference in performance, testing this case with only 10 runs shows that instance method is almost 3 times slower.
```
Instance took 0.000639 seconds
Static took   0.000240 seconds
```

Running this 100,000 times gives these results:
```
Instance took 0.3786505 seconds
Static took   0.0717608 seconds
```

I'm sure there are [more cases](http://blogs.msdn.com/b/bclteam/archive/2010/06/25/optimizing-regular-expression-performance-part-i-working-with-the-regex-class-and-regex-objects.aspx) of improving Regex performance that we could diagnose, but this one is pretty straightforward. What do you think?

Diagnostic Id: `CC0081`
Severity: `Info`
Style: `Performance`

@akamud is working on it.

**Comment by carloscds** [comment]
@akamud Very interesting. What do you think about try to implement this ?

**Comment by akamud** [comment]
@carloscds I would love to. What else can I do to give this a `Ready` status?

I'm editing the issue giving this a `Warning` level, given the description in the [contributing guidelines](http://code-cracker.github.io/contributing.html).

**Comment by carloscds** [comment]
@akamud Go ahead.

**Comment by akamud** [comment]
Great! I'll start right away.

**Comment by giggio** [comment]
@akamud @carloscds  The MSDN article states that only 15 Regexes are cached by default.
I am not sure that we would want to cache in every circumstance.
Also, if the regex is called very often, the same article recommends that we use the `Compiled` option.

The question, both for the cache, and for the `Compiled` option is: can we determine through static analysis if a specific regex might be called multiple times?

I think that the only place where this is actually true is if we check for loops, like `while` and `for`. But even then, a method that uses regexes might be called inside a loop, and if we are analyzing the method can't quickly determine that the method is being called in such condition.

So we leave to the user to decide, as we can't know. It could be a good a idea to use cache and compilation, or it could be a bad idea. If we use too much cache we might make it useless, if we use compilation on a regex that is used only once we are wasting cycles.

So, for this reason, I believe this is an `Info`, not a `Warning`, as we defined it:

http://code-cracker.github.io/severity.html

We could also have 2 diagnostic ids, one for `Info`, and another for `Warning`, if found inside a loop. The code fix would be the same.

Also, the code fix could be: use static, use compiled, use both.

What do you think?

**Comment by akamud** [comment]
@giggio  I tried to keep those more complicated scenarios as an improvement, but I like your idea of changing this to `Info` and give the user the two options.

But now that you said, I'm not sure even when it is found inside a loop should be a warning, as tested [here](http://blogs.msdn.com/b/bclteam/archive/2010/06/25/optimizing-regular-expression-performance-part-i-working-with-the-regex-class-and-regex-objects.aspx) and stated in the article, better performances for compiled expressions depends on a variety of factors, including the pattern's complexity and, of course, how many times it is called, since we can't tell if the loop will run 10 or 10,000  times or determine how complex the Regex is, we shouldn't make the user believe he should use the compiled version every time, as that has a slower startup time that may not pay off.

This is really hard to get it right with the information we have when the user is writing the code, so maybe we should just show it as an `Info`. 

What do you think?

**Comment by giggio** [comment]
I am fine with that. It also makes the analyzer simpler. But I would still offer the 3 code fixes, they would be great.

**Comment by akamud** [comment]
Yeah, I agree with that, it's a great idea.

**Comment by carloscds** [comment]
Great!
