### ISSUE TITLE
Class that has IDisposable fields should implement IDisposable and dispose those fields

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#30]
If a class has a field that is `IDisposable`, it should `Dispose` it.

This will generate a `Info`:

``` csharp
class Foo
{
    private SomeDisposableClass disposableField = SomeDisposableClassFactory.Create();
}
```

Becomes:

``` csharp
class Foo : IDisposable
{
    private SomeDisposableClass disposableField = SomeDisposableClassFactory.Create();
    public void Dispose()
    {
        disposableField.Dispose();
    }
}
```

This will generate a `Warning`:

``` csharp
class Foo
{
    private SomeDisposableClass disposableField = new SomeDisposableClass();
}
```

Becomes:

``` csharp
class Foo : IDisposable
{
    private SomeDisposableClass disposableField = new SomeDisposableClass();
    public void Dispose()
    {
        disposableField.Dispose();
    }
}
```

This is a `Warning` because of the object creation.
Diagnostid ids are:
- for the `Info`: `CC0032`
- for the `Warning`: `CC0033`

**Comment by ischas** [comment]
If I follow the [Dispose Pattern](https://msdn.microsoft.com/en-us/library/b1yfkh5e(v=vs.110).aspx) I mistakenly get the warning CC0033.

Example (with a hopefully correct implemented disposing):

    public class A : IDisposable
    {
        private DisposableClass disposableField = new DisposableClass();
        private bool disposedValue;
    
        public void Dispose()
        {
            this.Dispose(true);
            GC.SuppressFinalize(this);
        }
    
        private Dispose(bool disposing)
        {
            if (!this.disposedValue)
            {
                this.disposableField.Dispose();
                this.disposableField = null;
            }
        }
    }

The analyzer would propose this:

    public void Dispose()
    {
        this.Dispose(true);
        GC.SuppressFinalize(this);
        disposableField.Dispose();
    }

**Comment by giggio** [comment]
@ischas Created issue #603 to track that.
