### ISSUE TITLE
Nameof analyser ignoring index parameters.

### ISSUE THREAD

**Issue by thorgeirk11** [code-cracker/code-cracker#308]
The nameof analyser is not picking up the parameter of a indexer function correctly:

In the following code the only the string inside the second throw is underlined.
```CSharp
int this[string x]
{
    get
    {
        if (x == null) throw new ArgumentNullException("x");
        return x.Length;
    }
}
int length(string x)
{
    if (x == null) throw new ArgumentNullException("x");
    return x.Length;
}
```

![image](https://cloud.githubusercontent.com/assets/2693474/7058405/f15ae2a2-de50-11e4-918d-2f0aa885b99a.png)

**Comment by giggio** [comment]
@thorgeirk11 This is a know issue. Issue #263 already takes care of this. Someone just needs to do it.
