### ISSUE TITLE
NameOf produces wrong results/

### ISSUE THREAD

**Issue by AdamSpeight2008** [code-cracker/code-cracker#309]
Ran code-cracker's VB version of `Use NameOf` of the Roslyn code base and it produce a lot of incorrect conversions. [See](https://github.com/dotnet/roslyn/pull/1879)
Now I have to manually go through them correct the errors.

I suspect that it if using only first argument's identifier of the method the "Code Fix" is suggested, rather than the on matching the value of the string.

**Comment by giggio** [comment]
@AdamSpeight2008 Was this a problem on the Batch Fixer? Did you ask for an update on the whole solution, project or document?

**Comment by AdamSpeight2008** [comment]
@giggio  I did a couple manual use of the  `Use NameOf` Code-Fix it produced the desired results, so then applied across the entire Roslyn solution. It wouldn't matter even if I had or hadn't use the Batch-Fixer, it still would have produced incorrect fixes.

 [The diff]](https://github.com/AdamSpeight2008/roslyn-AdamSpeight2008/commit/6e057340923154ccac01b30d36db780eec433425)

**Comment by giggio** [comment]
@AdamSpeight2008 I have been able to reproduce the problem. It only happens when fixing all in document or higher. It should be a quick fix. I will look into it myself.
