### ISSUE TITLE
Convert a "Not Any" query for a condition to a "All" query for the inverted condition

### ISSUE THREAD

**Issue by moreirayokoyama** [code-cracker/code-cracker#31]
## Scenario 1: simple condition

This:

````csharp
if (!results.Any(r => condition))
    throw new Exception("Error");
````

Becomes:

````csharp
if (results.All(r => condition == false))
    throw new Exception("Error");
````

or

````csharp
if (results.All(r => !condition))
    throw new Exception("Error");
````

## Scenario 2: special case `>`, `<`, `>=` and `<=`

This:

````csharp
if (!results.Any(r => r > 0))
    throw new Exception("Error");
````

Becomes:

````csharp
if (results.All(r => r <= 0))
    throw new Exception("Error");
````

So it became more readable.
This is a refactoring, there is no diagnostic.

This is essentially a refactoring, so we are classifying it as a `Hidden` diagnostic.
Category is `Refactoring`.
Diagnostic id is: `CC0043`

**Comment by giggio** [comment]
@moreirayokoyama Are you still planing to work on this one?

**Comment by giggio** [comment]
@moreirayokoyama I am assuming you are not working on this one and returning it to the backlog. If you would like to complete let us know!

**Comment by giggio** [comment]
I finished and added Any to All, and All to Any. Also added a lot of special cases. Check out:
https://github.com/code-cracker/code-cracker/blob/7b4bac8ed0f6fd1a5e6afc67d0aec4c55d1b3f1d/test/CSharp/CodeCracker.Test/Refactoring/ChangeAnyToAllTests.cs#L84-L178
