### ISSUE TITLE
Create infrastructure for testing multi culture values

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#313]
On #312 a test failed when we tested on a pt-BR version of VS. We need a way to verify these types of issues on our unit tests.
We need to discuss what would be the best approach to do this.

**Comment by giggio** [comment]
@ElemarJR @carloscds Any idea on how we could deal with this? I am thinking of maybe changing the current thread's culture and reverting at the end of the test, using a disposable object, like this:

````csharp
[Fact]
void Test()
{
    using (new ChangeCulture("pt-BR"))
    {
        //test code
    }
}
````

**Comment by carloscds** [comment]
@giggio @ElemarJR Test failed not because VS is pt-BR, but about Windows is localized for pt-BR, more specifically date and number formats. But your idea in code above it's valid.
