### ISSUE TITLE
VS crash on CC0016

### ISSUE THREAD

**Issue by thorgeirk11** [code-cracker/code-cracker#314]
Visual studio crashes when refactoring of CC0016 runs on the following code

```CSharp
void Foo(Func<int, bool> isZero)
{
    if (1 == 1 && isZero(2))
    {
        // Some Stuff
    }
}
```

**Comment by giggio** [comment]
I am not getting CC0016 raised on this method:

![Where is CC0016?](https://cloud.githubusercontent.com/assets/334958/7220822/fb3dc006-e6ab-11e4-9e8f-3c3376c3e40e.png)

It is exiting on line 47:

https://github.com/code-cracker/code-cracker/blob/master/src/CSharp/CodeCracker/Design/CopyEventToVariableBeforeFireAnalyzer.cs#L47

The condition it is hitting to exit is `symbol is IParameterSymbol`. CC0016 will not be raised for parameters.

Are you using the latest VS (CTP 6)?

I am closing this for now, please let me know how can I reproduce it so we can fix it.
