### ISSUE TITLE
Bug: CC0006 ForInArrayAnalyzer

### ISSUE THREAD

**Issue by Kavignon** [code-cracker/code-cracker#317]
While trying out the library as a nuget package, I wanted to try the CC0006 analyzer. It turns out that 
if a method receives the IEnumerable concrete class as an argument, it won't pick up the analyzation that it needs to do. 
I tried the one on the website,and it worked. Basically, what I understand, as a bug (or maybe my machine is failing), I think that it only works when its used locally but not when it's passed as an argument.

Plus, there's the fact that I didn't use that method and the analyzer CC0068 did not tell me that my method was not used. Is it completed or that's a bug too ?

public void Method(int[] ints,int x)
		{
			var obj = new object();
			var count = 0;
			for (int i = 0; i < ints.Length; i++)
			{
				count += ints[i];
			}
		}

**Comment by giggio** [comment]
@Kavignon CC0006 looks for a very specific pattern. It looks for a `for` that has a specific condition (just as you used in your example), and a body which contains an assignment from the array/list into a variable, and if the indexer is not used again later for something else.
Even though your pattern makes sense, we did not plan for it. That does not mean we cannot expand it to also work with it.
So, this is not a bug, really, we were not trying to work with this specific when we first did it.
Looking at the code, I can tell you that it would be simple to fix the analyzer, but the code fix would take more effort. They both look for that specific pattern. I am not sure if this should be a whole new analyzer/code fix/diagnostic id, or if we can expand CC0006 to work with this pattern.

**Comment by giggio** [comment]
So, I have examined the code, and have opened issue #318 with some examples on how to deal with this item. Let's keep the discussion there. @Kavignon please see if you agree with what I have put there. And tks for the idea of expanding this analyzer and code fix.

Regarding CC0068, please open another issue with an example we can verify.
