### ISSUE TITLE
Expand CC0006 (change for into a foreach)

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#318]
Currently CC0006 is only raised on a specific pattern, with a for, and an assignment happening with the indexer like this:

````csharp
var array = new [] {1};
for (var i = 0; i < array.Length; i++)
{
    var item = array[i];
}
````

And it's code fix changes it to a foreach, like this:

````csharp
var array = new [] {1};
foreach (var item in array)
{
}
````

It is not currently able to deal with more array accessors, like this:

````csharp
var array = new [] {1};
var count = 0;
for (var i = 0; i < array.Length; i++)
{
    var item = array[i];
    count += array[i];
    Console.WriteLine(array[i]);
}
````

This could be changed to:

````csharp
var array = new [] {1};
var count = 0;
foreach (var item in array)
{
    count += item;
    Console.WriteLine(item);
}
````

This issue will expand both the analyzer and the code fix.

VB does not have this analyzer yet, so this would only be C#.

@albertomonteiro is working on it.

**Comment by carloscds** [comment]
@giggio It´s very interesting. I tested two samples now and second one do not fire analyzer.
