### ISSUE TITLE
Make accessibility consistent (code fix for CS0051)

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#321]
If a class references another class that is less accessible you will get `CS0051`. For example

````csharp
public class Dependent
{
    public Dependent(DependendedUpon d)
    {
    }
}
internal class DependendedUpon
{
}
````

This will raise `CS0051` on the first caracter of the constructor identifier (the first letter `D`).

The code fix should simply change the accessibility of the less accessible class. It would change the above code to (showing only the changed code, the first class stays the same, note the `public` modifier):

````csharp
public class DependendedUpon
{
}
````

There is no need for diagnostic id (we are using the `CS` one, category or visibility, as this is only a code fix provider.

**Comment by carloscds** [comment]
@giggio it´s a very common error. Will be a very useful fix.

**Comment by giggio** [comment]
@carloscds Ok, I am setting it as `Ready`, then.

**Comment by ElemarJR** [comment]
I missed the idea here. Please, man explain it a little bit more.

**Comment by giggio** [comment]
@ElemarJR Try the first code and you will see `CS0051` raised because the `DependentUpon` class is less accessible than the `Dependent` class, that references it. A `public` class cannot reference in a public way an `internal` class, for example, in a constructor argument.

**Comment by baks** [comment]
@giggio, can I work on this one?

**Comment by giggio** [comment]
Sure, go ahead.

**Comment by baks** [comment]
@giggio maybe we should open issues for other inconsistent accessibility related errors? Or at least code fix for method return type?

```csharp
    public class Dependent
    {
        public DependedUpon Method()
        {
            return null;
        }
    }

    class DependedUpon { }
```

**Comment by giggio** [comment]
@baks I thought this kind of problem would also be raised with `CS0051`, but I tried your example and it raises `CS0050`. As the code fix for both `CS0050` and `CS0051` is the same, which is to open up the dependent class, we can fix both of them in this issue.
Is there any other we should consider? I found `CS0052`, that is also the same problem. See:

* [`CS0050`](https://msdn.microsoft.com/en-us/library/be25s2h2.aspx)
* [`CS0051`](https://msdn.microsoft.com/en-us/library/4sscdk02.aspx)
* [`CS0052`](https://msdn.microsoft.com/en-us/library/997yz02a.aspx)

(There is no `CS0049` or `CS0053`, so maybe this is it)

**Comment by baks** [comment]
Yes, there are other compiler errors connected with incosistent accessibility :
* [CS0053] (https://msdn.microsoft.com/en-us/library/532wtsbc%28v=vs.90%29.aspx)
* [CS0054] (https://msdn.microsoft.com/en-us/library/0efy9xb8%28v=vs.90%29.aspx)
* [CS0055] (https://msdn.microsoft.com/en-us/library/6b0x5w9f%28v=vs.90%29.aspx)
* [CS0056] (https://msdn.microsoft.com/en-us/library/7zdw9dt0%28v=vs.90%29.aspx)
* [CS0057] (https://msdn.microsoft.com/en-us/library/1he6k2zs%28v=vs.90%29.aspx)
* [CS0058] (https://msdn.microsoft.com/en-us/library/9c065z8s%28v=vs.90%29.aspx)
* [CS0059] (https://msdn.microsoft.com/en-us/library/20f51zz7%28v=vs.90%29.aspx)
* [CS0060] (https://msdn.microsoft.com/en-us/library/5732hs83%28v=vs.90%29.aspx)
* [CS0061] (https://msdn.microsoft.com/en-us/library/7f82xxf1%28v=vs.90%29.aspx)

**Comment by giggio** [comment]
Weird thing, two sites with different info, both on MSDN.
Ok, then, from `CS0050` to `CS0061`, we fix them all. :)
Agreed?

**Comment by baks** [comment]
I agree with that we should create code-fix for all :+1: 
I just think it will be better if we can group and split it into few issues. Thanks to that it will be much easier to review code and to do it. We can use the same code fix but for every error there will be different code to find type that caused the error.

I propose to make this issue code-fix for CS0050, CS0051.
And create new issue for :
* CS0052 and CS0053
* CS0055 and CS0054
* CS0057 and CS0056
* CS0059 and CS0058
* CS0060 and CS0061

@giggio, what do you think?

**Comment by giggio** [comment]
@baks 
I just took a look at each of them. I don't think we should group them randomly. If we subscribe to `CS0050`, we will be expecting some type of expression with a Type on a return statement. If we subscribe to `CS0051` we will be expecting a parameter. This can be hard or easy to fix, depends on exactly where Microsoft is raising the diagnostic.
On `CS0050` they do it on the method identifier, so you would have to navigate to the parent, find the method declaration, and then find they type.
On `CS0051` they also raise it on the method identifier, but you would have to navigate to the parameters, and it does not explicitly tell you which of the parameter is the problem.

Either way, at the end, we have a Type Symbol. And a simple method that would make the type `public`, `internal`, or `public internal`, fixing all the diagnostics. We could do that simply by adding this method to some of the extension helper classes, and creating a `ChangeAccessibility` method.

I think it makes sense to have one code fix for each of these diagnostics and not group anything. We can create an umbrella issue to group all the issues, and we go on solving each. We can leave this issue as the first, so you can work on it, and decide the best approach, after it is done we create the others.

What do you think?

**Comment by baks** [comment]
@giggio Sounds good for me :+1: 
I first create code fix for CS0051 and I will try to prepare code for other errors. We'll se how it goes.

We also can fix CS0051 (and other errors) if we change method accessibility (or other code construct) to accessibility same as accessibility of parameter type that generated error.
So, this is also proper code fix for CS0051:
```csharp
    public class Dependent
    {
        Dependent(DependendedUpon d)
        {
        }
    }
    class DependendedUpon
    {
    }
```

**Comment by giggio** [comment]
Ok, as soon as you have the first one open a PR so we discuss it.
The code fix would make the `DependedUpon` class public, as is on this issue's description.

**Comment by giggio** [comment]
@baks Ok, we can now open the other issues as the first PR (#374) is in.
