### ISSUE TITLE
Bug in CC0008 analyser for variable access.

### ISSUE THREAD

**Issue by thorgeirk11** [code-cracker/code-cracker#324]
The CC0008 analyser does not check if the variable is used in the initialiser code.

```CSharp
class Point
{
    public Point(int x) { X = x; }

    public int X { get; set; }
    public int Y { get; set; }
}

void Foo()
{
    var myPoint = new Point(5);
    myPoint.Y = 5 + myPoint.X;
}
```

The refactored code has a compile error since the initializer cannot access the unassigned variable.

![image](https://cloud.githubusercontent.com/assets/2693474/7296313/d5e05a9e-e9ad-11e4-990e-0b91aad7706c.png)

**Comment by giggio** [comment]
Bug confirmed.
