### ISSUE TITLE
CC0056 Incorrectly classifying format strings.

### ISSUE THREAD

**Issue by thorgeirk11** [code-cracker/code-cracker#330]
The CC0056 is incorrectly classifying format strings. 

![image](https://cloud.githubusercontent.com/assets/2693474/7454603/df22b402-f264-11e4-8d59-35f0f183dfae.png)

```CSharp
string.Format(@"{0}", 1);
string.Format(@"{0}{0}", 1);
```

I am not sure if it should cover the following:

```CSharp
string.Format(@"{1}", 1); // This can be identified as a flawed string but isn't.
```

I am using 1.0.0.5-alpha of code cracker and Visual Studio 2015 RC

**Comment by carloscds** [comment]
@thorgeirk11 Error message seems correct. Number os arguments are incorrect. About second comment maybe we can improve analyzer to look this. What do you thing about ?

**Comment by sharwell** [comment]
The message does not make sense as written. Both instances of `{0}` in the format string refer to the first argument, and no other argument is referenced.

**Comment by carloscds** [comment]
@sharwell Analyzer is looking for number of arguments and not for your content. About this, message is correct. Maybe an improvement can be look for this aspect ? Do you like to implement this ?

**Comment by thorgeirk11** [comment]
@carloscds, this is clearly an unexpected error since the code is perfectly valid.

**Comment by carloscds** [comment]
@thorgeirk11 Yes, I agree that it's an error. I will create a bug.

**Comment by sharwell** [comment]
@carloscds I'm confused. Why did you make a new issue which is the same as this issue?

**Comment by carloscds** [comment]
@sharwell Yes, now it's a bug issue.

**Comment by giggio** [comment]
The PR was merged. I will open an issue for your second scenario. I am not sure we should expand the existing analyzer or create a new one. Let's discuss on the new issue.

**Comment by giggio** [comment]
Created issue #335 to discuss the 2nd item.
