### ISSUE TITLE
Incorrect string.Format usage

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#335]
This can be identified as a flawed string but isn't:

````CSharp
string.Format(@"{1}", 1);
````

There is no code fix.

We could expand on `CC0056` or not. Let's discuss it. If we decide to create a new analyzer, it should follow `CC0056` details (Error, Usage).

Here is the current analyzer for `CC0056`: https://github.com/code-cracker/code-cracker/blob/master/src/CSharp/CodeCracker/Usage/StringFormatArgsAnalyzer.cs

@thorgeirk11 is working on it.

**Comment by giggio** [comment]
Looking at the current implementation it shouldn't be a problem to expand `StringFormatArgsAnalyzer` to make it solve this problem. @thorgeirk11 you brought it up on #330, and fixed it later, what do you think? @code-cracker/owners what do you think?

**Comment by carloscds** [comment]
@giggio Why you close another bug about this ? Solve only this problem not solve it.

**Comment by carloscds** [comment]
I think that it´s not a problem for analyzer, because it´s a basic error. But if someone will want to fix it, go ahead!

**Comment by thorgeirk11** [comment]
I would like to try to extend CC0056 to also include this error, if that is ok ? 
What would the error message for this scenario be and would it be the same diagnostic ID ?
