### ISSUE TITLE
Bug on CC0082 when running on pt-br culture

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#339]
It was supposed to had been closed at this line:
https://github.com/code-cracker/code-cracker/blob/master/src/CSharp/CodeCracker/Refactoring/ComputeExpressionCodeFixProvider.cs#L51

![cc0082bug](https://cloud.githubusercontent.com/assets/334958/7635815/b7bf12d4-fa39-11e4-8415-48fc0162c19c.png)

Related to #312 and #313.

**Comment by giggio** [comment]
@carloscds I can't repro the bug on my machine and also the tests pass on the CI build server. This specific test is a `Theory`, it has several test cases. Which one is failing?
@ElemarJR Does it fail on your machine as well?

**Comment by carloscds** [comment]
@giggio I tried now in another machine and all tests passed.

**Comment by giggio** [comment]
@carloscds Ok, can you try to find out how we can repro? Is the other machine still producing the bug?

**Comment by carloscds** [comment]
@giggio I will try to repro again in my desktop, that was where test failed.

**Comment by giggio** [comment]
@carloscds Were you able to repro? If not, can we close the issue?

**Comment by giggio** [comment]
I am closing, if we are able to find a way to repro or maybe write a test we will reopen.
