### ISSUE TITLE
Port changes from CC0021 (nameof) to VB

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#341]
Recent changes on #263 and #198 demand an update to the VB analyzer and code fix which we have not yet done.

@jwooley is working on it.

**Comment by giggio** [comment]
@baks you worked on the C# side, would you like to take this one?

**Comment by jwooley** [comment]
I can take it if @baks doesn't.

**Comment by baks** [comment]
I didn't do any work with VB side of CC0021 yet.
So, if @jwooley want to take this I have nothing against :+1:

**Comment by giggio** [comment]
@jwooley go ahead then, it is yours!

**Comment by giggio** [comment]
Closed on #363.
