### ISSUE TITLE
Trailing whitespace (CC0065) fix all not working

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#344]
Right now it is only suggesting to fix one of the reported diagnostics.

**Comment by bigodera** [comment]
Hi @giggio, I wanna start contributing and this seems to be a nice issue to start. 
Before trying to figure out how to fix this bug, I'm trying to reproduce it. However, I'm not sure if Code Cracker is working on my VS. I've installed it via nuget in a separate solution and I wrote some code that should generate warnings about trailing whitespace and got nothing.

Installing CC via nuget is enough or I should do something else?

**Comment by giggio** [comment]
@bigodera We have not yet published a version to work with VS 2015 RC to Nuget, only to Myget. This would explain why it might not be working.
To try it you should actually fork, clone and run it, with VS 2015 RC. It should work. VS 2015 CTPs are not supported for dev anymore.

**Comment by giggio** [comment]
@bigodera If you get it working just let us know, and you may start to working on this issue. We have a few other examples on how to build a fix all provider on the project.

**Comment by bigodera** [comment]
@giggio I did what you told me to...forked and tried to run it. But I can't run it since it's a class library project. There is a Vsix type project in the solution that is not being loaded cause VS says it's incompatible. Maybe this is the one I should be running?
Sorry, I'm a little confused. If there's any other place we could chat a little about this, it'd be nice.

**Comment by jwooley** [comment]
For the VSIX project, make sure you've installed the VS SDK for 2015 RC under the Additional tools option at https://www.visualstudio.com/en-us/downloads/visual-studio-2015-downloads-vs.aspx. For most development, you shouldn't be F5 debugging, but rather writing tests and running/debugging the unit test project. It's much faster to run and debug the tests than to launch the experimental hive VS through the vsix.

**Comment by giggio** [comment]
@bigodera What @jwooley said is correct. I am on jabbr all day: https://jabbr.net/#/rooms/code-cracker

**Comment by bigodera** [comment]
Thank you @jwooley! I'll do that.

**Comment by bigodera** [comment]
@giggio I got it working.
I ran all the tests of the RemoveTrailingWhitespaceTests class and they're all ok. Then I ran the vsix project, tried each one of the examples that are in the tests in real code and the diagnostics were generated to me.
Maybe I didn't understand the issue?

**Comment by giggio** [comment]
You have to run a fix all in the solution. Did you try that?

**Comment by bigodera** [comment]
I hadn't, sorry. 
But I tried now in a project with 2 different classes, each one with at least one occurrence of the examples that are in the RemoveTrailingWhitespaceTests class. It seems to be working ok to me.
Do you have an example cenario where it doesn't work?

**Comment by giggio** [comment]
@bigodera  You are right. The problem was at another place, at the detection of generated code, which was bugged. I fixed it. The problem occurred when you started the fix on an AssemblyInfo.cs file.
You can select a different issue to work.
