### ISSUE TITLE
Use "" instead of String.Empty

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#354]
This is the opposite of #120.

````csharp
var a = string.Empty;
````

Becomes 

````csharp
var a = "";
````

Diagnostic Id: `CC0088`
Severity: Hidden
Category: Style

@kalkie is working on it.

**Comment by kalkie** [comment]
Hi giggio, can I try to solve this one?

**Comment by giggio** [comment]
@kalkie yes, go ahead. I'll also add you to the collaborators team and assign it to you.
