### ISSUE TITLE
Make method static if possible

### ISSUE THREAD

**Issue by baks** [code-cracker/code-cracker#364]
If method in class is not using any instance fields it can be made static.

````csharp
class Test 
{
    public char GetThirdCharacterFromString(string str)
    {
        return str[2];
    }
}
class Referencing
{
    void Foo()
    {
        var t = new Test();
        t.GetThirdCharacterFromString("");
    }
}
````

becomes

````csharp
public class Test 
{
    public static char GetThirdCharacterFromString(string str)
    {
        return str[2];
    }
    void Foo()
    {
        var t = new Test();
        Test.GetThirdCharacterFromString("");
    }
}
````

A non static method can be turned static, but only if it is not accessing `this`.
Also, the code fix would have to find all references and change them to static invocations. If the method is public, on the whole solution, if it is internal, on the project, etc. The current roslyn infrastructure takes care of finding those references for us.

Diagnostic id: `CC0091`
Category: `Design`
Severity: `Info`

**Comment by Kavignon** [comment]
Well in that case, we could even extend this to even a greater step @baks 
If we look at the entire class and we see that all the methods can be converted to static methods, but those static methods all seem to receive the same type of parameter, the class could be converted to an extension class!
What do you think about this ? @giggio

**Comment by giggio** [comment]
@Kavignon I like it but I think it is a different analyzer. To be able to create an extension method we need a non generic static class, that would be the only requirement. The methods don't need to receive the same type of parameters (see `CSharpAnalyzerExtensions` for an example).
I will create another issue and mention you so we can continue the discussion there.
@baks good one, I will fill in the other info and make it `Ready`.

**Comment by giggio** [comment]
@baks I set it to `Info` and `Usage`. I also expanded the test case and added comments, see what you think.

**Comment by baks** [comment]
@giggio , ok for me :+1: 
Just wonder about one thing - if the method will be turned static, should the code-fix also remove object creation, if it's not used after refactoring?

**Comment by giggio** [comment]
@baks to be able to do that we would need to analyze if the variable is not being referenced elsewhere, which we could do. The problem is that the object creation could have side effects. It shouldn't, for good code design, but it could. Variables that are not used will raise another diagnostic, from Roslyn directly.
I am not sure if we should remove the variable, it looks beyond the scope here.

**Comment by giggio** [comment]
I will take this one.

**Comment by giggio** [comment]
I updated the category do `Design`.
