### ISSUE TITLE
Async method can't be used with RegisterXXXXAction.

### ISSUE THREAD

**Issue by heejaechang** [code-cracker/code-cracker#375]
in DisposablesShouldCallSuppressFinalizeAnalyzer.cs 

public override void Initialize(AnalysisContext context) =>
            context.RegisterSymbolAction(AnalyzeAsync, SymbolKind.NamedType);

this is wrong since RegisterSymbolAction is synchronous method, giving "async void" doesn't make it synchronous method meaning, all stage management in engine now can blow up sometime later.

for example, if this method throws, engine no longer can catch it and show "exception diagnostic" in error list, rather it will crash VS.

also, context and everything in it have no guarantee that it would be still valid after "await".

it might have been working if "async/await" decide to inline continuation, otherwise, it will mess up engine (like the one I am seeing now)

it looks like the only reason it is using "async" is to do this
            var syntaxTree = await disposeMethod.DeclaringSyntaxReferences[0]?.GetSyntaxAsync(context.CancellationToken);

but SyntaxReference also provide synchronous version "GetSyntax" rather than GetSyntaxAsync". the analyzer should use GetSyntax.

**Comment by giggio** [comment]
@heejaechang Interesting. I fixed it in 32c9089.
Now, why would `SymbolAnalysisContext` offer a `CancellationToken` if we are not supposed to `await`?

**Comment by heejaechang** [comment]
Cancellation has nothing to do with async-ness.

cancellation is still valid to cancel long running operation.

foreach(.. loop billion times ..)
{ ... . .token.ThrowIfCancelled() }

**Comment by giggio** [comment]
@heejaechang Ok, got it. Tks!
