### ISSUE TITLE
Convert Local Variable to Constant Field

### ISSUE THREAD

**Issue by Kavignon** [code-cracker/code-cracker#378]
Local variables that are declared and initialised with a value without changing should be converted to constant field within a class or a struct.

        private bool SomeMethod(object obj)
        {
           var someVariable = 4;
           return someVariable == 4 && obj != null;
        }

I know this is a bad use case. But I'm just making a statement

**Comment by giggio** [comment]
@Kavignon This is already done. See `CC0030`.

**Comment by Kavignon** [comment]
The worst thing is, before proposing my idea, i went through the ones that were done...
I feel a bit bad haha
