### ISSUE TITLE
Make accessibility consistent (code fix for CS0050 to CS0061)

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#381]
**This issue is an umbrella issue. We will only close it when every sub issue is closed.**

Sub issues:

- [x] [`CS0050`](https://msdn.microsoft.com/en-us/library/be25s2h2.aspx) (#387)
- [x] [`CS0051`](https://msdn.microsoft.com/en-us/library/4sscdk02.aspx) (#321)
- [x] [`CS0052`](https://msdn.microsoft.com/en-us/library/997yz02a.aspx) (#391)
- [x] [`CS0053`](https://msdn.microsoft.com/en-us/library/532wtsbc%28v=vs.90%29.aspx) (#391)
- [x] [`CS0054`](https://msdn.microsoft.com/en-us/library/0efy9xb8%28v=vs.90%29.aspx) (#391)
- [x] [`CS0055`](https://msdn.microsoft.com/en-us/library/6b0x5w9f%28v=vs.90%29.aspx) (#391)
- [x] [`CS0056`](https://msdn.microsoft.com/en-us/library/7zdw9dt0%28v=vs.90%29.aspx) (#532)
- [x] [`CS0057`](https://msdn.microsoft.com/en-us/library/1he6k2zs%28v=vs.90%29.aspx) (#532)
- [x] [`CS0058`](https://msdn.microsoft.com/en-us/library/9c065z8s%28v=vs.90%29.aspx) (#558)
- [x] [`CS0059`](https://msdn.microsoft.com/en-us/library/20f51zz7%28v=vs.90%29.aspx) (#558)
- [x] [`CS0060`](https://msdn.microsoft.com/en-us/library/5732hs83%28v=vs.90%29.aspx)
- [x] [`CS0061`](https://msdn.microsoft.com/en-us/library/7f82xxf1%28v=vs.90%29.aspx)

**Comment by baks** [comment]
So, I can start work on `CS0050`. Should I create new issue for 'CS0050' with details of how code fix provider should work?

**Comment by giggio** [comment]
@baks I don't think we need it. Just go ahead.

**Comment by baks** [comment]
`CS0050` is done, so I start doing `CS0052`

**Comment by giggio** [comment]
Half is done! :)

**Comment by baks** [comment]
@giggio 
Sorry, it takes so long time :cry: , but now I'm able to finish it.

**Comment by giggio** [comment]
Cool!

**Comment by giggio** [comment]
And we are done! Thanks, @baks!!!
