### ISSUE TITLE
Extract Class to a New File

### ISSUE THREAD

**Issue by carloscds** [code-cracker/code-cracker#382]
Extracting a class to an external file, since this is not the only class in the file. The extracted class may not have the same name as the source file, if it occurs, change the file name including a number at the end.

The class must be created in the same folder and namespace.

Category: `Refactoring`
Diagnostic Id: `CC0096`
Severity: `Hidden`

**Comment by sharwell** [comment]
See the following for potential implementation assistance:

* DotNetAnalyzers/StyleCopAnalyzers#954
* DotNetAnalyzers/StyleCopAnalyzers#953

**Comment by carloscds** [comment]
@sharwell Thanks.

**Comment by giggio** [comment]
Closed on #505

**Comment by giggio** [comment]
This is a cool one. And it is done now!
:shipit:
