### ISSUE TITLE
Using the refactoring for CC0008 will result in a warning CC0015

### ISSUE THREAD

**Issue by wertzui** [code-cracker/code-cracker#383]
When using CC0008, the resulting object initializer will contain unnessecary parantheses and CC0015 will be trigered.

It would be better if parantheses where removed if the default constructor is used.

Example:

    var myFoo = new Foo();
    myFoo.bar = "foobar";

This will trigger CC0008.
After using it, the resulting code is

    var myFoo = new Foo()
    {
        bar = "foobar"
    };

this will trigger CC0015
After using it, the resulting code is

    var myFoo = new Foo
    {
        bar = "foobar"
    };

**Comment by thorgeirk11** [comment]
Can I take this on ?

**Comment by giggio** [comment]
Sure!
