### ISSUE TITLE
Warn when a constant with same value already exists.

### ISSUE THREAD

**Issue by marcelodeaguiar** [code-cracker/code-cracker#386]
Show a warning messaging when creating a constant with a value that already exists (and is visible) to the current project.
```
public const string TEMP_PATH = "/path/to/temp";
```
warning: There is a constant with the same value visible to this project in class "NameOfOtherClass"

It can even suggest a refactoring to use the other constant instead o a simple warning.

**Comment by Kavignon** [comment]
Well, if I have many const values within the project, but each of them have a different meaning, this would cause a big issue..Plus, this will need a big computation from the project as it's not looking in a single source file but n the entire project. We need analyzers to be as quick as possible and it's my opinion that this would not be a good idea for this project.

**Comment by marcelodeaguiar** [comment]
@Kavignon Makes sense.

**Comment by Kavignon** [comment]
@code-cracker/owners i vote to close this issue

**Comment by giggio** [comment]
It is true that we would need to wait for the compilation to end, and that happens only every now and then. And then, if the user changed the const, we would need again to wait for the compilation to finish to be able to remove it.
I am fine with closing it. It is not that I don't see value in it, but I think it is expensive for the benefit it is providing.
@marcelodeaguiar Tks for the suggestion, keep them coming.
@code-cracker/owners If you see something I am not seeing bring it up.
