### ISSUE TITLE
Bug on ObjectInitializerCodeFixProvider when constructor already has initialization

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#396]
This:

````
var p = new Person
{
    Name = "Giovanni",
};
p.Age = 25;
````

Will raise `CC0008`, which is fine. But the code fix is removing the existing initializer, not merging it. This is how it gets now:

````csharp
var p = new Person
{
    Age = 25
};
````

This is how it should become:

````csharp
var p = new Person
{
    Name = "Giovanni",
    Age = 25
};
````

Also, we have to be careful with repeating assignments. So this (notice that `Name` is showing twice:

````csharp
var p = new Person
{
    Name = "Giovanni",
};
p.Name = "Bassi";
````

Should become:

````csharp
var p = new Person
{
    Name = "Bassi",
};
````

**Comment by wertzui** [comment]
The Problem with the double assignemt of the Name property is, that we do not know if the Property has any side effects.

**Comment by giggio** [comment]
@wertzui You are right, but side effects on property assignment is an anti-pattern. We could say that assign twice to trigger a side effect is an even worse anti-pattern.
I feel fine to ignore this until someone brings a compelling argument to not do it.
If we decide to keep it we could then simply not bring this assignment into the constructor initializer.
We could even say, in this side effect line of thought, that we cannot bring an assignment up to the constructor initializer, because the order in which they happen might matter. Again, I'd rather ignore that this could happen.
