### ISSUE TITLE
Null Reference Exception on CodeCracker.CSharp.Usage.VirtualMethodOnConstructorAnalyzer

### ISSUE THREAD

**Issue by monoman** [code-cracker/code-cracker#398]
Severity|Code|Description
----------|-------|--------------
Message|AD0001|The User Diagnostic Analyzer 'CodeCracker.CSharp.Usage.VirtualMethodOnConstructorAnalyzer' threw an exception with message 'Object reference not set to an instance of an object.'.

Analyzing my library at https://github.com/managed-commons/managed-commons-core this appears on VS2015RC with the CodeCracker vsix installed.

**Comment by monoman** [comment]
Possibly in this unguarded references
``` csharp
           var methodInvocations = ctor.Body.DescendantNodes().OfType<InvocationExpressionSyntax>();
```
 or
``` csharp
   if (methodDeclaration.Symbol.IsVirtual) {
```

**Comment by giggio** [comment]
@monoman It is happening on:

````csharp
if (methodDeclaration.Symbol.IsVirtual) {
````

On the LicenseAttribute.cs file, on the `nameof`, which is understood as an invocation, but there are no symbols associated with it.
It is a quick fix, I will do it.
