### ISSUE TITLE
Ignore Disposables created on return statements

### ISSUE THREAD

**Issue by ericcastoldi** [code-cracker/code-cracker#399]
When an ```IDisposable``` object is created on the return statement of a method, the ```DisposableVariableNotDisposedAnalyzer``` creates a ```Diagnostic``` saying that the said object should be disposed. Like in the snippet below:

```csharp
public class DisposableClass : System.IDisposable  { }
public class ActualClass
{
    public DisposableClass Method()
    {
        return new DisposableClass(); 
     }
}
```

Trying to Fix Occurences of said Diagnostic causes VS to crash when method ```CreateUsing``` (class ```DisposableVariableNotDisposedCodeFixProvider```) is called. The crash is caused by an ```InvalidCastException``` thrown by ```CreateUsing``` here:

```csharp
newRoot = CreateRootWithUsing(root, (ExpressionStatementSyntax)objectCreation.Parent, u => u.WithExpression(objectCreation));
```
Since the disposable object is being created and returned, the ```Parent``` property of ```objectCreation``` in the code above is actually of type ```ReturnStatementSyntax```, causing the ```InvalidCastException``` to be thrown.

[I have already fixed this in my fork](https://github.com/ericcastoldi/code-cracker/commit/214cadb04659e23bd5f74e863b3d9220ee2a21d2), so the ```DisposableVariableNotDisposedAnalyzer``` ignores nodes
whose Parents are of type ```ReturnStatementSyntax```. But i'm not sure if i should submit the pull request yet because i guess people would have to discuss about it first, and maybe someone has a better approach.

I'll wait for your comments before submitting the pull request.

**Comment by giggio** [comment]
@ericcastoldi your code is fine. Go ahead and send the PR. I will add you to the colaborators team so we can assign this issue to you.
