### ISSUE TITLE
Unit test methods raises CC0091 - "Make <xxxx> method static"

### ISSUE THREAD

**Issue by OsirisTerje** [code-cracker/code-cracker#404]
Unit test methods are written as instance methods, and code cracker raises CC0091 on them. This warning is erroneous.  
The analyzer should suppress this for unit test methods.

If it uses the test attributes it should cover both MSTest, NUnit, XUnit and Intellitest methods. 

Attributes:
MSTest: `TestMethod`
NUnit: `Test`, `TestCase`, `TestCaseSource`
XUnit: `Fact`, `Theory`

In addition the setup and teardown attributes (XUnit uses ctor's so no issue there)
MSTest: `ClassInitialize`, `ClassCleanup`, `TestInitialize`, `TestCleanup`
NUnit: (V2): `TestFixtureSetup`, `TestFixtureTeardown`, `SetUp`, `TearDown` (V3), `OneTimeSetUp`, `OneTimeTearDown`

Also, any method that has the word `Test` in it is to be ignored, as NUnit uses that, but only if the containing class has a `TestFixture` attribute, or if there are sibling methods with a `Test` attribute. More info on this behavior [here](http://www.nunit.org/index.php?p=test&r=2.6.4) and [here](http://www.nunit.org/index.php?p=testFixture&r=2.6.4). Examples: `TestThis`, `DoATestSomewhere`.

**Comment by giggio** [comment]
Agreed, but we have to be more specific. Can you provide a more detailed description on how we detect such methods? For example, in Nunit, allow tests to start with the word `test`, and don't need an attribute (http://www.nunit.org/index.php?p=test&r=2.6.4). Which cases do we want to except?

**Comment by OsirisTerje** [comment]
There are many different ways of naming test methods, so requiring a certain naming convention can be hard.  
But, all test methods do have attributes that are marking them:
MSTest:  TestMethod
NUnit:  Test,  TestCase,  TestCaseSource
XUnit:  Fact
In addition the setup and teardown attributes (XUnit uses ctor's so no issue there)
MSTest:  ClassInitialize, ClassCleanup TestInitialize, TestCleanup
NUnit:  (V2): TestFixtureSetup, TestFixtureTeardown, SetUp, TearDown  (V3)  OneTimeSetUp, OneTimeTearDown

**Comment by giggio** [comment]
Will we support mbUnit or none uses that anymore?
Also remember to do not mark any method that starts with "Test" because of NUnit. And xUnit uses `Theory` as well. In NUnit case, `Test` would be enough, right?

**Comment by OsirisTerje** [comment]
I do believe mbUnit is dead.  
You need to check all the attributes I mentioned above.  
You're right about Theory, NUnit also has this one.
Also, IntelliTest has to be supported, it has PexMethod as an attribute.

**Comment by AlbertoMonteiro** [comment]
When checking if methods starts with **Test**, it should also check if project reference nunit, same for xUnit

**Comment by OsirisTerje** [comment]
Agree, Checking the reference is a good idea. 

However, checking for method names is not a viable solution, it must check the attributes.

**Comment by giggio** [comment]
To be able to check the references we will need a compilation action on the analyzer. I am not sure we need that. Can't we simply ignore methods that start with `Test`?

**Comment by AlbertoMonteiro** [comment]
For me, ok

**Comment by OsirisTerje** [comment]
I don't think ignoring methods that START with Test is enough.  Test methods often also ends with Test or Test.  
Others prefer test method names like CheckThatXYZIsValid().  
It don't need to check the references, it is enough to check the attributes.
Look the image below:
The method in focus is the AddTest()  (1)
The method can be seen in (2), and it has an attribute list with one attribute (3), and the value of that attribute is Test (4).

![image](https://cloud.githubusercontent.com/assets/203432/8735825/0ecc3a0a-2c14-11e5-823c-e20601605f22.png)

This is explicit, and all you need to is to cover the possible attributes that can be used.

**Comment by giggio** [comment]
@OsirisTerje Ok, I have updated the description with what we have discussed and I am marking it as up for grabs. Anyone that starts to work on it, look closely into this thread, as it may evolve.

**Comment by thomaslevesque** [comment]
> it is enough to check the attributes.

Actually, it's not. Some unit test frameworks don't use attributes at all, only conventions (e.g. [Fixie](https://github.com/Fixie/Fixie)).

**Comment by giggio** [comment]
@thomaslevesque I don't think we need to work with every possible test framework. Working with the main ones is enough. People using other frameworks can disable the analyzer for the test project or supress it on test classes. It should be enough.

**Comment by giggio** [comment]
Closed on #444.

**Comment by giggio** [comment]
If anyone wants this before we release, it is on `1.0.0-rc1-0746` on myget.
