### ISSUE TITLE
The code fix for ordering members fails

### ISSUE THREAD

**Issue by OsirisTerje** [code-cracker/code-cracker#405]
The Ordering members fix, CC0035, fails when just touching a classname (1), in VS 2015.  I assume that triggers it, it also seems a lot of the others triggers on code fixes, but this is a hidden one, so it is rather annoying.
![image](https://cloud.githubusercontent.com/assets/203432/8639420/fbe2d27e-28d9-11e5-99ef-4c61ff3bb7e7.png)

**Comment by giggio** [comment]
@OsirisTerje Can you paste an example class file we can test?
I did not understand your second sentence, can you elaborate?
Also, how did you get this nice yellow warning on the top? Right now, when an analyzer crashes all I get is a warning on Visual Studio Error list and I can't reenable it.

**Comment by OsirisTerje** [comment]
2nd sentence:  It seems that the code fix  on all the rules triggers the yellow message bar.   
When the rule is hidden it is even more annoying, but it seems something is broken.  

See the image below, I have a static code "violation", and press the yellow lamp (1) to fix it.
![image](https://cloud.githubusercontent.com/assets/203432/8735614/851080f6-2c12-11e5-9cd2-04b6bbb164e9.png)
Then the yellow bar appears at the top, also notice the drops below the yellow lamp, which is empty, it looks like something should have been there too.  And in this case it seems that there are two code fix errors
![image](https://cloud.githubusercontent.com/assets/203432/8735644/b4968ad2-2c12-11e5-8faa-6e7d5282c4ee.png)

**Comment by giggio** [comment]
@OsirisTerje I just tried it and I can't get error to show:

![add](https://cloud.githubusercontent.com/assets/334958/9431475/895ca772-49e8-11e5-9e38-28155294df00.png)

We have updated CodeCracker and stabilized a lot of the analyzers. Can you please try it with the current release, which is `rc2`, using VS 2015 RTM?

I will close the issue, if you still have it let us know, we will work to fix it.
