### ISSUE TITLE
I was having VS2015 RC crash when loading RoslynLight.sln with Code-Cracker vsix enabled

### ISSUE THREAD

**Issue by monoman** [code-cracker/code-cracker#406]
Initially I posted the issue there: https://github.com/dotnet/roslyn/issues/3866
But disabling Code-Cracker makes the exception go away, although it still freezed once.

As the exception is:
``` csharp
An unhandled exception of type 'System.InvalidCastException' occurred in mscorlib.dll

Additional information: Unable to cast object of type
 'Microsoft.CodeAnalysis.CSharp.Syntax.MemberAccessExpressionSyntax' to type
 'Microsoft.CodeAnalysis.CSharp.Syntax.IdentifierNameSyntax'.
```
it may be related to Code-Cracker.

**Comment by giggio** [comment]
Yes, don't try that. They are ahead of us, and our types do not match theirs. I hope that once they reach 1.0 that the signatures and references will match and we won't break them.
