### ISSUE TITLE
CC0021: nameof(x) suggested before x is declared

### ISSUE THREAD

**Issue by der-andy** [code-cracker/code-cracker#408]
In this code:

```
var str = "x";
var x = 1;
```

code-cracker suggests replacing `"x"` with `nameof(x)` which results in an error since `x` would be used before it is declared.

**Comment by carloscds** [comment]
That's make sense. Maybe check if declaration of type is before string. What do you think ?

**Comment by der-andy** [comment]
:+1: Sounds good. I don't know how these analyzers work in detail. But I assume that you do check what variables are declared, otherwise you wouldn't be able to suggest `nameof`. So I think you should remember the line number of the declaration and only suggest `nameof` in lines below the declaration.

**Comment by AlbertoMonteiro** [comment]
Can I fix this?

**Comment by jwooley** [comment]
Line numbers will only work for method local fields. Class scoped fields are available regardless of declaration location. If you fix this, please try to update the VB version as well or let me know the C# fix and I can apply to VB if necessary.

**Comment by giggio** [comment]
Bug confirmed.
@AlbertoMonteiro You are already working on another issue. After you are done with that one you can start this one if no one picked it up. :)

**Comment by jwooley** [comment]
Does this fix need to be added to the VB implementation as well?

**Comment by giggio** [comment]
@jwooley Probably. Good call. I will open an issue.

**Comment by giggio** [comment]
@jwooley Issue #420. If you want it let us know.

**Comment by jwooley** [comment]
I’ll take it since I did the last port.
