### ISSUE TITLE
Bug on compiling code-cracker commit dc6c8d5daa9ede05c1f9e59db2889eba5d4a9fba

### ISSUE THREAD

**Issue by dgmachado** [code-cracker/code-cracker#415]
![code-cracker-1](https://cloud.githubusercontent.com/assets/5738416/8840546/1f1e46ba-30b9-11e5-9652-8ad37f0721bc.png)

![code-cracker](https://cloud.githubusercontent.com/assets/5738416/8840461/ddb52870-30b7-11e5-888f-093d7cc2d449.png)

**Comment by giggio** [comment]
Yes, HEAD is at RTM now, you are using VS 2015. Update and it will compile. :)

**Comment by dgmachado** [comment]
Thanks it worked!!!
