### ISSUE TITLE
Provide an equivalence key on all code fix providers

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#417]
This is raising `RS1010`. We will also need to update the tests.

**Comment by giggio** [comment]
Lots of info on equivalencekey here: https://github.com/dotnet/roslyn/blob/master/docs/analyzers/FixAllProvider.md

**Comment by sharwell** [comment]
> Lots of info on equivalencekey here:

For that you get :star2:

**Comment by sharwell** [comment]
Article suggests using the title for the default equivalence key. I think we're going to use `nameof(CurrentCodeFixClass)` instead since all of our titles come from localizable resources.

**Comment by giggio** [comment]
We are using that as well, but when we have more than one key we are using the title or some other arbitrary value.
