### ISSUE TITLE
CC0021: nameof(x) suggested before x is declared (VB)

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#420]
Same as #408, for VB.

@jwooley is working on it.

**Comment by giggio** [comment]
@jwooley It is your, as you asked for it. I added you to the collaborators team on Github, see if you can accept so I can assign the task to you.

**Comment by jwooley** [comment]
I'm not sure where to see the accept option.

**Comment by jwooley** [comment]
Pull request issued.

**Comment by jwooley** [comment]
Updated pull request against Master for bug fix and fixed syntax error in unit test.

**Comment by giggio** [comment]
Closed on #439.
