### ISSUE TITLE
BUG in CC0061 when the method is a override from a base class

### ISSUE THREAD

**Issue by viniciusmelquiades** [code-cracker/code-cracker#424]
When I was writing a Owin Middleware, using Microsoft.Owin DLL, Code Cracker suggested me to rename the Invoke method, that is defined in the OwinMiddleware class, to InvokeAsync, but if I do so, the compilation obviously fails. I think this will also happen if it were an interface.

The code bellow will reproduce the problem.
```C#
public class MyMiddleware : OwinMiddleware
	{
                public MyMiddleware(OwinMiddleware next)
			: base(next) { }

		public override Task Invoke(IOwinContext context)
		{
			return Next.Invoke(context);
		}
	}
```

**Comment by giggio** [comment]
Bug confirmed. `TaskNameAsyncAnalyzer` should not create a diagnostic for `override` and also `new`.
