### ISSUE TITLE
CC0022 disposable intantiation on constructor call

### ISSUE THREAD

**Issue by paulomorgado** [code-cracker/code-cracker#432]
CC0022 is being reported on code like this:

    public EntitiesController() : this(new EntitiesDataContext())
    {
    }

Should this be detected as not an issue? Or is it better that it is explicit the reason why it's not being disposed?

**Comment by giggio** [comment]
It is being passed in, it shouldn't be reported.

**Comment by paulomorgado** [comment]
:+1:

**Comment by adraut** [comment]
Would this also fix #409?

**Comment by thorgeirk11** [comment]
Can I try to tackle this ?

**Comment by giggio** [comment]
@thorgeirk11 Sure, go ahead.

**Comment by thorgeirk11** [comment]
Just to be sure, CC0022 should not be reported on disposable objects created as argument ? 

```CSharp
                class A
                {
                    void Foo(Disposable disposable)
                    {
                    }
                    
                    void CallFoo()
                    {
                        Foo(new Disposable()); // This should report CC0022
                    }
                }
                class Disposable : System.IDisposable
                {
                    void System.IDisposable.Dispose() { }
                }
```

**Comment by giggio** [comment]
@thorgeirk11 It is complicated...

At the time it made sense, but I can see now that it makes sense to not report it at least on some of those situations.
One could argue that if the object is being created and directly passed into a method, that the method that created it does not want to control it's lifetime.
On the other hand, it might have to.

How about this: we raise the diagnostic on method invocations, but not on constructor invocations, and on the code fix we offer to extract the variable and dispose it after the **statement** where it is being used (not the method invocation, or expression, the statement). How about that?

So, this would raise a diagnostic:

````csharp
void Foo()
{
    string.Format("", new System.IO.MemoryStream());
}
````

The fix would change it to this:
````csharp
void Foo()
{
    using (var memoryStream = new System.IO.MemoryStream())
    {
        string.Format("", memoryStream);
    }
}
````

This would not raise a diagnostic:
````csharp
new Bar(new System.IO.MemoryStream());
````

This is different:

````csharp
string Foo()
{
    var s = string.Format("", new System.IO.MemoryStream());
    return s;
}
````

As `s` cannot be placed inside a `using` or it will be ou of scope on the return statement, we need a `Dispose` call, like this, on the fix:

````csharp
string Foo()
{
    var memoryStream = new System.IO.MemoryStream();
    var s = string.Format("", memoryStream);
    memoryStream.Dispose();
    return s;
}
````

Or even:

````csharp
string Foo()
{
    using (var memoryStream = new System.IO.MemoryStream())
    {
        var s = string.Format("", memoryStream);
        return s;
    }
}
````

(This last solution would depend on the flow, it might not be possible, there is already logic on the code fix to take care of that)

@paulomorgado How do you feel about this solution?

**Comment by giggio** [comment]
@adraut Yes, I closed #409.

**Comment by thorgeirk11** [comment]
Alright think I have done the all of the above however what is the expected behavoiur on the following ?

```CSharp 
string Foo()
{
    System.IO.MemoryStream m;
    string.Format(string.Empty, m = new System.IO.MemoryStream());
}
```

**Comment by paulomorgado** [comment]
@thorgeirk11, that one should be disposed.

But, unless you can observe the whole lifetime of the object, you can't really know how it's being used.
