### ISSUE TITLE
CC0057 unused parameter should offer a suppress option

### ISSUE THREAD

**Issue by paulomorgado** [code-cracker/code-cracker#434]
Some APIs require some parameters. Instead of just removing the  parameter, there should be an option to suppress the warning.

**Comment by giggio** [comment]
@paulomorgado Suppressing analyzers is available by default on Visual Studio for all diagnostics. What else do you have in mind?

**Comment by giggio** [comment]
@paulomorgado I am closing the issue, if you want to discuss it further let us know.
