### ISSUE TITLE
Doc comments for parameters in wrong order (XmlDocumentationCreateMissingParametersCodeFixProvider)

### ISSUE THREAD

**Issue by thomaslevesque** [code-cracker/code-cracker#437]
I noticed this one when I ran the tests with ReSharper's unit test runner. 4 tests are failing, even though they work in the VS test runner:
```
FixCreateManyParameterDoc
FixCreateManyParameterDocWhenHaveFullDocSyntax
FixCreateManyParameterDocWhenHaveOnlyReturns
FixCreateManyParameterDocWhenHaveOnlySummary
```
For the first one, for instance, the result is this:
```
        /// <param name="workspace">todo: describe workspace parameter on CreateProject</param>
        /// <param name="language">todo: describe language parameter on CreateProject</param>
        /// <param name="sources">todo: describe sources parameter on CreateProject</param>
```

instead of this:
```
        /// <param name="sources">todo: describe sources parameter on CreateProject</param>
        /// <param name="workspace">todo: describe workspace parameter on CreateProject</param>
        /// <param name="language">todo: describe language parameter on CreateProject</param>
```
(note how the `workspace` param ended up at the top of the list, even though it's the last parameter)

I first thought it was a quirk in R#, but it's actually a real bug: the test *can* fail based on seemingly random factors, because of [this](https://github.com/code-cracker/code-cracker/blob/a475139683c4009666f2018aa3738887bc206801/src/CSharp/CodeCracker/Maintainability/XmlDocumentationCodeFixProvider.cs#L38). A hashset does not preserve insertion order, so there's no guarantee that the items will stay in the order in which they were inserted. And indeed, in that case they didn't.

An easy fix is to change `ToImmutableHashSet` to `ToImmutableList`, since the call to `Union` already eliminates duplicates.

**Comment by thomaslevesque** [comment]
Wow, fastest PR ever ;)

**Comment by giggio** [comment]
\o/
