### ISSUE TITLE
CC0091 Methods prefixed with this

### ISSUE THREAD

**Issue by paulomorgado** [code-cracker/code-cracker#450]
This fix can make code uncompilable if the method access is being prefixed with `this`.

That's an hard one, but the fix should fix the code by removing the `this` prefix or changing to info it it's being prefixed.

**Comment by giggio** [comment]
Ok, so you mean that this is happening?

````csharp
void Foo()
{
}
void Bar()
{
  this.Foo();
}
````

Turned into:

````csharp
static void Foo()
{
}
void Bar()
{
  this.Foo();
}
````

I just tried it, and it actually removes the `this` inside `Bar`.

**Comment by paulomorgado** [comment]
It was something like this:

    public async Task<ViewResult> IndexAsync()
    {
        try
        {
            var viewModel = await this.dataContext.ScheduledTasks.All
                .Include(scheduledTask => scheduledTask.TaskStatus)
                .Include(scheduledTask => scheduledTask.TaskPriority)
                .Include(scheduledTask => scheduledTask.TaskType)
                .Include(scheduledTask => scheduledTask.Entity)
                .AsNoTracking()
                .OrderByDescending(st => st.TaskPriorityID)
                .ThenBy(st => st.StartDate)
                .ThenByDescending(st => st.Duration)
                .ThenBy(st => st.Title)
                .ThenBy(st => st.ID)
                .ProjectToListWithActionAsync<ScheduledTaskListItemViewModel>(this.PostMapViewModel);

            return this.View(viewModel);
        }
        catch (Exception ex)
        {
            return this.ErrorView(ex);
        }
    }

    private void PostMapViewModel<TScheduledTaskState>(TScheduledTaskState viewModel)
        where TScheduledTaskState : IScheduledTaskState
    {
        ...
    }

The strange thing is that it's no longer happening.

**Comment by giggio** [comment]
Ok, I will close the issue. If you can find an example we can reproduce, then we reopen it.
