### ISSUE TITLE
CC0091 Know APIs

### ISSUE THREAD

**Issue by paulomorgado** [code-cracker/code-cracker#451]
Methods like `Application_Start` on classes derived from `System.Web.HttpApplication` cannot be made static.

There should be a list of wellknown exceptions to this rule.

Global methods from `System.Web` (taken from [MSDN](https://msdn.microsoft.com/en-us/library/ee255122%28v=bts.10%29.aspx)):

* Application_AuthenticateRequest
* Application_BeginRequest
* Application_End
* Application_EndRequest
* Application_Error
* Application_Start
* Session_End
* Session_Start

**Comment by giggio** [comment]
Ok, it makes sense. Let's try to build one. We already know `Application_Start`. All of the System.Web lifecycle should be ignored, right? What else?

**Comment by giggio** [comment]
I added the System.Web ones to the description.

**Comment by giggio** [comment]
I'll take this one.

**Comment by giggio** [comment]
This has been fixed!

**Comment by soerennielsen** [comment]
Hmm.. this issue broke my app today :-(
Running 1.0.0.12, installed 12-11-2015. 
Glad it's fixed in the next build.
