### ISSUE TITLE
CC0029 DisposablesShouldCallSuppressFinalizeAnalyzer throws InvalidCastException

### ISSUE THREAD

**Issue by bmenees** [code-cracker/code-cracker#452]
I'm getting an error that says AD0001, The User Diagnostic Analyzer 'CodeCracker.CSharp.Usage.DisposablesShouldCallSuppressFinalizeAnalyzer' threw an exception of type 'System.InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.ThisExpressionSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.IdentifierNameSyntax'.'.

I can't tell which type it's analyzing when it blows up, but my public Dispose() methods look like this:
```C#
public void Dispose()
{
	this.Dispose(true);
	GC.SuppressFinalize(this);
}
```
I've had to disable rule CC0029 in a ruleset file into order to get rid of this error.

**Comment by adraut** [comment]
This is definitely a bug.  I'm working on it.

**Comment by giggio** [comment]
@bmenees Fixed on build 741, already pushed to Myget.
