### ISSUE TITLE
Erroneous CC0039 message

### ISSUE THREAD

**Issue by mc0re** [code-cracker/code-cracker#461]
In this code:

	Private Sub AdjustSample(readBuffer() As Single, ByRef readIdx As Integer, writeBuffer() As Single, ByRef writeIdx As Integer)
		If mIsMuted Then
			For chIdx = 0 To mDestChannels - 1
				writeBuffer(writeIdx) = 0
				readIdx += 1
				writeIdx += 1
			Next
...

there is an erroneous warning "Don't concatenate 'readIdx' in a loop".

**Comment by giggio** [comment]
I am not being able to repro this. Are you getting this message with the latest version of CodeCracker?
I will close the issue until we find a test case that can be reproduced. Please let us know.

**Comment by adraut** [comment]
@giggio  I had no problem reproducing this with code from master.  Where is our disconnect?

**Comment by giggio** [comment]
@adraut I added the test from @mc0re PR (#461) on 252e6dd, and it passed: https://ci.appveyor.com/project/code-cracker/code-cracker/build/1.0.0.759
This is the current HEAD on master. Does it match for you?
I need a test case that I can repro.

**Comment by adraut** [comment]
@giggio Change the parameter to ref parameter.  That's what causes the problem.  The non-ref parameter becomes a local which the diagnostic checks for already and is why your test passes.  It should be like the test in aef112b38afceb6543c28fd2966930e66808353e

```
public class TypeName
    {
        public void Looper(ref int a = 0)
        {
            while (a < 10)
            {
                a += 1;
            }
        }
    }
```

**Comment by giggio** [comment]
@adraut No, it still does not raise `CC0039`. I added another test on 5f54e6a. You can see the build still passes: https://ci.appveyor.com/project/code-cracker/code-cracker/build/1.0.0.765
Also, you can't have a default on a `ref` parameter, that will raise `CS1741`. But I tried it just like that, and it also did not raise `CC0039`.

**Comment by adraut** [comment]
@giggio Ok, then it is not broken in C#, but it definitely is in VB.  I blindly did the C# after confirming and fixing for VB.

**Comment by mc0re** [comment]
Thanks @giggio - I missed the previous notification. It is about VB code.

**Comment by giggio** [comment]
Bug confirmed on VB.
I will look into the PR again.
