### ISSUE TITLE
Incorrect CC0029 message

### ISSUE THREAD

**Issue by mc0re** [code-cracker/code-cracker#462]
In the following code:

	Public Sub Dispose() Implements IDisposable.Dispose
		' Do not change this code.  Put cleanup code in Dispose(disposing As Boolean) above.
		Dispose(True)
		GC.SuppressFinalize(Me)
	End Sub

there is a message CC0029, saying that GC.SuppressFinalize should be called inside Dispose method. It is!..

**Comment by adraut** [comment]
@mc0re @code-cracker/owners This was already fixed on #452.

**Comment by mc0re** [comment]
Ok, I'll wait for the new release then :-)
