### ISSUE TITLE
DisposableVariableNotDisposedAnalyzer (CC0022) should not raise a diagnostic when returning a type that contains the disposable

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#465]
`CC0022` should not be raised whenever there is a chance that the object lives longer than the method where it was created in.

It should not be raised when assigned to a field/property from another class.

````csharp
public void Foo(){
  var parent = new Parent();
  var disposable = new DisposableObject();
  parent.Child = disposable;
}
````

It should not be raised when passed to any method, in the same class or otherwise:

````csharp
public void Foo(){
  var disposable = new DisposableObject();
  Bar(disposable);
}
````

**Note**: This is coming from a comment on the extension, on [the extensions gallery](https://visualstudiogallery.msdn.microsoft.com/ab588981-91a5-478c-8e65-74d0ff450862/view/Discussions) started by user `fdsprod`.

**Comment by giggio** [comment]
@ElemarJR will improve the description as per our conversation.
When you are ready, set the `Ready` and `up-for-grabs` labels.

**Comment by adraut** [comment]
Is this still needed now that the FXCop analyzers are becoming usable?

**Comment by giggio** [comment]
@adraut what do you mean?

**Comment by adraut** [comment]
@giggio This issues looks similar to one being implement by the roslyn team: https://github.com/dotnet/roslyn-analyzers/issues/476

**Comment by giggio** [comment]
@adraut Ours is ready, I'd say yes. When theirs is ready we can reevaluate.

**Comment by giggio** [comment]
Per our most recent talk, we decided that `CC0022` should never be raised if there is any chance the disposable will leave the context of where it was created. I'll update the description to make it more clear and set it to `Ready` and up for grabs.

**Comment by giggio** [comment]
Actually, I'll fix this.
