### ISSUE TITLE
Bug on DisposableVariableNotDisposedAnalyzer (CC0022) when returning a disposable

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#466]
This should NOT raise a diagnostic:

````csharp
public IDisposable Foo()
{
    var disposable = new MemoryStream();
    return disposable;
}
````

If the method returned `MemoryStream`, the diagnostic is already not being raised. Like so:

````csharp
public MemoryStream Foo()
{
     var disposable = new MemoryStream();
     return disposable;
}
````

**Comment by ImaginaryDevelopment** [comment]
how could I tell when this fix is in a release or available for download in a beta or something?

**Comment by giggio** [comment]
It is already available on myget: https://www.myget.org/F/codecrackerbuild/
I will be releasing a new version later at the end of upcoming week.
