### ISSUE TITLE
CC0014 for VB is reported when disabled

### ISSUE THREAD

**Issue by adraut** [code-cracker/code-cracker#470]
CC0014 is being reported in VB even though it is disabled in the ruleset file.

**Comment by giggio** [comment]
This would be a bug on Roslyn. I will close, I suggest you open it there: https://github.com/dotnet/roslyn/
They will probably ask you for a project to check the problem, try to make a simple one and link to the issue.

**Comment by adraut** [comment]
@giggio I disagree.  It appears that it is because the  diagnostic is nested in the analyzer for 13, 14, and 80.  Other disabled analyzers don't have this problem.

**Comment by giggio** [comment]
What do you mean, nested?

**Comment by adraut** [comment]
@giggio I mean that in the `TernaryOperatorAnalyzer` for VB the `Analyzer` method can report both the `RuleForIfWithReturn` and `RuleForIfWithAssignment`.  It appears that based on this if CC0013 is disabled and CC0014 is enabled that CC0013 could still be reported.  The reverse situation appears to be possible if CC0013 is enabled and CC0014 is disabled that CC0014 could still be reported.

**Comment by adraut** [comment]
@giggio Please disregard.  Due to user error.  One of the projects in my solution was not using the same ruleset file.  It all works correctly.

**Comment by giggio** [comment]
;)
