### ISSUE TITLE
CC0068 is being reported in VB even though it is disabled in the ruleset file

### ISSUE THREAD

**Issue by adraut** [code-cracker/code-cracker#471]
The following code is triggering CC0068 even though it is disabled in the ruleset file.
```
Private Sub Form_Load(ByVal sender as Object, ByVal e as EventArgs) Handles Me.Load
End Sub
```

**Comment by giggio** [comment]
Same thing from #470, this would be a problem on Roslyn itself. CodeCracker does not control this infrastructure.

**Comment by adraut** [comment]
@ giggio CodeCracker does control this to an extent because this diagnostic is nested with 13, 14 and 80, right?

**Comment by adraut** [comment]
@giggio You are correct that this is not a CodeCracker issue.  It's user error.  I did not have one of the projects in the solution using the same ruleset file as the rest.  Whoops.
