### ISSUE TITLE
Add additional checks for determining if generated code

### ISSUE THREAD

**Issue by adraut** [code-cracker/code-cracker#476]
#260 addressed most of the cases, but missed check for attributes ending with the Attribute suffix.
For example, the following should also check for DebuggerNonUserCodeAttribute and GeneratedCodeAttribute:
`[public static bool IsGenerated(this SyntaxNode node) => node.HasAttributeOnAncestorOrSelf("DebuggerNonUserCode", "GeneratedCode");]`

This is required to fix #472

**Comment by giggio** [comment]
Closed on #477.
