### ISSUE TITLE
Useles suggestion of CC0023 rule 

### ISSUE THREAD

**Issue by gigazet** [code-cracker/code-cracker#485]
Useles suggestion of CC0023 rule. It will suggest to use StringBuilder, but d variable is defined inside for block.

static void TestCC0023() {
            for (var i = 0; i < 10; i++) {
                var d = i.ToString();
                d += " row";
                Console.WriteLine(d);
            }
        }

**Comment by giggio** [comment]
Bug confirmed.

**Comment by adraut** [comment]
@code-cracker/collaborators @code-cracker/owners I have made an attempt to fix this, but I am not sure that my approach is correct.  See 680ad9d.

**Comment by thomaslevesque** [comment]
@adraut, your approach seems reasonable and should work. However I think it would be better to check if the loop statement is an ancestor of the declaration, rather than check its position.
