### ISSUE TITLE
Prefer "Count" to "Count()"

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#489]
If it is an `IList` or some other object that has `Count` as a property, don't use the Linq extension method.

So this:

````csharp
var count = myList.Count();
````

Becomes:

````csharp
var count = myList.Count;
````

**Important**:
`Count` and `Count()` have to return the same type.
`Count()` has to be an extension method.

Diagnostic id: `CC0098`
Severity: Warning
Category: Performance

**Comment by thorgeirk11** [comment]
Can I take this one ?

**Comment by giggio** [comment]
Closed on #567.
