### ISSUE TITLE
CC0039 issues for Integer

### ISSUE THREAD

**Issue by paul1956** [code-cracker/code-cracker#499]
Past the following code somewhere, the 3rd line shows error CC0039 which only applies to stings.
```
    Private Sub Test(ByRef Levels() As Integer)
        For j As Integer = 0 To 10
                Levels(UBound(Levels)) += 1
      Next
End Function
```
If TypeOf symbolForAssignment is not one of the few listed the code falls through even though the type is not a string. Inserting
```
            If TypeOf symbolForAssignment IsNot IPropertySymbol OrElse
               TypeOf symbolForAssignment IsNot ILocalSymbol OrElse
               TypeOf symbolForAssignment IsNot IFieldSymbol OrElse
               TypeOf symbolForAssignment IsNot IParameterSymbol Then Exit Sub
```
before the following seem to fix the issue.
```
            If TypeOf symbolForAssignment Is IPropertySymbol AndAlso DirectCast(symbolForAssignment, IPropertySymbol).Type.Name <> "String" Then Exit Sub
            If TypeOf symbolForAssignment Is ILocalSymbol AndAlso DirectCast(symbolForAssignment, ILocalSymbol).Type.Name <> "String" Then Exit Sub
            If TypeOf symbolForAssignment Is IFieldSymbol AndAlso DirectCast(symbolForAssignment, IFieldSymbol).Type.Name <> "String" Then Exit Sub
            If TypeOf symbolForAssignment Is IParameterSymbol AndAlso DirectCast(symbolForAssignment, IParameterSymbol).Type.Name <> "String" Then Exit Sub
```

**Comment by giggio** [comment]
@paul1956  I just tried the code but I couldn't repro. Notice that it works on the second case, but not the first. I included the error list in the screenshot, so you can see that the diagnostic it is not there:

![loop](https://cloud.githubusercontent.com/assets/334958/9833513/bf46c5b6-596f-11e5-8b81-531d5da1c643.png)

Are you the latest version (rc2)? If so, can you paste a code that we can repro?

**Comment by paul1956** [comment]
I can not repo with latest version.

Sent from my iPhone
I apologize for any typos Siri might have made.
(503) 803-6077

**Comment by giggio** [comment]
Ok, I am closing the issue, then.
