### ISSUE TITLE
Convert method to property

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#508]
This:

````csharp
class Foo
{
    int Bar() => 1;
    int Baz()
    {
        return 2;
    }
    void Using()
    {
        var v = Bar() + Baz();
    }
}
````

Becomes:

````csharp
class Foo
{
    int Bar => 1;
    int Baz
    {
        get
        {
            return 2;
        }
    }
    void Using()
    {
        var v = Bar + Baz;
    }
}
````

Can only be offered if method does not return void. Method invocations have to be changed to property references.

Category: Refactoring
Id: CC0103
Severity: Hidden

**Comment by Shiney** [comment]
I'd like to start on this task.

Do we need to stop the code fix from being applicable if the method is overloaded?

**Comment by carloscds** [comment]
@Shiney I think not because you won't change method signature.

**Comment by Shiney** [comment]
But you can't have a method and a property with the same name.

**Comment by carloscds** [comment]
@Shiney Can you put a sample of this ?

**Comment by giggio** [comment]
@Shiney I added you to the collaborators team so we can assign this issue to you. You may start working on it.

Answering your question, I can't think of a way to solve the overloaded method problem. Simply ignore the method if it has an overload.

**Comment by giggio** [comment]
@Shiney Also, remember to fork from the vnext branch, and to request to pull into it. Not from master, which is stabilizing now for 1.0.

**Comment by Shiney** [comment]
class A{
public int Foo(int a){ return a;}

public int Foo{get{return 314;}}

}

Does not compile.


Am I supposed to look up and down the whole inheritance tree to find out if this method was overloaded everywhere? Or would it be simpler and less confusing for the user to just get sometimes non-compilable code out of the code fix?

**Comment by giggio** [comment]
@Shiney A first quick check would be to ask for the type symbol, check all members with the same name, if there is more than one, return. You should use symbolic analysis as you may be dealing with a partial class. Then, if that succeeds, you should ask for all parents and children in the class hierarchy if and see if you find a member with the same name. Please put that as on the common project as an extension, as it might be useful for other analyzers/fixers.

**Comment by Shiney** [comment]
I'm a bit confused about how to replace the old references. Is there a good example of looking at references and changing them?

**Comment by giggio** [comment]
On the code fix you can use the `SymbolFinder` class. There are examples on the CodeCracker source you can use.

**Comment by giggio** [comment]
Already present in latest VS/Roslyn. Feature dropped.
