### ISSUE TITLE
CC0013 Should be Information instead of Warning

### ISSUE THREAD

**Issue by paulomorgado** [code-cracker/code-cracker#520]
Sometimes, it makes sense and the code is more readable as an __if__/__else__ instead of a ternary operator.

One such cases is when there's an execution flow that happens to return a value:

    if (this.Url.IsLocalUrl(returnUrl))
    {
        return this.Redirect(returnUrl);
    }
    else
    {
        return this.RedirectToAction("Index");
    }

I want to see that it's following different branches and not just return one of two possible values.

**Comment by giggio** [comment]
Makes sense to me.

**Comment by giggio** [comment]
I will also be changing `CC0014` as the argument is the same there.
