### ISSUE TITLE
CC0013 Should check for a common type and cast is necessary.

### ISSUE THREAD

**Issue by paulomorgado** [code-cracker/code-cracker#521]
Take this example:
````csharp
    if (this.Url.IsLocalUrl(returnUrl))
    {
        return this.Redirect(returnUrl);
    }
    else
    {
        return this.RedirectToAction("Index");
    }
````

It is rewritten as:

````csharp
return this.Url.IsLocalUrl(returnUrl) ? this.Redirect(returnUrl) : this.RedirectToAction("Index");
````

However, the return types are not the same and the compiler should assume that the expression has the value of the return type, but it doesn't.

````csharp
    return this.Url.IsLocalUrl(returnUrl)
        ? (ActionResult)this.Redirect(returnUrl)
        : this.RedirectToAction("Index");
````

**Comment by giggio** [comment]
You don't need to cast both the `WhenTrue` and the `WhenFalse`, only the first is needed. This should do:
````csharp
            return this.Url.IsLocalUrl(returnUrl) ? (ActionResult) this.Redirect(returnUrl) : this.RedirectToAction("Index");
````

I will update the description.

**Comment by paulomorgado** [comment]
Yes, in this particular case.

Let's try a more convoluted test:

    class Animal {}
    class Dog : Animal {}
    class Cat : Animal {}
    
    Animal Get(bool selection)
    {
        if (selection)
        {
            return new Dog();
        }
        else
        {
            return new Cat();
        }
    }

That should be rewritten into:

    Animal Get(bool selection)
    {
        return (selection)
            ? (Animal)new Dog()
            : (Animal)new Cat();
    }

It can get even trickier than that and I hope the compiler removes the casts in the future.

But as of now, none is being casted.

**Comment by giggio** [comment]
@paulomorgado You don't need the second cast. This will do:

````csharp
Animal Get(bool selection)
{
    return (selection)
        ? (Animal)new Dog()
        : new Cat();
}
````

**Comment by paulomorgado** [comment]
This is also valid:

    Animal Get(bool selection)
    {
        return (selection)
            ? new Dog()
            : (Animal)new Cat();
    }

That's how C# is still broken.

The point is you always need to look for a common ancestor.

**Comment by Shiney** [comment]
class Animal
    {
    }

    interface INoiseMaker
    {
        void MakeNoise();
    }


    class Dog : Animal, INoiseMaker
    {
        public void MakeNoise()
        {
            System.Console.WriteLine("Woof");
        }
    }

    class Cat:Animal, INoiseMaker
    {
        public void MakeNoise()
        {
            System.Console.WriteLine("Miaow");
        }
    }
    
Animal Get(bool selection)
{
    if (selection)
    {
        return new Dog();
    }
    else
    {
        return new Cat();
    }
}

How should this work? Should it cast it to INoiseMaker or should it cast it to Animal?

**Comment by paulomorgado** [comment]
`Animal` as it's the type of the return value of the method and it doesn't implement `INoiseMaker`.

A proper implementation would offer all the possibilities but `INoiseMaker` is not one of them.

**Comment by giggio** [comment]
I'll fix this one!
