### ISSUE TITLE
CC0013 Check for applicability as argument

### ISSUE THREAD

**Issue by paulomorgado** [code-cracker/code-cracker#522]
(This is a tricky one)

Consider this code:

```
if (condition)
{
    return Method(value1);
}
else
{
    return Method(value2);
}
```

Instead of rewriting as:

```
return condition ? Method(value1) : Method(value2);
```

Rewrite as:

```
return Method(condition ? value1 : value2);
```

**Comment by carloscds** [comment]
@paulomorgado It's interesting, but complex. What do you think about @code-cracker/owners ?

**Comment by giggio** [comment]
I like it, but this is going to vnext. :)

**Comment by MaStr11** [comment]
I would like to implement this. I started to prototype this to see if it could be easily integrated.
The proposed refactoring is already working in the prototype.
I came across some issues I would like to discuss.

1. Is it okay to start working on this?
2. I created branch from the *master* branch of my fork. Should I use *vnext* instead?
3. How should methods with multiple arguments be handled:

```CS
// Option1: Don't support multiple arguments. Refactor as before
    Method(1,1) 
else 
    Method(1,2)
refactor: cond?Method(1,1): Method(1,2)

// Option2: Allow multiple arguments, if both method calls use the same
// overload and differ only in one argument.
refactor: Method(1,cond?1:2)

//Option3: Allow multiple arguments and replace every argument that differs.
//This is bad for multiple reasons, but most import it is a breaking change
//because the condition is evaluated multiple times.
    Method(1,1) 
else 
    Method(2,2)
refactor: Method(cond?1:2,cond?1:2)
// I currently implemented option 2.
```

4. What else should be supported (argument *1* is the argument to be replaced 
   with the conditional expression):
   1. *Constructor*: `new A(1) else new A(2) refactor: new A(cond?1:2)`
   2. *Property access before method call*: 
       * `this.Method(1)`
       * `this.Service.Method(1)`
   3. *Method call between property access*:
       * `this.GetService(1).IsOnline`
       * `this.GetService().GetUser(1).Name`
   4. *Indexer*: `arr[0] else  arr[1] refactor: arr[cond?0:1]`
5. What should be tested
   1. Instance method (done)
   2. Instance method with several overloads (missing)
   3. Static methods (missing)
   4. Method call to a `dynamic` object (missing) 
   5. Local functions (C# 7, not possible yet, shouldn't be needed)
   6. Calls to anonymous functions/Lambda, e.g. `Action<int> action=arg=>{}; if (cond) action(1); else action(2)`; (shouldn't be needed)

**Comment by giggio** [comment]
Sure, send a PR!
