### ISSUE TITLE
Can't Manage extension settings

### ISSUE THREAD

**Issue by ImaginaryDevelopment** [code-cracker/code-cracker#524]
I've installed Code Cracker as an extension for Visual Studio 2015, but there appears to be no way to manage which diagnostics are on and what levels they are on at. I've found the analyzers node of References in solution explorer. While I can make changes there they don't seem to save as the new set the next time I open the solution or project. Even if they did, this is installed for my entire VS2015, so I'd like to manage it at that level rather than have to make changes to every project I open.

**Comment by giggio** [comment]
You can do it in VS. See this comment: https://github.com/code-cracker/code-cracker/issues/47#issuecomment-63705397

**Comment by ImaginaryDevelopment** [comment]
The link provides a way to set it per project, meaning for every project I open I have to go set the ruleset.

**Comment by giggio** [comment]
You can share the ruleset file with all the projects. Just move it to the root folder where the solution lives. This is what we are doing at CodeCracker, check the repo.
