### ISSUE TITLE
CC0022 does not recognize dispose in finally block

### ISSUE THREAD

**Issue by rtigithub** [code-cracker/code-cracker#529]
void Foo()
{
    var m = new MemoryStream();
    try
    {
        //other statements using m
       }
    finally
    {
        m.Dispose();
    }            
}

**Comment by carloscds** [comment]
@rtigithub Using last version of CodeCracker, dispose has been recognized. Can you try with last version ?

**Comment by giggio** [comment]
@rtigithub I also cannot confirm this bug. Can you try again with the version released yesterday (RC4)? I'll close the issue, if you find some where we can repro this, we will promptly reopen it, ok?
