### ISSUE TITLE
UnusedParametersCodeFixProvider will crash when it is trying to remove ParamArray

### ISSUE THREAD

**Issue by paul1956** [code-cracker/code-cracker#533]
For the following Sub
```
    Private Sub PrintSummary(ByRef Worksheet As IXLWorksheet, ByVal colData As ColDataCollection, ByVal ParamArray levels() As Integer)
        Dim ExcelRowIndex As Integer = FindExcelRow(Worksheet, colData(0).Value, False)
        For colDataIndex As Integer = 1 To colData.Count - 1
            Worksheet.Cell(ExcelRowIndex, colDataIndex + 2).Value = colData(colDataIndex).Value
        Next
    End Sub
```
with references that look like
```
PrintSummary(Worksheet, Total.ColDataList)
```
 Function RemovePArameterAsync needs to change from
```
Dim newArguments As ArgumentListSyntax = arguments.WithArguments(arguments.Arguments.RemoveAt(parameterPosition))
```
```
If arguments.Arguments.Count > parameterPosition Then
     Dim newArguments As ArgumentListSyntax = arguments.WithArguments(arguments.Arguments.RemoveAt(parameterPosition))
    replacingArgs.Add(arguments, newArguments)
End If
 ```

**Comment by giggio** [comment]
Bug confirmed. It is up for grabs. Are you going to work on it, @paul1956?

**Comment by paul1956** [comment]
I don't know how to work on GitHub, the two line change I posted fixes the bug. If you want to point to the process to "works on it" I will.

**Comment by giggio** [comment]
@paul1956 There was a problem on the way params was being handled. It had to remove all arguments, and it was only removing one. I fixed that and the exception is not happening anymore.
The problem also ocurred with C#.
See #535 and specially commit 873afb1. I also reenabled the analyzer and fixed the fix all, which was not working.

**Comment by paul1956** [comment]
The case that was causing my crash was when there are 0 parram array arguments calling the function.
