### ISSUE TITLE
Bug: Use ?.Invoke operator and method to fire 'configuration' event, though configuration can't be null

### ISSUE THREAD

**Issue by TsengSR** [code-cracker/code-cracker#536]
When validating parameters and enforcing the this methods invariants, Code-Cracker keeps giving this message, even though it's guaranteed that configuration can't be null. 

    public static class ActionInvokeExample
    {
        public void ActionExample(this IApplicationBuilder app, Action<IApplicationBuilder> configuration)
        {
            if (configuration == null)
            {
                throw new ArgumentNullException(nameof(configuration));
            }

            var builder = app.New();

            // Use ?.Invoke operator and method to fire 'configuration' event, though configuration
            configuration(builder);
    }

Please remove this warning, if the it was assured that configuration can't be null or change the suggestion to "configuration.Invoke(builder)" without the null check. We add this kind of check so we don't have to explicity do null-checks again

**Comment by giggio** [comment]
I agree this needs improvement. I have had this problem myself.
