### ISSUE TITLE
CC0001 Is raised on multiple variable declarations.

### ISSUE THREAD

**Issue by thorgeirk11** [code-cracker/code-cracker#537]
The following code raises CC0001 
```CSharp
public void Foo()
{
    string foo = "", otherFoo = "";
}
```
However the code fix introduces a compile error:
``` Error	CS0819	Implicitly-typed variables cannot have multiple declarators```

**Comment by giggio** [comment]
Bug confirmed.

**Comment by giggio** [comment]
Closed on #549.
