### ISSUE TITLE
UnusedParametersCodeFixProvider crashing when removing params

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#539]
Related to #533.

This will throw an error on the code fix provider:

````vb
Class Foo
    Sub Baz()
        go(1, 2)
    End Sub
    Function go(i As Integer, j As Integer, ParamArray xs As Integer())
        i += 1
        Return 1
    End Function
End Class
````

Params and ParamArray are working, but when trying to remove a parameter that has no argument passed to it (see above that the invocation to `Go(1,2)` does not pass an argument to `xs`) it throws.
Affects C# and VB. Both need fixing, and the fix is likely the same.

**Comment by giggio** [comment]
@ paul1956 here is the issue so you can follow.

**Comment by paul1956** [comment]
@giggio changing the "do" to a "while" seems to fix the issue for me.

**Comment by giggio** [comment]
@paul1956 You were right, simply changing the do to a while fixed it.
