### ISSUE TITLE
Is there any way to config inspect severity? Some errors are not necessary but noisy

### ISSUE THREAD

**Issue by iccfish** [code-cracker/code-cracker#543]
I wonder the possibility of add an inspect severity configuration like R#, due to some analysis errors are not really need to be fixed.

For example, checkout the source codes of [Dapper.Net](https://github.com/StackExchange/dapper-dot-net)  and open it in visual studio, almost 200+ errors were shown, and most of them are ```CC0090 incorrect xml documention```, ```CC0021 use nameof```.
![dapper_error](https://cloud.githubusercontent.com/assets/1091653/10391778/db08a428-6eb3-11e5-8bfb-f792b3a5f877.png)

If I use ```#pragma warning disable CC0090``` to disable CC0090, there are still 170+ errors, and says ```CC0001 Use var ``` ...

![dapper_error_2](https://cloud.githubusercontent.com/assets/1091653/10392039/1fe4fae0-6eb6-11e5-9f8d-f9f2c91f019b.png)

Of cause these are issues, but they don't need to be changed or rewrote due to they are third party projects or they are old projects, and works well currently. And I don't want make any changes to these projects even a little modification.
So it will be more effective if inspect severity could be configured.

Btw, I want to contribute on translation. I've already read the contributing guideline, and knew I need to start a new issue. But I don't know where to find all diagnostics (seems that [this page](http://code-cracker.github.io/diagnostics.html) was out-dated) and what's the content format of the issue.

**Comment by carloscds** [comment]
@iccfish We don't have documentation for all analyzers at this time, but you can see IDs at this page: https://github.com/code-cracker/code-cracker/wiki/DiagnosticIds

**Comment by giggio** [comment]
@iccfish You can already change the severity or even disable specific diagnostics. See https://github.com/code-cracker/code-cracker/issues/47#issuecomment-63705397 for details on how to do that. This is a Visual Studio/.NET thing, we just benefit from it. :)
I will be closing the issue, as it is already possible to do what you need. If you find there is more we can do, let us know.

**Comment by giggio** [comment]
@iccfish Regarding translation, not all analyzers are yet ready for translation. We would love to have translation happening. The infrastructure is the same as from any localized .NET assembly, based on resources.
But we still need to prepare the infrastructure for all the analyzers and fixers. We have issue #360 tracking that, with an example on how to do it. We would love your collaboration either making the analyzers and fixes localizable, or on the translation itself. What language are you interested in?

**Comment by iccfish** [comment]
My primary language was chinese (zh-CN), or C# if you mean the program language. I'll track issue #360 later :smile:

**Comment by giggio** [comment]
I meant speaking language. It would be awesome to have it translated to chinese! :)
I speak portuguese, and have not yet started the translation. No time!
