### ISSUE TITLE
BUG on ReadonlyFieldAnalyzer (CC0052) with assignment in Func<T> in constructor

### ISSUE THREAD

**Issue by mgrosperrin** [code-cracker/code-cracker#544]
With this code :
```
internal class Test
{
    private string _value;

    public Test()
    {
        Func<string> factory = () => _value ?? (_value = "Hello");
    }
}
```

the ReadonlyFieldAnalyzer shows a suggestion for the field ```_value```, but the field ca be assigned outside of the constructor (when invoking the Func).

**Comment by giggio** [comment]
Bug confirmed. It is up for grabs.

**Comment by mgrosperrin** [comment]
Hi @giggio,
I've created the PR #556 to fixes this issue.
