### ISSUE TITLE
CC0022 DI container delegate causes error

### ISSUE THREAD

**Issue by hmmdeif** [code-cracker/code-cracker#545]
Using Simple Injector and lifestyle scoping (so it handles disposables inside the container) triggers CC0022 when the class is registered using a delegate:

    container.Register<IDisposableIntr>(() => new DisposableImpl(), Lifestyle.Scoped);

This causes CC0022 to encounter an error and get disabled since it can't generate a solution. The warning is fine and I can disable it with a pragma declaration, but I figured the error probably shouldn't occur!

**Comment by giggio** [comment]
Bug confirmed. Here is a simple test case that is library independent:

````csharp
class Container
{
    static void Foo()
    {
        var container = new Container();
        container.Register<System.IO.MemoryStream>(() => new System.IO.MemoryStream());
    }
    void Register<T>(System.Func<T> f) { }
}
````
