### ISSUE TITLE
Update VS Code Galley page -- broken link for code-cracker.github.io 

### ISSUE THREAD

**Issue by BethMassi** [code-cracker/code-cracker#546]
Just want to send a quick note that the second link on your VS code gallery page  https://visualstudiogallery.msdn.microsoft.com/ab588981-91a5-478c-8e65-74d0ff450862 is broken and the link should be updated to code-cracker.github.io :smile: 

Keep up the great work!

**Comment by carloscds** [comment]
@BethMassi Thanks Beth, we will fix it.

**Comment by giggio** [comment]
@BethMassi Fixed. Thanks for letting us know.

**Comment by giggio** [comment]
Also fixed for the VB one.
