### ISSUE TITLE
Code fix error in CC0014 TernaryOperatorAnalyzer (assignment) 

### ISSUE THREAD

**Issue by filippobottega** [code-cracker/code-cracker#550]
Code fix for CC0014 TernaryOperatorAnalyzer is not compatible with += operator in VB code.
Example:
Original code:
          If values = String.Empty Then
            values = valueString
          Else
            values += ", " & valueString
          End If
Fixed code:
          values = If(values = String.Empty, valueString, ", " & valueString)

**Comment by giggio** [comment]
Bug confirmed. It should be pulled into the master branch.

**Comment by jwooley** [comment]
It looks like we have 3 open bugs for CC0014 in VB at this point. I can take them unless @filippobottega wants to try his hand.

**Comment by giggio** [comment]
@filippobottega do you?

**Comment by filippobottega** [comment]
Really sorry but I'm only a tester for the moment...

**Comment by giggio** [comment]
So, it is yours, @jwooley, I am assigning all 3 to you, I guess you will submit one PR for all 3, right?

**Comment by jwooley** [comment]
Fixed all 3 issues in changesets 2b5e919 and 0f2fb83. Having issues with rebase and pull requests with cherry picking. Let's work together at the hackathon to help me get git.

**Comment by giggio** [comment]
@jwooley Sure! ;)
