### ISSUE TITLE
Code fix error in CC0013 TernaryOperatorAnalyzer (return)

### ISSUE THREAD

**Issue by filippobottega** [code-cracker/code-cracker#552]
Hello,
  this code:

If FoldersTabControl.SelectedTab Is OutputTabPage Then
  Return OutputFileListBox
ElseIf FoldersTabControl.SelectedTab Is ErrorsTabPage Then
  Return ErrorsFileListBox
Else
  Return OutputFileListBox
End If

Is wrongly fixed as:

Return If(FoldersTabControl.SelectedTab Is OutputTabPage, OutputFileListBox, OutputFileListBox)

Best regards,
  Filippo Bottega.

**Comment by giggio** [comment]
Bug confirmed. Here is a simpler case:

````vb
            If 1 > 2 Then
                Return 1
            ElseIf 2 > 3 Then
                Return 2
            Else
                Return 3
            End If
````

It is incorrectly fixed to:

````vb
            Return If(1 > 2, 1, 3)
````

**Comment by giggio** [comment]
The analyzer should not report a diagnostic on such a situation.

**Comment by giggio** [comment]
Being worked on by @jwooley along with #550 and #551.
