### ISSUE TITLE
CC0013 Fix Error

### ISSUE THREAD

**Issue by filippobottega** [code-cracker/code-cracker#553]
For example:
    If nonClsCompliantIdentifiers.Contains(inputType.FullName.ToUpper) Then
      Return GetType(Object)
    ElseIf nonClsCompliantIdentifiers.Contains(Replace(inputType.FullName, "[]", "").ToUpper) Then
      Return GetType(Object())
    Else
      Return inputType
    End If

Is different from:

    Return If(nonClsCompliantIdentifiers.Contains(inputType.FullName.ToUpper), GetType(Object), inputType)

**Comment by jwooley** [comment]
I recommend that we not report this analyzer in cases where an ElseIf clause is present.

**Comment by giggio** [comment]
This is a duplicate of #552.
