### ISSUE TITLE
CC0031 is not appropriate for non-event delegates (e.g. System.Action)

### ISSUE THREAD

**Issue by wilhelmmedetz** [code-cracker/code-cracker#561]
public void Foo(Action action)
{
    action();
}

Generates CC0031 which is in my opinion not appropriate.

**Comment by giggio** [comment]
In your scenario, `action` could still be null, changing it to `action?.Invoke()` still makes sense.
But I think the wording could be better. This is not about events, it is about null delegates.
We have value in checking that.
Issue #536 is tracking the null check happening before.

What do you suggest?

**Comment by thomaslevesque** [comment]
I just stumbled onto this problem as well. I agree with @wilhelmmedetz, this diagnostic should only be emitted for events.

> In your scenario, action could still be null, changing it to action?.Invoke() still makes sense.

There are plenty of cases where you _know_ that the delegate is not null, and using `?.Invoke` implies that it could be null. The `?.Invoke` pattern is commonly used for events, but I don't think it should be generalized to all delegates, for the same reason we don't suggest using `?.` on all member accesses.

**Comment by wilhelmmedetz** [comment]
In my opinion firing an event is different from invoking an Action delegate. When firing an event yo usually make a local copy of  the delegates list (in order to assure thread safety), then check that the delegates are not null, and then invoke the delegates. This default pattern is exactly matched by the null-conditional operator.

event EventHandler<float> OnTemperatureChanged;

    FireEvent()
    {
        EventHandler<float> localOnChanged = OnTemperatureChanged;

        if (localOnChanged != null)
            localOnChanged(this, new EventArgs(...));

        // can be reduced to
        // OnTemperatureChanged?.Invoke(this, EventArgs(...));
    }

For pure action delegates I think there is no default pattern. For my example I would usually write something like

    public void Foo(Action action)
    {
        if (action != null)
            throw new ArgumentException(...);
        action();
    }

**Comment by andrecarlucci** [comment]
I agree with @wilhelmmedetz, it makes sense for events only imho :)

**Comment by giggio** [comment]
@wilhelmmedetz @andrecarlucci This pattern, with checking for null, was tracked on #536 and fixed on PR #568.
Does that fix it? It is already available on the RC4 and on the latest version on the extension gallery.

**Comment by wilhelmmedetz** [comment]
OK - enabling CC0016 and disabling CC0031 is a suitable solution for me.
