### ISSUE TITLE
CC0057 mistaken 'Parameter is not used' warning

### ISSUE THREAD

**Issue by wilhelmmedetz** [code-cracker/code-cracker#562]
The following code creates a 'CC0057 Parameter 'currentCulture' is not used' message, although the parameter is used.

        public static void SetDefaultThreadCulture(CultureInfo currentCulture, CultureInfo currentUICulture)
        {
            typeof(CultureInfo).InvokeMember("s_userDefaultCulture", BindingFlags.NonPublic | BindingFlags.Static | BindingFlags.SetField, null, null, new object[] { currentCulture }, CultureInfo.InvariantCulture);
            typeof(CultureInfo).InvokeMember("s_userDefaultUICulture", BindingFlags.NonPublic | BindingFlags.Static | BindingFlags.SetField, null, null, new object[] { currentUICulture }, CultureInfo.InvariantCulture);
            // CultureInfo.DefaultThreadCurrentCulture = new InternationalCultureInfo(); Requres .Net Framework 4.5
        }

**Comment by giggio** [comment]
I am not able to repro:

![screenshot 10](https://cloud.githubusercontent.com/assets/334958/10671290/3bb71442-78c0-11e5-8891-f3032bd8a68a.png)

Are you on the latest version of CodeCracker, and on VS RTM?

I will close the issue. If we can find a reproduceable code we can reopen it, ok?

**Comment by wilhelmmedetz** [comment]
I am still having this problem (Code Cracker 1.0.0.12)

A sample project reproducing this behavior can be downloaded at https://www.dropbox.com/s/bfjpw4p06t6mp9o/ClassLibrary1.zip?dl=0

My Visual Studio version is:
> Microsoft Visual Studio Professional 2015
> Version 14.0.23107.0 D14REL
> Microsoft .NET Framework
> Version 4.6.00079

![image](https://cloud.githubusercontent.com/assets/7532446/11059404/c4704f96-8799-11e5-9378-1c47fb88ae97.png)

**Comment by giggio** [comment]
Ok, now I was able to repro. Weird... Anyway, it is a bug, let's fix it!

**Comment by ElemarJR** [comment]
I asked for help from the team. 

There are differences from DataFlowAnalysis between run-time and test environments.

**Comment by ElemarJR** [comment]
I just reported an issue on Roslyn repo. 

https://github.com/dotnet/roslyn/issues/6967

Let's see what comes from the team.
