### ISSUE TITLE
IP Parsing fails for variables

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#571]
This will incorrectly raise `CC0064`:

````csharp
var correctIP = "0.0.0.0";
System.Net.IPAddress.Parse(correctIP);
````

The analyzer should ignore non string literals.

Might be happening also for others, like Regex and Json.

**Comment by andrecarlucci** [comment]
I can fix that :)

-----Original Message-----

**Comment by giggio** [comment]
@andrecarlucci Go for it!
