### ISSUE TITLE
Remove empty Catch Block too aggressive

### ISSUE THREAD

**Issue by jwooley** [code-cracker/code-cracker#587]
If code has multiple catch blocks in a single try, when selecting the fix to remove empty catch block, it removes all catch blocks not just the one requested. Sample test:

  public void foo()
    {
        try
        {
            Console.WriteLine("foo");
        }
        catch (ArgumentException aex)
        {  
            
                   
        }
        catch 
        {
            throw;
        }
    }

Should return 
  public void foo()
    {
        try
        {
            Console.WriteLine("foo");
        }
        catch 
        {
            throw;
        }
    }

but instead, returns
  public void foo()
    {
        Console.WriteLine("foo");
    }

Is broken in C# and VB

**Comment by giggio** [comment]
Bug confirmed.
