### ISSUE TITLE
Suggested Nameof fix incorrectly suggests wrong type

### ISSUE THREAD

**Issue by mirhagk** [code-cracker/code-cracker#594]
The following code fragment 

        public ActionResult ChangePassword(ChangePasswordMessageId? message, bool? Redirect = false)
        {
            var returnUrl = "ChangePassword";

Correctly identifies a place where `nameof` should be used. However it suggests using `nameof(ChangePasswordMessageID)` instead of the correct `nameof(ChangePassword)`. If I change the type of `message` it produces the correct fix, and if I change `returnUrl` to `"ChangePasswordMessage"` then it does not suggest any fix. This leads me to believe that it's correctly identifying the issue, but incorrectly finding the suggested fix because of the matching prefix, although I haven't looked at the code so I can't be sure (I'll take a look later on if you want).

Tested with code-cracker version 1.0.0-rc2 (although I believe it also existed in earlier versions).

Here is a simple test that will not work:

````csharp
public class TypeName
{
    void Foo(TypeName d)
    {
        var bar = new [] { "Foo" };
    }
}
````

And here is the test case:

````csharp
        [Fact]
        public async Task ReplacesUsingMethodName()
        {
            const string source = @"
public class TypeName
{
    void Foo(TypeName d)
    {
        var bar = new [] { ""Foo"" };
    }
}";

            const string fixtest = @"
public class TypeName
{
    void Foo(TypeName d)
    {
        var bar = new [] { nameof(Foo) };
    }
}";
            await VerifyCSharpFixAsync(source, fixtest);
        }
````

@mirhagk is working on it.

**Comment by mirhagk** [comment]
Actually while searching through the code base I found another similar problem 


        public ActionResult Index(int? id = null, FormResponse<object> response = null, string searchQuery = "")
        {
            var viewModel = new ShipmentIndexViewModel
            {
                SearchQuery = searchQuery,
                Response = response ?? new FormResponse<object>()
            };
            return View("Index", viewModel);

Here it identifies an issue but suggest replacing `"Index"` with `nameof(FormResponse)`. This perhaps invalidates my prefix theory.

**Comment by carloscds** [comment]
@mirhagk I try to repro this issue, CC replace "Index" to "nameof(Index)"

**Comment by mirhagk** [comment]
Hmm perhaps it was an issue with rc2 but now fixed in rc4? I'll try on a simplified project and if I can reproduce it I'll share the project. On a related note I'm having a lot of difficulty convincing VS to actually update the analyzer. I've updated the nuget package, but that doesn't seem to be enough?

**Comment by carloscds** [comment]
@mirhagk If you can share a project, will be great!

**Comment by giggio** [comment]
@mirhagk I've tagged as `Can't repro` until we find a simple case we can verify, ok? When it is found we can remove the tag.

**Comment by mirhagk** [comment]
https://github.com/mirhagk/TestReproduceCodeCrackerIssue594 I can't seem to determine the exact cause but it doesn't seem to be overly difficult to reproduce.

**Comment by carloscds** [comment]
Bug confirmed: 
![2015-11-19_14-11-48](https://cloud.githubusercontent.com/assets/1697221/11276048/9c062b0e-8ec7-11e5-92f3-ed289e54bf5e.png)

**Comment by mirhagk** [comment]
Great. As far as I can tell it isn't related to the name being the same, or the clas being in the same file. So I'm not sure what the root cause is

**Comment by mirhagk** [comment]
Alright found the issue. Design\NameOfAnalyzer.cs line 91:

    programElementName = symbol.ToDisplayParts().LastOrDefault(AnalyzerExtensions.IsName).ToString();


For the unit test I added `symbol.ToString()` is `N1.N2.@using.@class.Foo3(string,N1.N2.@using.BaseTypeName)`.`ToDisplayParts` returns `N1,N2,@using,@class,Foo3,string,N1,N2,@using,BaseTypeName` so this would be the wrong thing to use for methods. I have a potential fix coming in a pull request
