### ISSUE TITLE
Change project Erros and Warnings

### ISSUE THREAD

**Issue by carloscds** [code-cracker/code-cracker#598]
Change CodeCracker projects property "Treat warnings as error" to None to avoid compiler errors.

**Comment by giggio** [comment]
I don't think this should be done. Warning as errors will prevent warnings. If we have an specific warning we don't want to appear, we should suppress that specific instance.
Today's warning is tomorrow's bug.

**Comment by jwooley** [comment]
I'm still seeing the AD0001 compile error with VS 2015 Update1 even after updating to the 1.1.0.0 Analyzers libraries. I was able to remove the old analyzer reference and get the project to compile. Running the vsix debugger, I think I've identified the source error. When compiling Code Cracker through the vsix, experimental debugging option, the compiler crashes on HasCheckForNull in UseInvokeMethodToFireEventAnalyzer when being called from the FixAllDiagnosticProvider (although I'm not sure which analyzer is firing into the FixAllDiagnosticProvider yet. The underlying issue appears to be the fact that method.Body is null somewhere.

        private static bool HasCheckForNull(InvocationExpressionSyntax invocation, SemanticModel semanticModel, ISymbol symbol)
        {
            var method = invocation.FirstAncestorOfKind(SyntaxKind.MethodDeclaration) as MethodDeclarationSyntax;
            if (method != null && method.Body != null)
            {
                var ifs = method.Body.Statements.OfKind(SyntaxKind.IfStatement);

Modifying the analyzer to include a null check for method.Body seems to resolve the compiler issue:

            if (method != null && method.Body != null) { ...

What I haven't been able to determine is a test case to repro the error and was hesitant to check in the change without one. Fixing this bug will allow you to compile with treat warnings as errors again however.

Additionally, I was unsure how we wanted to handle the Analyzer 1.0 - 1.1 update from a build perspective.

**Comment by giggio** [comment]
Closed on f767d631f18aea0a940da2f8370796a417c724b7.
@carloscds instead of disabling warning as errors, we just need to disabled `AD0001` as an error. That was done on f767d631f18aea0a940da2f8370796a417c724b7. This way we are not stopped from other analyzer's errors and we still get to keep warnings away. All we needed to do is add `<WarningsNotAsErrors>AD0001</WarningsNotAsErrors>` to the .csproj and .vbproj files.
