### ISSUE TITLE
Rule CC0043 Change Any to All collides with Resharper Linq rule

### ISSUE THREAD

**Issue by OsirisTerje** [code-cracker/code-cracker#601]
Resharper want to change All to Any, and this rule suggest changing Any to All.  
The code line where I see this suggestion is
![image](https://cloud.githubusercontent.com/assets/203432/11251665/9acac6a4-8e32-11e5-9fbf-930d8b801874.png)

And I can't see it makes any sense here.

**Comment by giggio** [comment]
@OsirisTerje See the discussion on item #31. This is a hidden diagnostic, so you will only see it if you ask for it (CTRL DOT). Any or All depends on your logic, there is no way to determine which one is better.
I will close the issue, but if you can find a proposed algorithm to fix that, or even some pseudo code on how to change that analyzer or bring a way for us to fix it, we can reopen it, ok? And if you don't want to see the suggestion, you can always disable the analyzer.
