### ISSUE TITLE
Duplicate ruleset

### ISSUE THREAD

**Issue by wmjordan** [code-cracker/code-cracker#608]
CC0021 and CC0108 are the same.
So to CC0052 and CC0074; CC0013 and CC0014.
Please remove the duplicated one or change their names and descriptions if they are actually different.

**Comment by giggio** [comment]
No, 21 is for symbols in your solution, 108 is for outside.
52 was removed on recent versions.
13 is for a ternary on a return statement, 14 for a ternary on an assignment.
