### ISSUE TITLE
Not all objects need to be Disposed

### ISSUE THREAD

**Issue by RehanSaeed** [code-cracker/code-cracker#619]
Some objects like the `HttpClient` and `HttpWebRequest` do not need to be disposed even though they implement `IDisposable`. In fact the advice is not to dispose `HttpClient`. Please add exceptions for these types. I'm sure there are others.

**Comment by carloscds** [comment]
@code-cracker/owners What do you think about this ?

**Comment by giggio** [comment]
HttpClient has to be disposed, it would not make sense to implement IDisposable if it was not disposable. When it opens a connection it holds unmanaged resource until it is disposed. You might reuse it on your app, so you don't open unnecessary local ports, and might dispose it only when your app closes, but if you try to create 10000 HttpClients and not close any you might end up exausting your machine resources.
So, I vote that, for this cases, the user should disable it with `#pragma`.

**Comment by carloscds** [comment]
@giggio It's make sense for me too.
