### ISSUE TITLE
CC0017 Code fix "fixes" more than it should

### ISSUE THREAD

**Issue by TineSvete** [code-cracker/code-cracker#622]
It seems CC0017 code fix unnecessarily deletes empty line above backing field.

Before applied fix ...
```C#
      private object someField = null;

      private string test;
      public string Test
      {
         get
         {
            return test;
         }

         set
         {
            this.test = value;
         }
      }
```

... after fix (there is empty line missing after "someField") ...

```C#
      private object someField = null;
      public string Test
      {
         get;
         set;
      }
```
... if there is empty line between backing field and property, then fix works fine. After testing some various configurations of backing field and property it seems the fix tries to delete empty line above backing field no matter what (if it exists).

**Comment by giggio** [comment]
It does because it is removing the field `test` altogether, and the empty line before it was part of the field's trivia. It would also remove any comment on the field.
So this:

````csharp
class Bazz
{
    private object someField = null;

    //field comment
    private string test;
    //prop comment
    public string Test
    {
        get
        {
            return test;
        }

        set
        {
            test = value;
        }
    }
}
````

Is becoming:

````csharp
class Bazz
{
    private object someField = null;
    //prop comment
    public string Test { get; set; }
}
````

I am not sure this is a problem. Do you have a suggested fix? What do you think, @code-cracker/owners?

**Comment by carloscds** [comment]
@giggio I think that is not a problem. Maybe a second fix ?

**Comment by TineSvete** [comment]
First of all, I don't see this as big problem in any way, I just posted it because I imagine the behavior can be fairly easily changed.

Perhaps it's just me, but I think the fix should leave an empty line in given situation, since this is usually part of the coding style and current situation demands to manually add deleted line. The way I see it the empty line in provided situation does not "belong" to backing field, but to "someMember" in sense it is not the last member in code block, therefore it needs empty line behind it. So to sum it up ... empty space should be deleted only if backing field (plus potential comment) is surrounded by two empty lines (one above and one below) or empty space is between backing field and property or backing field is the last member in code block (to prevent empty lines before closing brace) ... there might be of course some corner cases.

**Comment by giggio** [comment]
@TineSvete I understand, but the way the compiler does this is by assigning the empty line to the field's trivia, not to the property's trivia. We can discuss keeping the trivia there, and removing only the field. That would keep the line break and also any comments. This makes sense to me.
The problem we create if we do that is that several people to not leave the field next to the property, but at the top of the file, with other fields. Removing the field but not the trivia would leave a pending comment on the file, and that comment would immediately become part of the next field. Like this:

````csharp
class Bazz
{
    private object someField = null;
    //field comment
    private string test;
    //field comment2
    private string test2;

    //prop comment
    public string Test
    {
        get
        {
            return test;
        }

        set
        {
            test = value;
        }
    }
}
````

Would become:

````csharp
class Bazz
{
    private object someField = null;
    //field comment
    //field comment2
    private string test2;

    //prop comment
    public string Test { get; set; }
}
````

Notice the 2 comments, one on top of the other, `//field comment` is now part of field `test2`. That is not nice.

**Comment by TineSvete** [comment]
@giggio as this seems to be a decision between deleting one empty row too many or not removing obsolete/misleading comment I definitely agree that failing to do the latter is much worse.

As far as I'm concerned you can mark this "issue" as closed/non-issue as I'm sure there are far more important areas to put your resources in.

**Comment by giggio** [comment]
Ok, @TineSvete, I will close the issue. If you can find a way to compromise between this options, we would love to hear it. Let us know.

**Comment by TineSvete** [comment]
@giggio I agree ... thanks for the feedback and great job guys.
