### ISSUE TITLE
CC0001 is shown for variables with type dynamic and object

### ISSUE THREAD

**Issue by Duetting** [code-cracker/code-cracker#625]
`CC0001` should not be reported for dynamic like this:

````csharp
dynamic foo = new object();
````

See discussion bellow. It only happens when the right hand side of the assignment is an object. This already does not report `CC0001`:

````csharp
dynamic foo = 1;
````

Original comment:

> Imho it doesn't make sense and can generate errors if the type definition of a variable is changed from dynamic to var. Especially when using COM we use variables of type dynamic. The type dynamic should never be replaced with var, as it's intentionally used.

**Comment by giggio** [comment]
CodeCracker will only suggest to change it to var if the right hand expression on the assignment is already dynamic, making the type unnecessary. If the expression is not dynamic, it will not suggest the change.

So, this will raise CC0001:
````csharp
void Foo()
{
    dynamic j = M();
}
dynamic M() { return 1; }
````

And this will not, as the value of `j` would change:
````csharp
void Foo()
{
    dynamic j = M();
}
int M() { return 1; }
````

This is as expected.

I am closing the issue, if you find we missed something let us know and we can reopen it.

**Comment by Duetting** [comment]
I got CC0001 here:
```csharp
            dynamic nafi = Activator.CreateInstance(itemType);
```
Activator.CreateInstance returns an object and not dynamic. We use this for late binding to a COM object and if the nafi variable is changed to "type" var, calling of the COM methods of nafi isn't possible any more.

**Comment by giggio** [comment]
Ok, confirmed! Weird, it does not work for `object`! I am reopening the issue! Thanks for the follow up.

**Comment by Duetting** [comment]
I have to thank you and your team for a great Analyzer. Had the dream to replace all our property name references of our ORM business classes (e. g. every setter has to have a method call with the property name as one of the parameters) with nameof. And with Code Cracker i managed to get that done in all of our over 600 classes in less than a day. 
And i found a few places too where there were already errors because of a mismatch. So the nameof FixAllProvider alone saved and will save me a lot of work and will enhance the quality of our products.

**Comment by giggio** [comment]
@Duetting Hey, thank you for the feedback! That really encourages us to keep going! I am happy CodeCracker was able to help! :)

**Comment by thorgeirk11** [comment]
Dose this mean that the `AlwaysUseVarAnalyzer` has to ignore all cases of `dynamic` variables?

**Comment by giggio** [comment]
Not, not all. It already works correctly in some cases. See the description.
I am assigning it to you, @thorgeirk11.
