### ISSUE TITLE
BUG: CC0091 WPF event cannot be static

### ISSUE THREAD

**Issue by huoyaoyuan** [code-cracker/code-cracker#639]
For example `Window_Loaded`, it is being referenced by `MainWindow.g.i.cs`, like this:

````csharp
((Showcase.MainWindow)(target)).Loaded += new System.Windows.RoutedEventHandler(this.Window_Loaded);
````

And these events have to be instance methods, see: https://msdn.microsoft.com/en-us/library/cc221357%28v=VS.95%29.aspx

We could check for them being passed to `RoutedEventHandler`, and ignore them.

Original description:

> Similar to #451 
> It seems that xaml haven't be resolved.
> There may be information in .g.i.cs .

**Comment by giggio** [comment]
@huoyaoyuan Can you provide an example?

**Comment by huoyaoyuan** [comment]
[Showcase.zip](https://github.com/code-cracker/code-cracker/files/75665/Showcase.zip)
A very very simple showcase with nothing but only an event handler.
Use Code Cracker as vsix.
A CC0091 is on Window_Loaded, and when I try to "fix it", the fix provider crashes.
And in fact, the method cannot be static at all.

**Comment by giggio** [comment]
@huoyaoyuan Ok, I logged the bug for the crash on issue #644.
Regarding `Window_Loaded`, it is being referenced by `MainWindow.g.i.cs`, like this:

````csharp
((Showcase.MainWindow)(target)).Loaded += new System.Windows.RoutedEventHandler(this.Window_Loaded);
````

And these events have to be instance methods, see: https://msdn.microsoft.com/en-us/library/cc221357%28v=VS.95%29.aspx

Maybe we could check for them being passed to `RoutedEventHandler`, and ignore them?

**Comment by huoyaoyuan** [comment]
@giggio Good. This can be a way.
By the way, how about event handlers in Windows Forms? Consider to treat them as instance or not?

**Comment by giggio** [comment]
@huoyaoyuan Do they need to be instance methods? If they don't, then we don't need to do anything.

**Comment by huoyaoyuan** [comment]
@giggio It seems not. Usually there will be references to instance fields in handlers.

**Comment by giggio** [comment]
@huoyaoyuan That is alright, if there are references to fields than CodeCracker will not suggest to change it to static.

**Comment by giggio** [comment]
I got it to work a little differently. Instead of checking for calls passing the method to `RoutedEventHandler`, which would be hard, or maybe impossible, I checked if the method had a `RoutedEventArgs` parameter. Works the same.
PR is up.
