### ISSUE TITLE
Readonly reference field is never assigned and is used

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#647]
When a reference readonly field is not assigned inside the constructor or during declaration, raise an error.

This should raise a diagnostic:

````csharp
class Foo
{
    private readonly object o;
    void Bar()
    {
        o.GetHashCode();
    }
}
````

This should not:

````csharp
class Foo
{
    private readonly object o = new object();
    void Bar()
    {
        o.GetHashCode();
    }
}
````

This also should not:

````csharp
class Foo
{
    private readonly object o;
    public Foo()
    {
        o = new object();
    }
    void Bar()
    {
        o.GetHashCode();
    }
}
````

Should apply to any usage, such as member access, being passed as parameter, used in any expression, etc.

There is no code fix.

Category: Design
Diagnostic id: `CC0112`
Severity: Error

**Comment by carloscds** [comment]
@giggio It's raise a warning CS0649. An have a probem with this when class have parameters in constructor:

`````CSharp
class Foo
{
    private readonly MyClass o;
    public Foo()
    {
        o = new object(); // how can I implement a constructor here ?
    }
    void Bar()
    {
        o.GetHashCode();
    }
}

class MyClass
{
   public MyClass(int par1, int par2)
   {
      // do something
   }
}
`````

**Comment by giggio** [comment]
@carloscds I don't think we should care about how the user will implement the object constructor call. It is their problem. If they decide they need it, then they **have** to do it, other a null reference exception will **always** throw inside the `Bar` method call for `GetHashCode`.

**Comment by carloscds** [comment]
@giggio Even breaking the code ?

**Comment by giggio** [comment]
There is no code fix, so we cannot break any code, this is only an analyzer with a diagnostic of the problem.

**Comment by carloscds** [comment]
@giggio Ok, In this case this analyzer will cause only an error code, without any fix ?

**Comment by giggio** [comment]
@carloscds Yes, just like the regex analyzer.

**Comment by carloscds** [comment]
@giggio Good, I think that is needed change description.

**Comment by giggio** [comment]
`CS0649` already does this. https://msdn.microsoft.com/en-us/library/03b5270t.aspx
