### ISSUE TITLE
Change from as operator to direct cast or the opposite

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#65]
This:

````csharp
var nullLiteral = returnElse.Expression as LiteralExpressionSyntax;
````

Becomes:

````csharp
var nullLiteral = (LiteralExpressionSyntax)returnElse.Expression;
````

Or the opposite, turn a direct cast into an expression with the `as` operator.

Severity is `Hidden`.
Diagnostic id is `CC0028`.
Category: `Refactoring`

**Comment by MisinformedDNA** [comment]
I don't think you should do refactorings that could break code. If you are going to refactor code, it must result in the same thing as before. We should guide developers into the pit of success, not give them an easy path to failure.

**Comment by giggio** [comment]
@code-cracker/owners I am moving this to `Ready`. If you disagree let me know.

**Comment by thomaslevesque** [comment]
I started work on this one and I'm making good progress, I should be able to submit a PR today

**Comment by giggio** [comment]
@thomaslevesque How is this coming?

**Comment by thomaslevesque** [comment]
Hi @giggio,

PR #422 was merged a while ago, which should have closed the issue automatically... not sure why it didn't. As far as I'm concerned, it's done.

**Comment by thomaslevesque** [comment]
Actually I think the issue wasn't closed automatically because the PR was merged into vnext, not master.

**Comment by giggio** [comment]
Right... That's why I couldn't find the files you worked on. I was looking on master. Sorry about that. Thanks!
