### ISSUE TITLE
CC0074 readonly field cannot be setted in derived class

### ISSUE THREAD

**Issue by huoyaoyuan** [code-cracker/code-cracker#657]
If I have a protected field in base class, and I set it __only__ in the constructor of derived class, there will be a CC0074 to make me change it to readonly.
But in fact, a readonly field cannot be setted in derived class, even in constructor.
Maybe a further version of C# will change this behavior, but it gets a CS0191 at current version.

**Comment by huoyaoyuan** [comment]
It seems to be my fault.
When I use a `#pragma warning disable`, the warning still doesn't disappear until I restart Visual Studio.

**Comment by huoyaoyuan** [comment]
But, the warning reappears when I do some changes, and cannot be disabled until I restart Visual Studio. I have no idea about it.

**Comment by giggio** [comment]
I just tried it, could not repro. Here is the code:

````csharp
class Base
{
    protected int i;
}
class Derived : Base
{
    public Derived()
    {
        i = 1;
    }
}
````

**Comment by carloscds** [comment]
@huoyaoyuan Can you put a code sample here ?

**Comment by huoyaoyuan** [comment]
@carloscds I'm sorry, but it seems to be unstable that a warning does not disappear when I add `#pragma`, and reappears unreasonably. I'll wait for a stable version of the Analyzer.

**Comment by carloscds** [comment]
@huoyaoyuan To correct analyzer, if appropriate, we need to understand your scenario. It's important for us a sample code in your scenario. If possible, create a simple code and share with us.

**Comment by huoyaoyuan** [comment]
@carloscds In fact, I'm not sure what causes this issue at all. I have many readonly fields in my program, and sometimes when I do some changes to one, the warning may appears. But I haven't found out what kind of edit may cause it. I could not provide any further information.

**Comment by giggio** [comment]
@huoyaoyuan This could be a bug on the compiler infrastructure. When you change a node, the compiler recompiles it, and every parent of it. If the compiler is not being able to finish, the diagnostic is not added or removed in time, and you might see stale diagnostics. This could happen if your PC is starved out of CPU time, for example. Usually, the compiler is really fast.
The same problem could happen when you add or remove a `#pragma`.
Have you seen this problem with any other diagnostic?
Do you think that what I said above applies to your problem?

**Comment by huoyaoyuan** [comment]
@giggio Thanks. This may help. At least I know why `#pragma` doesn't work.
I haven't seen this problem with other diagnostic yet.
