### ISSUE TITLE
CC0031 should not copy the variable with readonly members

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#663]
Same as #645 but for `CC0031`.

This should not raise `CC0031`:

````csharp
class Foo
{
    readonly Action a = () => { };
    public void Bar()
    {
        a();
    }
}
````

@Vossekop is working on it.

**Comment by giggio** [comment]
@Vossekop You might want to fix this one, as you did the other one.
@haacked I guess this one is bothering you as well. It's the same problem. We are discussing on #662 as these 2 analyzers seem to be doing very similar work.

**Comment by Vossekop** [comment]
@giggio I'll have a look at it tonight. Is there a place in the solution already where we can put common utility methods. So I can move the check for initializers code there?

**Comment by giggio** [comment]
There are some extensions we have been using. If it is common for C# and VB use the `Common` project, otherwise, you will find it in the C# project.

**Comment by Vossekop** [comment]
Sorry for the long wait, ISP issues still ruining my week. Got a chance to add some unit tests for this situation now but somehow they pass with the current code.

**Comment by giggio** [comment]
No problem, if you need help let us know. We are trying to close all bugs until the end of the month to finally get 1.0 out.
