### ISSUE TITLE
CC0031 must not fire when Null-check is outside of a try block

### ISSUE THREAD

**Issue by wertzui** [code-cracker/code-cracker#672]
I have the following code which fires CC0031:

    if (method != null)
    {
        try
        {
            method(parameter);
        }
        catch (Exception e)
        {
             ...
        }
    }

I expect CC0031 to not fire when there is a Null-check somewhere above in the call-chain and there is no assignment to "method" between the check and the invocation.

**Comment by giggio** [comment]
Agreed. We are already checking for something similar. If you do:

````csharp
public static void Execute(System.Action action)
{
    if (null == action) throw new Exception();
    action();
}
````

or

````csharp
public static void Execute(System.Action action)
{
    if (action == null) return;
    action();
}
````

We will not raise. Your proposal also makes sense.
