### ISSUE TITLE
ObjectInitializerCodeFixProvider crashes

### ISSUE THREAD

**Issue by jakubsuchybio** [code-cracker/code-cracker#676]
Hi.
When I wanted to resolve aprox. 60 Warnings via BatchFixAllProvider of CC0008, I encountered crash.
So I started to make it manually and I found one, that is crashing ObjectInitializerCodeFixProvider and I think that was a reason for BatchFixAllProvider crashes.
Here is the snippet:
```
var quitButton = new GButton( 0x7D9, 0x7DB, 0x7DA, 18, 445, new OnClick( FinalGumps.Quit_OnClick ) );
quitButton.Tooltip = new Tooltip( ClientLocalization.GetString( "#57#Ukončit Ultimu Online" ) );
```
Hope it helps to solve these crashes, regards.

**Comment by giggio** [comment]
Bug confirm, I will work on it.

**Comment by jakubsuchybio** [comment]
Fix confirmed on our codebase via alpha-nuget package.

**Comment by giggio** [comment]
Awesome! :D
