### ISSUE TITLE
BUG: CC0091 (make static) changes references incorrectly when used as a method group and in conjunction with another method invocation

### ISSUE THREAD

**Issue by jakubsuchybio** [code-cracker/code-cracker#680]
This is producing an incorrect fix:

````csharp
class Bar
{
    void ShouldBeStatic()
    {
    }
    void Caller()
    {
        Foo.M(new Baz(ShouldBeStatic));
    }
}
class Foo
{
    public static void M(Baz b) { }
}
class Baz
{
    public Baz(Action a)
    {
    }
}
````

This is the current fix, broken (other classes omitted):

````csharp
class Bar
{
    static void ShouldBeStatic()
    {
    }
    void Caller()
    {
        M(new Baz(ShouldBeStatic));
    }
}
````

This is the expected fix (other classes omitted, only `static` added to method, nothing else changed):

````csharp
class Bar
{
    static void ShouldBeStatic()
    {
    }
    void Caller()
    {
        Foo.M(new Baz(ShouldBeStatic));
    }
}
````

Here is the original description from @jakubsuchybio:

> I found another error in CC0091 which somehow changes another method.
> Dunno why it is changing things in another method not related to the changed method.
> ```c#
>         private void ResetButton_Confirm(Gump sender, bool response)
>         {
>             if( response )
>             {
>                 PerConfig.DefaultMacros();
>                 MacroProvider.InstanceIndex = 0;
>             }
> 
>             GMacroEditorForm.Open();
>         }
> 
>         private void ResetButton_OnClick(Gump g)
>         {
>             this.Close();
>             Gumps.Desktop.Children.Add( new GMessageBoxYesNo(
>                 ClientLocalization.GetString( "#319#Smazat všechna\rvlastní makra?" ),
>                 true,
>                 ResetButton_Confirm ) );
>         }
> ```
> Translates into:
> ```c#
>         private static void ResetButton_Confirm(Gump sender, bool response)
>         {
>             if( response )
>             {
>                 PerConfig.DefaultMacros();
>                 MacroProvider.InstanceIndex = 0;
>             }
> 
>             GMacroEditorForm.Open();
>         }
> 
>         private void ResetButton_OnClick(Gump g)
>         {
>             this.Close();
>             Add( new GMessageBoxYesNo(
>                             ClientLocalization.GetString( "#319#Smazat všechna\rvlastní makra?" ),
>                             true,
>                             ResetButton_Confirm ) );
>         }
> ```
> Here is a picture of preview:
> ![cc0091-crazy-error](https://cloud.githubusercontent.com/assets/6567287/12627789/19512aec-c540-11e5-8d2d-58bd3de28a96.png)
> 
> Another occurence of this bug here:
> ```c#
>         private void Export(string fileName)
>         {
>             var dialog = new System.Windows.Forms.SaveFileDialog
>             {
>                 FileName = "mwmakra.mul",
>                 InitialDirectory = Environment.GetFolderPath( System.Environment.SpecialFolder.MyDocuments )
>             };
> 
>             var result = dialog.ShowDialog();
>             if( result == System.Windows.Forms.DialogResult.OK )
>             {
>                 System.IO.File.Copy( fileName, dialog.FileName, true );
>             }
>             System.IO.File.Delete( fileName );
>         }
> 
>         private void ExportButton_OnClick(Gump g)
>         {
>             var fileName = System.IO.Path.GetTempFileName();
>             this.Close();
>             MacroProvider.Export( fileName );
>             GSystemDialogWaiter<string>.Run( Export, fileName, ExportCompleted );
>         }
> ```
> Translates into:
> ```c#
>         private static void Export(string fileName)
>         {
>             var dialog = new System.Windows.Forms.SaveFileDialog
>             {
>                 FileName = "mwmakra.mul",
>                 InitialDirectory = Environment.GetFolderPath( System.Environment.SpecialFolder.MyDocuments )
>             };
> 
>             var result = dialog.ShowDialog();
>             if( result == System.Windows.Forms.DialogResult.OK )
>             {
>                 System.IO.File.Copy( fileName, dialog.FileName, true );
>             }
>             System.IO.File.Delete( fileName );
>         }
> 
>         private void ExportButton_OnClick(Gump g)
>         {
>             var fileName = System.IO.Path.GetTempFileName();
>             this.Close();
>             MacroProvider.Export( fileName );
>             Run( Export, fileName, ExportCompleted );
>         }
> ```
> Here is a picture of preview of second occurence:
> ![cc0091-crazy-error2](https://cloud.githubusercontent.com/assets/6567287/12627806/2401d400-c540-11e5-8dc5-ee3c0840ad09.png)
> 
> I would post you my whole codebase to test it on it, if you couldn't find a code proof, but this project is not open and my employer wouldn't like it.

**Comment by giggio** [comment]
@jakubsuchybio bug confirmed, I have narrowed it down to a simpler case. Thanks for the report.

**Comment by martinzimmermann** [comment]
@giggio my pull request also fixes this issue
