### ISSUE TITLE
CC0017 wrong change with explicitly implemented properties, but can be fixed

### ISSUE THREAD

**Issue by jakubsuchybio** [code-cracker/code-cracker#687]
Hi.
I came across some code, that I didn't even know was possible, but there it gives wrong output after fix with CC0017. See:
```c#
		interface ITranslucent
		{
			float Alpha { get; set; }
		}

		class Foo : ITranslucent
		{
			private float _alpha;
			float ITranslucent.Alpha
			{
				get
				{
					return _alpha;
				}

				set
				{
					_alpha = value;
				}
			}

			public Foo()
			{
				_alpha = 0.0f;
			}
		}
```
Translates into:
```c#
		interface ITranslucent
		{
			float Alpha { get; set; }
		}

		class Foo : ITranslucent
		{
			float ITranslucent.Alpha { get; set; }

			public Foo()
			{
				Alpha = 0.0f;
			}
		}
```
And that gives me error in constructor, that Alpha doesn't exist in current context.

But when this Interface isn't implemented it gives me 2 options:
![image](https://cloud.githubusercontent.com/assets/6567287/12639242/5148a192-c5a3-11e5-9fb9-4f8143cffa5f.png)
and
![image](https://cloud.githubusercontent.com/assets/6567287/12639248/625444fa-c5a3-11e5-8c43-f427a2894dae.png)

When the property is not implemented explicitly like this:
```c#
		interface ITranslucent
		{
			float Alpha { get; set; }
		}

		class Foo : ITranslucent
		{
			private float _alpha;
			public float Alpha
			{
				get
				{
					return _alpha;
				}

				set
				{
					_alpha = value;
				}
			}

			public Foo()
			{
			}
		}
```
It translates into:
```c#
		interface ITranslucent
		{
			float Alpha { get; set; }
		}

		class Foo : ITranslucent
		{
			public float Alpha { get; set; }

			public Foo()
			{
			}
		}
```
Which is correct.

So I wound suggest to implement into CC0017 to change Explicit properties to public ones, which should be equivalent think.

**Comment by giggio** [comment]
Bug confirmed. We cannot change the property to public, that would change the meaning of the program. The correct way it to cast `this`, like so:

````csharp
class Foo : ITranslucent
{
    float ITranslucent.Alpha { get; set; }

    public Foo()
    {
        ((ITranslucent)this).Alpha = 0.0f;
    }
}
````
