### ISSUE TITLE
BUG: CC0048 (string interpolation) when string is split into multiple lines

### ISSUE THREAD

**Issue by jakubsuchybio** [code-cracker/code-cracker#689]
Hi.
These 2 examples translates into unbuildable code with CC0048 (Use string interpolation):
```c#
			var foo = 1;
			var goo = string.Format( "{0}", foo == 2 ?
				10 : 15 );

			var baz = string.Format( "{0}", foo +
				"baz" +
				"boo" );
```
They create interpolated strings over multiple lines, which compiler doesn't like.

Easy fix is to add ' @ ' between ' $ ' and ' " ' in these cases, which tells compiler that the string is split into multiple lines.

**Comment by giggio** [comment]
Bug confirmed, I will fix it, as I created the analyzer and fix.

**Comment by giggio** [comment]
@jakubsuchybio I decided to place the expression on the same line, removing the line breaks. Adding the `@` could be dangerous, we'd have to escape all `"`, and that is very error prone. See #692 for an example.
