### ISSUE TITLE
Bug: CC0048 nested interpolations doesn't fix in one iteration

### ISSUE THREAD

**Issue by jakubsuchybio** [code-cracker/code-cracker#690]
Hi.
When I have nested string.Format , then applying CC0048 will only solve first or selected one of them.
For example on this code:
```c#
var foo = string.Format( "{0}", string.Format( "{0}", 1 ) );
```
It will fix only one of them in one go. I think it would be good to solve them all at once.

Edit: Sorry I forgot to mention by using FixAll in Solution it will only fix one of them instead of both. 
When those string.Formats are concatenated they are fixed correctly. Like in here:
```c#
var foo = string.Format( "{0}", 1 ) + string.Format( "{0}", 1 );
```

**Comment by giggio** [comment]
@jakubsuchybio The code fixes only work on the current state of the code. To be able to do that, we would need to iterate:

1. Change the code
2. Recompile
3. Check for new diagnostics, and if found on the same node, go back to 1, else end.

This problem affects all code fixes. The "make static" one, for example, is another one. When you make a method static, probably other methods that used to call it as instance, and are now calling it as a class method, can also be made static. So, if you fix all, at the end, you will still have methods that can be made static.

I don't think this is something CodeCracker should fix. But if we would, we would need a way to solve it for all, create a more generic way to do it.

@code-cracker/owners what do you think?

**Comment by carloscds** [comment]
@jakubsuchybio @giggio The problem is about find all occurrences of string.Format(), maybe a chage in document fixer can be solve this.

**Comment by giggio** [comment]
@carloscds No, the problem is that it takes more than one iteration to fix it.

**Comment by carloscds** [comment]
@giggio Why diagnostic can't get all string.formats ?

**Comment by jakubsuchybio** [comment]
Listing in 'Error list' gets them all, but when applied Solution wide Fix it just doesn't fix those nested ones.

**Comment by giggio** [comment]
Hm... if they all appear on the error list, then we CAN fix them all. We just need to add a fix all provider, if we don't yet have one.
