### ISSUE TITLE
BUG: CC00091 Method `GetEnumerator` should never be made static

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#696]
If a method is named `GetEnumerator`  and returns an `IEnumerator` it should not be made static.  If it was changed you could break existing `foreach`s. See reference [on MSDN](https://msdn.microsoft.com/library/65zzykke%28v=vs.100%29.aspx);

Example:

````
class MyList
{
    public System.Collections.IEnumerator GetEnumerator()
    {
        yield return "x";
        yield return "y";
    }
}
````

**Comment by Vossekop** [comment]
I'll fix this one if you want!

**Comment by giggio** [comment]
Go for it. I'll add you to the collaborators group. You will be getting an email from github, let me know when you got it.

**Comment by Vossekop** [comment]
Got the mail, and clicked the link and all. Promptly screwed up my own fork as well... I'm still getting used to this Git stuff, give me TFVC any time.
