### ISSUE TITLE
BUG: CC0006 (foreach) edge case for non-writable struct field

### ISSUE THREAD

**Issue by jakubsuchybio** [code-cracker/code-cracker#698]
Hi.
So I found another one. But this one is interesting.
Here is a repro code: (tested with 1.0.0-rc5-1063)
```c#
		struct Foo
		{
			public int X;
		}

		static void Goo()
		{
			var array = new Foo[1];
			for( int i = 0; i < array.Length; i++ )
			{
				var actual = array[i];
				array[i].X = 5;
			}
		}
```
Here this flags for with CC0006 to convert it to foreach, but when it does then its uncompileable, because of writing into struct temp var doesn't work.

But when you delete the line with
```c#
var actual = array[i];
```
Then it works ok and doesn't flag it.

So I think that it doesn't matter to look for local var assignment of indexed array, when for is dealing with struct foreach temp variable.

Also, fix for lists and other enumerables. For example:

````csharp
var list = new List<Foo>();
for (int i = 0; i < list.Count; i++)
{
    var actual = list[i];
    actual.X = 5;
}
````

**Comment by giggio** [comment]
Bug confirmed, it should not raise a diagnostic.
