### ISSUE TITLE
BUG: CC0017 (create auto property) removing modifiers (static, virtual, etc)

### ISSUE THREAD

**Issue by jakubsuchybio** [code-cracker/code-cracker#699]
Hi.
When I have static field with property and trying to fix it with CC0017 to auto-property, it removes static which breaks referenced calls.
Repro code: (tested with 1.0.0-rc5-1063)
```c#
		class FileManager
		{
			private static string _filePath = "";
			public static string FilePath
			{
				get
				{
					return _filePath;
				}
				set
				{
					_filePath = value;
				}
			}
		}

		static void Foo2()
		{
			var path = FileManager.FilePath;
		}
```
Translates into:
```c#
		class FileManager
		{
			public string FilePath { get; set; } = "";
		}

		static void Foo2()
		{
			var path = FileManager.FilePath;
		}
```
Which doesn't compile.
Regards.

**Comment by giggio** [comment]
Bug confirmed. It should keep the property static, like this:

````csharp
class FileManager
{
    public string FilePath { get; set; } = "";
}
````

**Comment by giggio** [comment]
I just confirmed that it is removing all modifiers. I think that entered with the last bug fix I added yesterday.
