### ISSUE TITLE
BUG: CC0052 (readonly) flags field that is used in variable initializer, which then gives compile error

### ISSUE THREAD

**Issue by jakubsuchybio** [code-cracker/code-cracker#700]
Hi.
Here is a repro code:
```c#
		class A
		{
			public int X;

			public A()
			{
				X = 5;
			}
		}

		static void B()
		{
			var c = new A { X = 7 };
		}
```
Translates into:
```c#
		class A
		{
			public readonly int X;

			public A()
			{
				X = 5;
			}
		}

		static void B()
		{
			var c = new A { X = 7 };
		}
```
Which gives error:
Error CS0191 A readonly field cannot be assigned to (except in a constructor or a variable initializer)

So I don't know if there is bug in compiler or in CC0052. Because what I can say from this error is that this code should be valid after fix from CC0052. :/

**Comment by giggio** [comment]
Bug confirmed, it should not be raised for public fields.

**Comment by adraut** [comment]
I am working this.
