### ISSUE TITLE
CC0057: extern method parameter unused

### ISSUE THREAD

**Issue by huoyaoyuan** [code-cracker/code-cracker#701]
```C#
[DllImport("wininet.dll", SetLastError = true)]
public static extern bool InternetSetOption(IntPtr hInternet, int dwOption, IntPtr lpBuffer, int lpdwBufferLength);
```
This will get CC0057 on every parameter.
Confirmed using vsix 1.0.0.14

**Comment by carloscds** [comment]
@huoyaoyuan I can't repro using last version and this code:

`````csharp
public class foo
    {
        [DllImport("wininet.dll", SetLastError = true)]
        public static extern bool InternetSetOption(IntPtr hInternet, int dwOption, IntPtr lpBuffer, int lpdwBufferLength);
    }
`````

**Comment by huoyaoyuan** [comment]
@carloscds The nuget version cannot repro, but vsix version can.

**Comment by carloscds** [comment]
@huoyaoyuan Bug confirmed, only in VSIX.

**Comment by carloscds** [comment]
@huoyaoyuan Can you test again ?

**Comment by huoyaoyuan** [comment]
@carloscds I'd like to test it next time, because I use nuget version mainly and I don't have my own build.

**Comment by carloscds** [comment]
@huoyaoyuan Thanks for your contribution with project !
