### ISSUE TITLE
Add `developmentDependency` to nuspec

### ISSUE THREAD

**Issue by haroldhues** [code-cracker/code-cracker#706]
Per https://docs.nuget.org/create/nuspec-reference there is a `developmentDependency` value that I think applies to code-cracker.

> v2.8 A Boolean value that specifies whether the package will be marked as a development-only dependency in the packages.config. This will cause the package to be excluded from the dependency list when the referencing project itself is later packaged.

Should be as simple as adding a line in the *.nuspec file
```
    <developmentDependency>true</developmentDependency>
```

**Comment by giggio** [comment]
@haroldhues Is there a specific reason you need this? When you compile as release, any libraries that you are not using are removed from the dll/exe, so, unless you reference CodeCracker directly, you won't ever get a reference to it on the compiled output.

Anyway, we will check to make sure. Thank you you for bringing this to our attention.

**Comment by haroldhues** [comment]
This flag has to do with how NuGet handles dependencies. When I tried to package my project (as a NuGet package) using something like `nuget pack MyProj.csproj` NuGet failed with an error like:

> A stable release of a package should not have on a prerelease dependency.

Where code-cracker was listed, after some research I changed this line in packages.config

```
  <package id="codecracker.CSharp" version="1.0.0-rc5" targetFramework="net461"/>
```

to 

```
  <package id="codecracker.CSharp" version="1.0.0-rc5" targetFramework="net461" developmentDependency="true" />
```

At that point the error went away. I was curious about why some of my other packages (like Fody) already had the tag. That lead me to the above document, so I thought I would let you guys know :)

**Comment by giggio** [comment]
Makes sense!

**Comment by giggio** [comment]
Ok, we are about to release a stable version, this should solve your problem.
Let's wait for a conclusion from the Roslyn team on https://github.com/dotnet/roslyn/issues/9311.

**Comment by giggio** [comment]
This is being worked now on #829.
