### ISSUE TITLE
False "unused parameter" report

### ISSUE THREAD

**Issue by wmjordan** [code-cracker/code-cracker#708]
DLL import functions should not trigger CC0057.
For instance, `b1`, `b2` and `count` inappropriately triggered CC0057 in the following code:

    [DllImport ("msvcrt.dll", CallingConvention = CallingConvention.Cdecl)]
    internal static extern unsafe int memcmp (byte* b1, byte* b2, int count);

**Comment by carloscds** [comment]
@wmjordan Did you test with last version ?

**Comment by wmjordan** [comment]
Yes, version 1.0.0.14.

**Comment by carloscds** [comment]
@wmjordan It was correct in this commit: https://github.com/code-cracker/code-cracker/commit/bb585e29b90e5ca753f3d974a71722644a55ba63

**Comment by wmjordan** [comment]
It appeared that it had been fixed.

**Comment by giggio** [comment]
Yes, this is a duplicate of #701. It is not yet published to the extension gallery.
