### ISSUE TITLE
Please make CC0031 a little bit smarter

### ISSUE THREAD

**Issue by wmjordan** [code-cracker/code-cracker#709]
We are sharing code with some other developers who are still using VS 2013 or earlier, so the ?.Invoke pattern could not be applied.
The following code shall not issue CC0031 since `null` has been checked:

    var button = new MyButton();
    var c = button.Click;
    if (c != null) { // calls Click event handler
        c (button, new EventArgs());
    }

**Comment by giggio** [comment]
@wmjordan This is already being checked. See on line:

````csharp
context.RegisterSyntaxNodeAction(LanguageVersion.CSharp6, Analyzer, SyntaxKind.InvocationExpression);
````

To enable that to work on your VS 2015 you have to change the C# language version you are using. Go to `Properties > Build > Advanced` and change `Language Version` to C# 5.
We are aware of the problem for the null check. This will probably work on a merge from CC0031 and CC0016. See #662 for a fup.
