### ISSUE TITLE
BUG: CC0033 (DisposableFieldNotDisposed) Should ignore static field

### ISSUE THREAD

**Issue by wmjordan** [code-cracker/code-cracker#710]
Please take a look at this example:

   static class GuidGenerator {
        static readonly RNGCryptoServiceProvider _rng = new RNGCryptoServiceProvider ();
   }

The static field once created, will never be disposed until the process quits. Should the above code trigger CC0033?

**Comment by giggio** [comment]
No, it is a bug.
