### ISSUE TITLE
Please suppress CC0057 in template method pattern

### ISSUE THREAD

**Issue by wmjordan** [code-cracker/code-cracker#716]
In the following code, the Method `CheckConfiguration` serves as an empty template method.

   interface IConfigurableJobRunner {
     bool CheckConfiguration(Configuration config);
     void Run ();
   }

   public abstract RunnerBase : IConfigurableJobRunner {
      public virtual bool CheckConfiguration (Configuration config) { return false; }
      public abstract Run ();
   }

The `RunnerBase` class makes the `CheckConfiguration` an optional method to its sub-classes.
In this case, I think CC0057 should not be triggered, if the following two conditions are met:
1. The method is virtual;
2. The method implements a method defined in an interface.

**Comment by carloscds** [comment]
It's make sense. What do you think @code-cracker/owners  ?

**Comment by giggio** [comment]
I was not able to repro. I do not get `CC0057` with this code:

````csharp
    public class Configuration { }
    interface IConfigurableJobRunner
    {
        bool CheckConfiguration(Configuration config);
        void Run();
    }

    public abstract class RunnerBase : IConfigurableJobRunner
    {
        public virtual bool CheckConfiguration(Configuration config) { return false; }
        public abstract void Run();
    }
````

I am closing the issue. If you can find a repro we will happily reopen.

**Comment by wmjordan** [comment]
The above code triggered CC0057 improperly on the virtual `Get` method of class `A`.

````csharp
abstract class A
{
	internal virtual string Get(string index) { return null; }
}
class C : A
{
	Dictionary<string, string> _values = new Dictionary<string, string> ();
	internal override string Get (string index) {
		return _values[index];
	}
}
````

**Comment by giggio** [comment]
Right now only `partial`, `override`,  `abstract` and `extern` modifiers make the exclusion list. Should we do the same for `virtual`? I am not really sure, template method is an exception to the more common case.
And we cannot simply search the whole project for other classes overriding the method, that would make the analyzer unusable.
I think that, for this scenarios, the user should suppress the analyzer. What do you think, @code-cracker/collaborators and @code-cracker/core?

**Comment by thomaslevesque** [comment]
> Should we do the same for virtual?

I think so. If a method is virtual, the parameter might be used in overriding methods.

FWIW, ReSharper never emits a warning for unused parameters unless the method is private.
