### ISSUE TITLE
BUG: CC0090 (xmldoc) is raised on generated files

### ISSUE THREAD

**Issue by k94ll13nn3** [code-cracker/code-cracker#720]
XmlDocumentationAnalyzer (0090) is raised on generated file, particularly the `GeneratedInternalTypeHelper.g.i.cs` in my case, it may be missing the generated file check.

I am using the latest version of the Code Cracker Extension.

I was able to reproduce the problem by using [this sample](https://github.com/PrismLibrary/Prism-Samples-Wpf/tree/master/InteractivityQuickstart) from the Prism samples.

**Comment by giggio** [comment]
Bug confirmed, I will work on it.
