### ISSUE TITLE
BUG: CC0013 (Make Ternary) doesn't handle comments correctly

### ISSUE THREAD

**Issue by kwhitefoot** [code-cracker/code-cracker#725]
#Bug

Fix for ternary puts all the code on one line and this results in comments that were within the if turning the whole expression into a comment.

I think it would be better if the ternary expression placed the condition on one line and the return values on separate lines below it.

````vbnet
  Function s() As Boolean
    If True Then
      ' a comment
      Return False
    Else
      Return True
    End If
  End Function
````

Current output after fix applied (it is a code fix bug):

````vbnet
'code fixed incorrectly
Function s1() As Boolean
    ' a comment    Return If(True, False, True)
  End Function
````

Expected output after fix applied (if it is a code fix bug):

````vbnet
'code fixed correctly
Function s1() As Boolean
    ' a comment    
    Return If(True, False, True)
  End Function

````

**Comment by giggio** [comment]
Bug confirmed.
