### ISSUE TITLE
Using code-cracker outside Visual Studio

### ISSUE THREAD

**Issue by elvisdelima** [code-cracker/code-cracker#727]
Is there a way to use code-cracker without Visual Studio?
I work on linux, coding on VSCode and It would be great do something like "codecracker run" at my terminal and get this:

/***** output *****/

MyWebApp/FooController.cs at line 79
CC0043: ChangeAnyToAllAnalyzer - Changes Any to All or All to Any.

MyWebApp/BarController.cs at line 66
CC0011: RemoveWhereWhenItIsPossibleAnalyzer - When a linq operator support a predicate parameter it should be used instead of using ‘Where’ followed by the operator.

/******************/

**Comment by carloscds** [comment]
@elvisdelima You can use in command line.

**Comment by elvisdelima** [comment]
@carloscds thanks.
