### ISSUE TITLE
Code fix for CC0075 could break the logic of the code

### ISSUE THREAD

**Issue by wmjordan** [code-cracker/code-cracker#740]
Please take a look at the following code:

	if (s != null && s.Length > 0) {
		if (l.Count == 0 || l[l.Count - 1] != s) {
			// ...
		}
	}

The code fix will merge the two conditional statement into 

	s != null && s.Length > 0 && l.Count == 0 || l[l.Count - 1] != s

which will break the logic of the code since `&&` operator has higher precedency over `||`.
The correct code fix should be:

	s != null && s.Length > 0 && (l.Count == 0 || l[l.Count - 1] != s)

**Comment by giggio** [comment]
Bug confirmed. And we should only add the extra parenthesis when necessary.
Docs: https://msdn.microsoft.com/en-us/library/ms173145.aspx
As we are applying the `&&` operator, this means that not only the conditional OR `||` has less precedence, but also:
* Null coalescing: `??`
* Conditional: `x ? y : z`
