### ISSUE TITLE
CC0014 Use ternary tries to DirectCast integer to double

### ISSUE THREAD

**Issue by kwhitefoot** [code-cracker/code-cracker#745]
#Bug

````vb.net
  if condition then
    return aDouble
  else
    return bInteger
  end if
````

Current output after fix applied (if it is a code fix bug):

````vb.net
  return If(condition, aDouble, DirectCast(bInteger,Double))
````

Expected output after fix applied (if it is a code fix bug):

````vb.net
  return If(condition, aDouble, bInteger)
````

**Comment by giggio** [comment]
Here is the spec to conversions for VB:
https://github.com/ljw1004/vbspec/blob/gh-pages/vb/conversions.md#numeric-conversions
