### ISSUE TITLE
CC0030 incorrectly marks declaration and assignment of reference type as possible const

### ISSUE THREAD

**Issue by kwhitefoot** [code-cracker/code-cracker#749]
#Bug

````vb.net
    dim x as SomeClass = Nothing
    DoSomeThingWith(x)
   ...
   Sub DoSomeThingWith(ByRef p as SomeClass)
     ...
````

Current output after fix applied.

````vb.net
    const x as someclass = Nothing
    DoSomeThingWith(x)
   ...
   Sub DoSomeThingWith(ByRef p as SomeClass)
     ...
````

ByRef is used here because it is the nearest thing that VB has to an Out parameter, that is DoSomeThingWith is probably going to modify the reference so that it is no longer nothing.

The fix should not be offered in this case because it is not possible to tell at this point whether or not x really is constant and because it most likely is not.

**Comment by giggio** [comment]
I just tried your code, and could not repro. I also tried this code:

````vb.net
Class Foooo
    Sub Foo()
        Dim x As Integer = 1
        DoSomeThingWith(x)
    End Sub
    Sub DoSomeThingWith(ByRef p As Integer)
        p = Nothing
    End Sub
End Class
````

It also does not repro. If I remove the method call, only then, is the code fix offered and the diagnostic raised, so we are checking for this byref argument.
Also, if `x` is typed as a reference type (a class), it will not show up, even if the method call is not there.

Please post some code that we can repro. I am closing the issue by now, but fell free to reopen it with an example we can use to repro.

**Comment by kwhitefoot** [comment]
Very strange.  I must have made a mistake when I sanitised the code.  If it turns up again I'll be more careful and also check the sanitised code to make sure it properly represents what I saw in the real code.
