### ISSUE TITLE
CC0011 incorrect when Where predicate uses index parameter

### ISSUE THREAD

**Issue by RachelDavids** [code-cracker/code-cracker#752]
#Bug

CC0011 incorrectly suggests that the Where, in the code below, can be replaced by Any. There is no Enumerable.Any extension which supports the index parameter to the predicate.

```
IList<int> first = Enumerable.Range(1, 10).ToList();
IEnumerable<int> second = Enumerable.Range(1, 10);
bool isNotMatch = second.Where((t, i) => first[i] != t).Any();
```

The related CodeFix performs as expected, but leaves the code in an un-usable state 

```
IList<int> first = Enumerable.Range(1, 10).ToList();
IEnumerable<int> second = Enumerable.Range(1, 10);
bool isNotMatch = second.Any((t, i) => first[i] != t);
```

**Comment by giggio** [comment]
Bug confirmed, we should not raise a diagnostic in this case.
