### ISSUE TITLE
Remove Unnecessary ToString in String Concatenation

### ISSUE THREAD

**Issue by wmjordan** [code-cracker/code-cracker#753]
The runtime automatically calls `ToString` for string concatenation operations.

For instance, the `ToString` is unnecessary in the following code:

````csharp
 var foo = "a" + new object().ToString();
````

It should become:

````csharp
 var foo = "a" + new object();
````

Should also mark the `.ToString()` invocation with `WellKnownDiagnosticTags.Unnecessary`.

Category: `Style`
Diagnostic Id: `CC0118`
Severity: `Info`

**Comment by lazarofl** [comment]
Hello @giggio, I'm working in this issue.

I'm using __UnnecessaryToStringInStringConcatenationAnalyzer__  and __UnnecessaryToStringInStringConcatenationCodeFixProvider__.

They are missing some tests yet.

**Comment by giggio** [comment]
@lazarofl the name is fine. Go ahead!
