### ISSUE TITLE
CC0068 (Remove private method): ShouldSerializeXXX() and ResetXXX() should not trigger the message

### ISSUE THREAD

**Issue by LoRdPMN** [code-cracker/code-cracker#762]
To define complex default values for properties that will be serialized by the windows forms designers (and others serializers, like XmlSerializer), one can create a ShouldSerializeXXX() and/or a ResetXXX(), being XXX the property name, as stated by this MSDN article: [Defining Default Values with the ShouldSerialize and Reset Methods](https://msdn.microsoft.com/en-us/library/53b8022e%28v=vs.110%29.aspx)

That is not specified explicitly on the article, but because the serializers uses reflection, you can declare those methods private to not change your public API. When doing so, #CC0068 will trigger, which IMO is a false-positive.

Code sample:

``` csharp
public LineStyle Style {
    get;
    set;
}

private bool ShouldSerializeStyle() {
    return Style != null && Style.DashStyle != DashStyle.Solid && Math.Abs(Style.LineWidth - 1f) > 0.001f && Style.LineAlignment != PenAlignment.Center;
}
private void ResetStyle() {
    Style = new LineStyle();
}
```

PS.: Sorry for my bad English, it is not my native language.

**Comment by giggio** [comment]
@LoRdPMN You make these methods public, right? If so, I'd say that this is better. In the article you linked they used public properties.

**Comment by LoRdPMN** [comment]
@giggio The properties should be public, but the methods can be private, imagine a class that have many properties with complex types that can not be declared using the DefaultValueAttribute, if you make those methods public, you will pollute the class model, and a ShouldSerializeXXX method is not useful to user of a public API, except to serializers.

It is like when you MUST declare a parameterless constructor to a class be serializable and that constructor can be private, as you could not want normal users to use it, only the serializer when recreating the object.

**Comment by giggio** [comment]
Ok, as this is an official part of the .NET Framework, I think we should support it.
I will make it an enhancement on that analyzer.
