### ISSUE TITLE
CC0057 Fails with ByRef parameter

### ISSUE THREAD

**Issue by kwhitefoot** [code-cracker/code-cracker#768]
#Bug

Diagnostic identifies an unused ByRef parameter but the fix fails and Visual Studio disables it.

````vb.net
Public Sub X(ByRef y as String)

````

**Comment by giggio** [comment]
I just tested and it worked:

![cc0057](https://cloud.githubusercontent.com/assets/334958/14584102/3ff22f0a-040d-11e6-932e-140bc70d1a7b.png)

Did you try it with 1.0?
I am closing it by now, @kwhitefoot. If you can confirm the bug, please post an example we can try.

**Comment by kwhitefoot** [comment]
@giggio I have Code Cracker 1.0.0.15 installed.  

I've checked again and I can't reproduce it either but I don't know why.  

When I reported the bug I was using VS2015 Update 1, now I'm using Update 2

What is the simplest way to install the latest development version (I have zero experience of creating Visual Studio Extensions)?  Is there a guide somewhere?

**Comment by giggio** [comment]
You simply need to install the VS SDK. The standard setup should offer you this option, if you did not do it when you installed VS you can always go to installed programs, ask to change, and then add the SDK.
Then git clone the `master` branch. VS can help you with that too.
Set the .vsix project as the startup project, and run! :)
