### ISSUE TITLE
Code fix for naming conventions

### ISSUE THREAD

**Issue by wmjordan** [code-cracker/code-cracker#772]
#New analyzer:

Sometimes I had to cope with other programmers' project from out sourcing partners. They suck at naming conventions, for instance, the use PascalCase parameter names, SNALE_CASE method names or constants, etc. in the public members.
There is little possibility for them to change their style or continue to maintain their code. I wanna fix them, but there are too much of these types of bad styles.
Is it possible to fix them with Code-Cracker?

Before:

````csharp
private const string _NAME = "APP";
public const int IMPORTANT = -1;
private string m_numberPattern = @"\d+";
public void MY_METHOD (XmlDocument ParentDocument, string xpath_expression) {}
````

After:

````csharp
private const string _Name = "APP";
public const int Important = -1; // changing all UPPERCASE to TitleCase
private string _numberPattern = @"\d+"; // removing the m of the C++ programming style
public void MyMethod (XmlDocument parentDocument, string xpathExpression) {} // changing SNALE_CASE to Pascal case of method naming, using camalCasing for parameters
````

**Comment by jwooley** [comment]
Many of these kinds of analyzers are already included in the [StyleCop Analyzers](https://github.com/DotNetAnalyzers/StyleCopAnalyzers) and available on [nuget](https://www.nuget.org/packages/StyleCop.Analyzers/). I'm not sure that we need to redo @sharwell's work again here.

**Comment by wmjordan** [comment]
Oops, I searched the VS gallery but did not found @sharwell 's work.
I did not realized that it could be on the NuGet.

**Comment by giggio** [comment]
Also, the Roslyn team is implementing some of those style fixers on their own analyzers. It is already available on VS 2015 Update 2.
