### ISSUE TITLE
Auto generated files detection

### ISSUE THREAD

**Issue by kindermannhubert** [code-cracker/code-cracker#773]
Could you please update your detection of "auto-generated" comment to be same as [StyleCopAnalyzers](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCop.Analyzers/GeneratedCodeAnalysisExtensions.cs) have?
We started using CodeCracker side by side with StyleCopAnalyzers, but CC detects "auto-generated" comments more strictly and some of our auto-generated files are not detected as auto-generated.

**Comment by carloscds** [comment]
@kindermannhubert Can you put as code sample ?

**Comment by kindermannhubert** [comment]
For clarity I write the line numbers too.

Now it will be detected by CC as auto-generated here:
```C#
1: //
2: // <auto-generated>
3: using System;
```

but not here:
```C#
1: // <auto-generated>
2: using System;
```

StyleCopAnalyzers detects both version as auto-generated.

**Comment by giggio** [comment]
@kindermannhubert It is actually checking for the second line.
What do you suggest? It would not be nice to go scanning the whole file for this comment, it would hurt performance. Would it be enough for you to check the 1st and 2nd lines?
Also, what tool is auto generating using this pattern (I'm curious)?

**Comment by kindermannhubert** [comment]
StyleCopAnalyzers goes through all comment lines at start of file.
See:
```C#
 var comments = trivia.Where(t => t.IsKind(SyntaxKind.SingleLineCommentTrivia) || t.IsKind(SyntaxKind.MultiLineCommentTrivia)); 
             return comments.Any(t => 
             { 
                 string s = t.ToString(); 
                 return s.Contains("<auto-generated") || s.Contains("<autogenerated"); 
             }); 
```
where 'trivia' is leading trivia of first token. I think it is enough.

@giggio 
> Also, what tool is auto generating using this pattern (I'm curious)?

We have lot of custom auto-generated files from T4 and we place the aut-generated tag at the first line.

**Comment by giggio** [comment]
Ok, the suggestion to go through all the trivia makes sense.
