### ISSUE TITLE
BUG: CC0030 should not try to make a pointer const

### ISSUE THREAD

**Issue by kindermannhubert** [code-cracker/code-cracker#774]
Fix does not work for 'const' pointers.
![cc0030](https://cloud.githubusercontent.com/assets/11704036/14527393/e5491f2e-0249-11e6-98f5-fd0e586e534d.png)

**Comment by carloscds** [comment]
@kindermannhubert I agree. We will fix.

**Comment by giggio** [comment]
@carloscds let's release this on 1.0.1, you can send a PR to the 1.0.x branch.

**Comment by giggio** [comment]
Closed on dfd5c39
