### ISSUE TITLE
BUG: CC0052 (Make readonly) should not be applied to complex value types

### ISSUE THREAD

**Issue by kindermannhubert** [code-cracker/code-cracker#775]
Fix of this analyzer can be really dangerous when used on non-primitive value types.
As CC0052 was already restricted only to private fields, maybe it should be restricted further just to reference types and primitive value types (another aspect of readonly complex value types is that it can harm performace because at each access to field whole struct must be loaded on stack).

Here's an example of code which will break after changing field 'myStruct' to readonly:

```c#
public class MyClass
{
    private MyStruct myStruct = default(MyStruct);

    public void Modify()
    {
        myStruct.Modify();
        Console.Write(myStruct.Value);
    }

    private struct MyStruct
    {
        public int Value;

        public void Modify()
        {
            Value++;
        }
    }
}

public class Program
{
    private static void Main(string[] args)
    {
        var myClass = new MyClass();
        for (int i = 0; i < 5; i++)
        {
            myClass.Modify();
        }
    }
}
```

When 'myStruct' is not readonly output of program will be:
12345

but after making it readonly the out will be following:
00000

Another common example could be using System.Threading.SpinLock (it just doesn't work if it is saved in readonly field).

So, `CC0052` should not be applied to complex value types. The above code should not raise `CC0052`. Instead, we will use a new diagnostic id: `CS0121`. The analyzer should be updated to use this new id. It should be on the same analyzer, a new one should not be created.

**Comment by carloscds** [comment]
@kindermannhubert Maybe we can change this fix to Hidden. What do you think @code-cracker/owners ?

**Comment by kindermannhubert** [comment]
@carloscds I believe it's not want we want to do. It would negatively affect usability of this analyzer. By default it would be only optional and if you want from it to be 'rule' it must be set to e.g. Warning (but you can't do this because of problems described higher (suppressing all these occurrences is not acceptable)).

In my opinion there are two ways we can solve it:
1. Use two different results - current one for reference types or primitive value types and Hidden for the rest (=complex value types). I've already used this kind of 'multi-result' analyzer and it works. It's simple but there is problem with manual overriding of analyzer's severity (it would project all possible results to the manually selected one).
2. Split analyzer to two separated ones. One would detect reference and primitive value types with current severity. The second one would detect the rest with Hidden severity. Probably the best solution.

If you want I can help.

**Comment by giggio** [comment]
I think we should split this into two analzyers. Sometimes the behavior described is exactly what we want, sometimes not.
I would imagine that usually it is not. So, this new analyzer should be disabled by default.
I will create another issue for this new analyzer. For `CC0052` let's just remove the diagnostic for complex value types.

**Comment by giggio** [comment]
Actually, we can simply add the new diagnostic to this same analyzer. I will update the description. It is easier.

**Comment by carloscds** [comment]
@kindermannhubert @giggio I agree.

**Comment by giggio** [comment]
Created #808 for the continuation (new analyzer).
