### ISSUE TITLE
BUG: CallExtensionMethodAsExtensionAnalyzer threw exception when project language was C# 5.0

### ISSUE THREAD

**Issue by wmjordan** [code-cracker/code-cracker#781]
After that I switched the project language from default to C# 5.0, Code-Cracker threw exception in the analyzer with error code AD0001.
The error occurred on an extension method.

> Analyzer CodeCracker.CSharp.Usage.CallExtensionMethodAsExtensionAnalyzer threw an exception of type System.ArgumentException
> Argument name: syntaxTrees

**Comment by giggio** [comment]
Bug confirmed. Working on it right now.

**Comment by giggio** [comment]
Closed on #782
