### ISSUE TITLE
Error of Build solution

### ISSUE THREAD

**Issue by Urameshi78** [code-cracker/code-cracker#787]
#Error 

Hey , I want to build your project so I clone it and Build it, but I have this error I m looking for a fix but I don't find the solution can you help me please ? (this error appear only for the CodeCracker.VisualBasic.sln project when I build it)

On  Error List window
Error : Extension 'CodeCracker.Vsix..5b99e64c-1418-4a06-990c-fd4cf01f1234' could not be found. Please make sure the extension has been installed. CodeCracker.Vsix	

On Output Window
5>------ Rebuild All started: Project: CodeCracker.Vsix, Configuration: Debug Any CPU ------
5>  CodeCracker.Vsix -> 
5>  CodeCracker.Vsix -> 
5>  Creating VSIX Container...
5>  CodeCracker.Vsix -> C:\Users\mmbarki\Desktop\refactoring\code-cracker\src\VisualBasic\CodeCracker.Vsix\bin\Debug\CodeCracker.VisualBasic.vsix
5>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\VSSDK\Microsoft.VsSDK.targets(655,5): error VSSDK1031: Extension 'CodeCracker.Vsix..5b99e64c-1418-4a06-990c-fd4cf01f1234' could not be found. Please make sure the extension has been installed.

**Comment by carloscds** [comment]
@Urameshi78 What is your VS version ?

**Comment by Urameshi78** [comment]
@carloscds  I have VS 2015 with Update 2

**Comment by carloscds** [comment]
@Urameshi78 Your problem seems problem with SDK, can you update it ?

**Comment by giggio** [comment]
This is a problem with VS, you have to try to clean the `Roslyn` instance. 

First close all VSs.

Try this in Powershell:

````powershell
. "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VSSDK\VisualStudioIntegration\Tools\Bin\CreateExpInstance.exe" /Clean /VSInstance=14.0 /RootSuffix=Roslyn
````

If it does not work, try to delete both `%appdata%\Microsoft\VisualStudio\14.0Roslyn` and `%localappdata%\Microsoft\VisualStudio\14.0Roslyn`, then run that Clear again, just to make sure.

Then try running the Roslyn instance before running it from VS.

Then open the Roslyn instance:

````powershell
devenv /rootsuffix Roslyn
````

This is a know problem, if you search for it you will find similar answers. It has nothing to do with CodeCracker, it is a VS problem.
