### ISSUE TITLE
cc0022 DisposableVariableNotDisposedAnalyzer

### ISSUE THREAD

**Issue by thiagomoreiraboby** [code-cracker/code-cracker#792]
Erro quando não esta dentro de chave. 
nao executa fica so pedindo para habilitar

````csharp
if (UsuaSetord.usse_codigo != null)
  new UsuaSetorClient(Funcaosistema.Bindinsihl, Funcaosistema.Endpointsihl).DeletarUsuaSetor(UsuaSetord);
````

**Comment by giggio** [comment]
@thiagomoreiraboby I can't repro. Tried this simpler one, it worked fine:

````csharp
class Foo
{
    public static void M()
    {
        if (true)
            new System.IO.MemoryStream();
    }
}
````

We need more details. I am closing this for now, but feel free to reopen with a case we can try to repro.
