### ISSUE TITLE
CC0061: Implementing interface using async

### ISSUE THREAD

**Issue by LoRdPMN** [code-cracker/code-cracker#793]
This is similar to #424 , but with interfaces.

When you try to implement some interface method using async/await pattern, CC0061 triggers incorrectly as you can't change the method name while still implementing the interface.
I would like to remember that async/await pattern is an implementation detail, you can use it while implementing any abstract base class or interfaces and sometimes you don't have access to the interface.

I had this issue implementing WPF `ICommand` to behave asynchronously (following this article: [Async Programming : Patterns for Asynchronous MVVM Applications: Commands](https://msdn.microsoft.com/en-us/magazine/dn630647.aspx))

Code:

```csharp
public class Bar : IBar // assume IBar is in another assembly that is not part of the project
{
    public Task Foo()
    {
        throw new NotImplementedException();
    }
}
```

It is acceptable to raise `CC0061` if the interface is also on source, not a referenced library.

PR should go into branch `v1.0.x.`

**Comment by giggio** [comment]
Bug confirmed, it is up for grabs.

**Comment by giggio** [comment]
@LoRdPMN I have updated the issue to add a simple example and also added more info.

**Comment by LoRdPMN** [comment]
@giggio IMHO I think it is not acceptable if the interface is on source, because you should be creating an API which the implementer should decide whether it will be implemented as async or not.

I agree with it in cases where the method is not implementing an interface and is not overriding an abstract method.

Also, if it triggers when the interface is on source, then the interface will need to force EVERY implementation to be async, which may not be intended.

Pick the `ICommand` as an example, if it was on source and had the method name changed to `ExecuteAsync`, and in another class, the implementer choose to implement without async/await (it's an implementation detail), then the name would be misleading.

**Comment by giggio** [comment]
@LoRdPMN A method is async not if it uses the `async` keyword, but if it follows the async pattern, which mostly involves returning a `Task`.
So, a method that does not have the keyword `async`, but still returns a `Task`, is still async.
Bear in mind that the async keyword only exists on source, there is way to tell that a method was async when looking at IL. We could, at the most, look for the state machine generated by Roslyn.
Still, to follow the current behavior with overriden method, it might probably be best to simply not raise the diagnostic. I am looking at it myself, and will post here with what I find.

**Comment by giggio** [comment]
Closed on #825.

**Comment by Portikus** [comment]
Hi @giggio,
It seems I encountered this bug. I have the same situation as described above with an ICommand. But I get a warning that I should change the name of Execute to ExecuteAsync which is impossible because it is declared in an Interface. 
I am using CodeCracker version 1.0.3 and Visual Studio 2017 version 15.1 (26403.7).

**Comment by giggio** [comment]
@Portikus I can't repro. Would you please share project that we can look at?

**Comment by Portikus** [comment]
Hi @giggio ofcorse I attached a repo solution [CodeCrackerBug.CC0061.zip](https://github.com/code-cracker/code-cracker/files/1073624/CodeCrackerBug.CC0061.zip).
Forgot to mention that it is a .NetSTandard project.

**Comment by giggio** [comment]
@Portikus You are correct, I created issue #936 detailing the bug a little more.
