### ISSUE TITLE
CC0057 : Unused parameters on extension methods

### ISSUE THREAD

**Issue by Cybermaxs** [code-cracker/code-cracker#794]
This is an open discussion but I think that CC0057 (remove unused parameters) should not be triggered on extension methods.
*sometimes*, we have to add extension methods to existing class, even if we don't use it. This a convenient method to get more coherence in client code.

````csharp
        public static string RenderFooBar(this HtmlHelper helper)
        {
            // do something without helper
            return "footbar";
        }
````

**Current output after fix applied (if it is a code fix bug)**

````csharp
        public static string RenderFooBar()
        {
            // do something without helper
            return "footbar";
        }
````
Please note that the project _won't compile_ after the code fix because RenderFooBar is no longer an extension method.

**Expected output after fix applied (if it is a code fix bug)**

````csharp
        public static string RenderFooBar(this HtmlHelper helper)
        {
            // do something without helper
            return "footbar";
        }
````

**Comment by wmjordan** [comment]
This may reflect a problem in your design, IMHO.
Could you please show us the typical usage and advantage of such an extension method?

**Comment by Cybermaxs** [comment]
True, but sometimes it's better to keep it coherent with common conventions.
In asp.net MVC, we generally create extension methods on HtmlHelper for 'everything that will generate Html'.
````
//csharp
     public static class LabelExtensions
     {
          public static string Label(this HtmlHelper helper, string target, string text)
          {
               return String.Format("<label for='{0}'>{1}</label>", target, text);

          }
     } 
//razor vew
 <%= Html.Label("firstName", "First Name:") %> 
````
But I think the general suggestion is more :: should it provide a fix that is useless and will break the code ?

**Comment by wmjordan** [comment]
The `HtmlHelper` example makes sense.

**Comment by giggio** [comment]
I agree, but this is an example where you should suppress it. I don't see a generic way for us to change the code analysis. Do you? In which cases should the diagnostic be triggered, and which cases should it not?
I am closing the issue, but if we can find a way to solve this, I will gladly reopen it.

**Comment by KristianWedberg** [comment]
I've also run in to this one due to 'existing practices'. 

How about not generate a warning if the unused parameter is the 'this' extension parameter? Or is that hard to find out?

**Comment by giggio** [comment]
@KristianWedberg It is not hard to find out, but as I said earlier, this is exactly the case where you suppress the analyzer directly in the source, that is what a suppression is for. ;)
