### ISSUE TITLE
CC0014 doesn't notice that subscripted properties have different subscripts

### ISSUE THREAD

**Issue by kwhitefoot** [code-cracker/code-cracker#801]
#Bug

CC0014 should not offer to fix when the variable that is the target of the assignment is different in the two branches of the if statement.

````vb.net
                If condition Then
                  a(3) = b
                Else
                  a(1) = b
                End If
````

Current output after fix applied (if it is a code fix bug):

````vb.net
                a(3) = If(condition, b,b)
````

**Comment by giggio** [comment]
Duplicate from #798.
