### ISSUE TITLE
BUG: CC0052 detection (ref/out parameters)

### ISSUE THREAD

**Issue by kindermannhubert** [code-cracker/code-cracker#802]
CC0052 - A field that is only assigned on the constructor can be made readonly.
Diagnostic should not be detected when field is used as 'ref' or 'out' parameter of method.

Example:
````csharp
    class Test
    {
        private int value = 4;

        public void Method()
        {
            int.TryParse("", out value);
        }
    }
````

**Comment by giggio** [comment]
Duplicate from #788.
