### ISSUE TITLE
BUG: CC0052 detection (property setters)

### ISSUE THREAD

**Issue by kindermannhubert** [code-cracker/code-cracker#803]
CC0052 - A field that is only assigned on the constructor can be made readonly.
Diagnostic should not be detected when field is set inside property setter.

I see this problem only when variable is set in constructor.

Here the diagnostic is correctly NOT detected:
Example:
```C#
    class Test
    {
        private int value = 7;

        public int Value
        {
            get { return value; }
            set { this.value = value; }
        }
    }
```

But here it is detected:
```C#
    class Test
    {
        private int value;

        public int Value
        {
            get { return value; }
            set { this.value = value; }
        }

        public Test()
        {
            value = 8;
        }
    }
```

**Comment by giggio** [comment]
The problem is not the property, is the order in which the constructor shows up. This does not raise the diagnostic:

````csharp
class Test
{
    public Test()
    {
        value = 8;
    }
    private int value;
    public int Value
    {
        get { return value; }
        set { this.value = value; }
    }
    public void Foo()
    {
        value = 1;
    }
}
````

And this does:

````csharp
class Test
{
    private int value;
    public int Value
    {
        get { return value; }
        set { this.value = value; }
    }
    public void Foo()
    {
        value = 1;
    }
    public Test()
    {
        value = 8;
    }
}
````

The only difference is the order in which the members appear. I will open another issue with this. By now, only change the order, bring the constructor up in the class and you should be fine.
