### ISSUE TITLE
Make readonly (for complex value types)

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#808]
Make complex value type readonly.

Before:

``` csharp
public class MyClass
{
    private MyStruct myStruct = default(MyStruct);
}
private struct MyStruct
{
    public int Value;
}
```

After:

``` csharp
public class MyClass
{
    private readonly MyStruct myStruct = default(MyStruct);
}
private struct MyStruct
{
    public int Value;
}
```

Diagnostic Id: `CC0121`
Category: `Usage`
Severity: `Info`

This analyzer should be disabled by default because of the problems described on #775. And it should share could, if possible, with the analyzer for `CC0052`. The code fix can be the same, for sure, and should only be updated to take `CC0121` as an extra id.

**Comment by cezarant** [comment]
"_This analyzer should be disabled_" 
Just set the isEnabledByDefault parameter to false that's enough?

**Comment by giggio** [comment]
@cezarant yes. Are you working on it?

**Comment by cezarant** [comment]
Yes @giggio  It seems to be a slight issue to start.

**Comment by giggio** [comment]
@cezarant Cool, let us know when you are ready, and send a PR!

**Comment by cezarant** [comment]
One question: If the analyser it's hidden or disabled,i need to implement tests for the  situations where he is enabled?
Because, i don't have found a analyser with condition "**enabledByDefault=false.**"

**Comment by giggio** [comment]
@cezarant We will enable the analyzer before we run the tests.
