### ISSUE TITLE
Provide Sonar Plugin

### ISSUE THREAD

**Issue by pascalberger** [code-cracker/code-cracker#811]
Do you plan to provide a plugin for SonarQube for this analyzer (See https://github.com/SonarSource-VisualStudio/sonarqube-roslyn-sdk/)? This would allow to use the analyzer in a CI scenario to manage technical dept with SonarQube, and also have it in Visual Studio through SonarLint.

For supporting Roselyn analyzers Sonar requires a plugin (as explained [here](https://blogs.msdn.microsoft.com/visualstudioalm/2016/02/18/sonarqube-scanner-for-msbuild-v2-0-released-support-for-third-party-roslyn-analyzers/)). The Sonar SDK automatizes most of this, it is just a matter of adding some metadata additionally.

The Sonar plugin could be created by the user, but it would be better if it would be maintained and provided by the official creator.

**Comment by giggio** [comment]
@pascalberger right now, no, we don't.
If we were to create this plugin, where would we publish it?

**Comment by pascalberger** [comment]
There exists the possibility to have plugins listed in the Sonar update center. See [here](http://docs.sonarqube.org/display/DEV/Deploying+to+Update+Center) how the process works.

**Comment by carloscds** [comment]
@pascalberger You can use Sonar Roslyn SDK to create a .jar file based on CodeCracker NugetPackage. You need on download SonarSDK (https://github.com/SonarSource-VisualStudio/sonarqube-roslyn-sdk/releases/download/1.0/SonarQube.Roslyn.SDK-1.0.zip) and run follow command line:
RoslynSonarQubePluginGenerator.exe /a:codecracker.CSharp /acceptLicenses
After this you need to install jar file into your SonarQube Server

**Comment by pascalberger** [comment]
@carloscds I'm aware of the possibility to create the plugin myself. But IMHO it would be much better to have done this by the original author instead of each user on its own, with each user requiring to add the additional metadata (effort for technical dept) and keep updated on new analyzers.

**Comment by carloscds** [comment]
@pascalberger We will discuss about generate a plugin for SonarQube, and after tis I will update this issue.

**Comment by giggio** [comment]
We have decided it is a good idea to publish the plugin, @carloscds will investigate the best way to do that, we will not add a binary to this repo, we have to find some other way.

**Comment by giggio** [comment]
Created Repo for this plugin at: https://github.com/code-cracker/SonarQubePlugin
Docs on how to submit a plugin do SonarSource: http://docs.sonarqube.org/display/DEV/Deploying+to+Update+Center

**Comment by giggio** [comment]
Release for the 1.0.0 created: https://github.com/code-cracker/SonarQubePlugin/releases/tag/v1.0.0
The .jar is already there. @carloscds will submit the plugin to SonarSource.

**Comment by giggio** [comment]
We are now one of SonarQube plugins. Only need to update readme, now: http://docs.sonarqube.org/display/PLUG/Other+Plugins

**Comment by giggio** [comment]
@carloscds I am reopening, as we did not yet update the readme.

**Comment by carloscds** [comment]
@giggio Ok, sorry!

**Comment by carloscds** [comment]
Readme updated.
