### ISSUE TITLE
CodeActions should have an ID

### ISSUE THREAD

**Issue by vbfox** [code-cracker/code-cracker#83]
There is something important in the last version of Roslyn for CodeFixes : The `id` passed to `CodeAction.Create`.

This `Id` is the indicator that the `FixAllProvider` (At least `WellKnownFixAllProviders.BatchFixer`) uses to trigger.

If it isn't specified like :
```C#
context.RegisterFix(CodeAction.Create("Use 'ConfigureAwait(false)'", 
    ct => AddConfigureAwait(context, diagnostic, ct, false)), diagnostic)
```

The code fix appear like that :

![Without](https://i.imgur.com/v6ctznw.png)

But if it is specified:
```C#
context.RegisterFix(CodeAction.Create("Use 'ConfigureAwait(false)'", 
    ct => AddConfigureAwait(context, diagnostic, ct, false), "KR.AddConfigureAwait.False"),
    diagnostic)
```

New options appear at the bottom:
![With](https://i.imgur.com/IxXCRjU.png)

I think that it should be fixed in all current fixes and mandatory for new ones.

Also when `WellKnownFixAllProviders.BatchFixer` works (Sometimes for complex code fixes it might create problems) all fixes should contain :

```C#
public override FixAllProvider GetFixAllProvider()
{
    return WellKnownFixAllProviders.BatchFixer;
}
``` 

It is especially important as this method can't be forgotten today (it's abstract in the base class) but it already changed in Roslyn master since [b272933fa0083e9d1c91df4e00c874ea82a8671f](https://roslyn.codeplex.com/SourceControl/changeset/b272933fa0083e9d1c91df4e00c874ea82a8671f) to be virtual and return `null` by default.

**Comment by giggio** [comment]
I have analyzed and confirmed that it is not necessary to have the diagnostic id on the code fix to enable the change on document, project or solution levels. Maybe this was something on beta1 that is now fixed on the new VS.
Also, all analyzers already use `WellKnownFixAllProviders.BatchFixer` when appropriate.
