### ISSUE TITLE
C++ is Coming?

### ISSUE THREAD

**Issue by feb21** [code-cracker/code-cracker#850]
+1

**Comment by jwooley** [comment]
While I appreciate the desire for more static analysis tools for C++, I don't think this project is the correct one. Since Roslyn is limited to C# and VB at this point and Code-cracker is a Roslyn powered tool, I don't see the benefit of doing a C++ version through this project.

**Comment by giggio** [comment]
Right. Until then, there is no way to support C++. I am closing the issue, unfortunately, because it would be really cool.

**Comment by feb21** [comment]
GGGGGGGGGGGGG
