### ISSUE TITLE
CC0089 should ignore if statements that include "else if" blocks

### ISSUE THREAD

**Issue by rezanid** [code-cracker/code-cracker#855]
When writing if statements that include `else if` blocks such as following:
````csharp
if (status == NotStarted)
{
  MonitorProgress();
}
else if (status == OnGoing)
{
  Logger.Log("Operation was already ongoing", severity: Warning);
  MonitorProgress(isAlreadyStarted: true);
}
````
It is a good practice to also include a final `else` block to indicate that all cases are covered. This can would help to clearly indicate the purpose of the code and when it is implemented in a project, lack of `else` can be a lead to find potential bugs. Unfortunately if we write the above code like this:
````csharp
if (status == NotStarted)
{
  MonitorProgress();
}
else if (status == OnGoing)
{
  Logger.Log("Operation was already ongoing", severity: Warning);
  MonitorProgress(isAlreadyStarted: true);
}
else {
  // else block intentionally left empty as there other possibilities that are not important in this case.
}
````

**CC0089 analyzer complains that the else block is redundant.**

**Comment by jwooley** [comment]
I'm not sure that forcing code to include a noop is a best practice. If we extended the logic here, one could contend that all if blocks should always have else blocks to indicate that both cases are covered even if there is no functionality in the else condition. I can understand the desire for this with a switch statement, but am not convinced that it is best practice for if.. else if.. else blocks.

**Comment by rezanid** [comment]
Why not? Could you elaborate more? I have seen this in many static code analysers already.



On Wed, Dec 7, 2016 at 4:18 PM +0100, "Jim Wooley" <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm not sure that forcing code to include a noop is a best practice. If we extended the logic here, one could contend that all if blocks should always have else blocks to indicate that both cases are covered even if there is no functionality in the else condition. I can understand the desire for this with a switch statement, but am not convinced that it is best practice for if.. else if.. else blocks.

-

**Comment by rezanid** [comment]
I think I understand your concern now. IMHO when we are righting a single `if` statement we are evaluating a condition that can be anything. In that case the necessity to include an `else` depends on what we are trying to achieve and it's not related to the readability or maintainability. but `if` statements that include `if else` are a different story. They are used to evaluate a list of possibilities. Those possibilities can be endless or not (it turns out most often they are not when we use `if else`). Including an extra `else` is the best way to indicate it. 
PS: VB/CS compiler easily gets rid of the noop when optimizing the code in compile-time. I think it's safe to assume that other modern compilers do the same too.

**Comment by GGG-KILLER** [comment]
@rezanid I believe this would be suited only for specific cases as many exceptions exist to it. Take for example a code that has an `enum` with 4 options:
```
enum Example
{
	None = 0,
	Flag1 = 1,
	Flag2 = 2,
	Flag3 = 4,
	All = Flag1 | Flag2 | Flag3
}
```

And it wanted to make different choices based on the flags set like:

```
var flag = Example.Flag1 | Example.Flag2;
if ( ( flag & ( Example.Flag1 | Example.Flag2 ) ) != 0 )
{
	// One of both is set
}
else if ( flag == Example.Flag3 )
{
	// Flag 3 is set
}
```

And the code was designed in a way that there'll never be any other possibilities rather than the ones covered by the `if/else if` statement, your new rule would make it so that they have to add an empty `else { }` that would be totally useless apart than following arbitrary code standards, which I believe is not the objective of this extension, but rather fix common code mistakes made by developers (such as not disposing objects, using if when a ternary operator is an option, using for instead of foreach, etc.)

**Comment by rezanid** [comment]
@GGG-KILLER In your example, you are using an `enum`. I assume that your `if` statement is not the only place in your application that this `enum` is being used. It can be used in other functions and even different classes (unless it's very specific scenario). Now imagine for a moment that a developer has joined the team to work on a specific bug and while chasing the leads she / he comes to this very spot. Now imaging if your code had been written like this:
````
var flag = Example.Flag1 | Example.Flag2;
if ( ( flag & ( Example.Flag1 | Example.Flag2 ) ) != 0 )
{
	// One of both is set
	Some code here.
}
else if ( flag == Example.Flag3 )
{
	// Flag 3 is set
	Some more code here
}
else
{
	// Due to the way application is designed there can be no other possibilities to cover.
}
````
If your "code is designed in a way that there'll never be any other possibilities rather than the ones covered by the `if / else if` statement". You can easily indicate it like above if would save your colleague or even you some time in the future. Even the design of the application changes in that case this can again be helpful. In fact everything can change! but we can either foresee the future and guess or indicate the intention of code as clear as possible. The only cases I personally do not favour clean code is when performance, resource usage or even any other important measurable factor is against it! that little `else` will be removed by the compiler as if it has never existed and it helps make your code become cleaner. but I fully agree with you that this can be made optional.

**Comment by GGG-KILLER** [comment]
@rezanid But fundamentally, in understanding, what would be the difference of this:
```
var flag = Example.Flag1 | Example.Flag2;
if ( ( flag & ( Example.Flag1 | Example.Flag2 ) ) != 0 )
{
	// One of both is set
	Some code here.
}
else if ( flag == Example.Flag3 )
{
	// Flag 3 is set
	Some more code here
}
else
{
	// Due to the way application is designed there can be no other possibilities to cover.
}
```

and this

```
var flag = Example.Flag1 | Example.Flag2;
if ( ( flag & ( Example.Flag1 | Example.Flag2 ) ) != 0 )
{
	// One of both is set
	Some code here.
}
else if ( flag == Example.Flag3 )
{
	// Flag 3 is set
	Some more code here
}
// Due to the way application is designed there can be no other possibilities to cover.
```

apart from the fact the former inserts a noop which is probably removed by compiler optimizations and attends to your coding standards?

My point is that there is no practical reason to have this as a feature of the extension, since it does not provide any actual functionality as the `replace type names for "var" on local variables` and the `do not leave empty "catch" clauses`, those are there because they have practical applications (no need to apply typing and preventing bad coding practices respectively, even though I tend to disagree with the latter).

**Comment by giggio** [comment]
I think this would add a lot of noise to the error list. It is so common that this is not needed that I don't think it is a good idea. `If else if` without a final `else` are just normal in code, I don't see it even as an info.
