### ISSUE TITLE
VS 2017RC Support

### ISSUE THREAD

**Issue by GGG-KILLER** [code-cracker/code-cracker#856]
Would it be possible to have support for VS 2017RC added to this extension? VS2015 will probably not get support for the upcoming .NET Core tooling suite that already ships with 2017 so .NET Core developers will have to move to 2017 as it uses a new MSBuild system (not available on 2015).

One of the biggest issues I have is not being able to use Code Cracker C# since it is not available to 2017RC.

**Comment by carloscds** [comment]
@GGG-KILLER In VS 2017 extensions was changed and we didn't update project yet.

**Comment by GGG-KILLER** [comment]
@carloscds I am aware of that, however I was asking if it is in the roadmap for the project to make it available for VS 2017RC.

**Comment by carloscds** [comment]
@GGG-KILLER Yes, we are upgrade to run on VS 2017.

**Comment by rfiori** [comment]
Oi @carloscds tudo joia ?
Como está a previsão para disponibilizar o Code-Cracker no VS2017 RC ?
Não consigo mais fica sem essa ferramenta.

Obrigado

**Comment by carloscds** [comment]
@rfiori Já estamos trabalhando nisto!

**Comment by giggio** [comment]
Closed on 7b21fbdd55ba90e2ccde1d3835ca698ef84660aa.
We will release to VS 2017 today.
