### ISSUE TITLE
CC0009 should ignore IDisposable types

### ISSUE THREAD

**Issue by Thieum** [code-cracker/code-cracker#857]
CC0008 should ignore IDisposable types as it will pop a CA2000 code analysis warning considering an initializer declares a temporary variable (see : http://haacked.com/archive/2013/01/11/hidden-pitfalls-with-object-initializers.aspx/ for more details)
Example: 

````csharp
public sealed class Owner : IDisposable
{
    Dependency dependency;

    public Owner()
    {
        dependency = new Dependency();
        dependency.SomeProperty = "Blah";
    }

    public void Dispose()
    {
        dependency.Dispose();
    }
}

public sealed class Dependency : IDisposable
{
    public string SomeProperty { get; set; }
        
    public void Dispose()
    {
    }
}

````

Current output after fix applied (if it is a code fix bug):

````csharp
public sealed class Owner : IDisposable
{
    Dependency dependency;

    public Owner()
    {
        // This is going to cause some issues.
        this.dependency = new Dependency { SomeProperty = "Blah" };
    }

    public void Dispose()
    {
        this.dependency.Dispose();
    }
}

public sealed class Dependency : IDisposable
{
    public string SomeProperty { get; set; }
        
    public void Dispose()
    {
    }
}

````

Expected output after fix applied (if it is a code fix bug):

````csharp
public sealed class Owner : IDisposable
{
    Dependency dependency;

    public Owner()
    {
        this.dependency = new Dependency();
        this.dependency.SomeProperty = "Blah";
    }

    public void Dispose()
    {
        this.dependency.Dispose();
    }
}

public sealed class Dependency : IDisposable
{
    public string SomeProperty { get; set; }
        
    public void Dispose()
    {
    }
}

````

**Comment by giggio** [comment]
@Thieum This no longer seems to be true. @haacked's post seems to be from 2013. This is the constructor for the `Owner` object now when using an initializer:

![image](https://cloud.githubusercontent.com/assets/334958/21744580/a477ae82-d4ff-11e6-8bce-38280c264116.png)

The problem he states on the blog post about the property setter throwing still exists, but the temporary local variable no longer exists.

Here is the same constructor without the initializer:

![image](https://cloud.githubusercontent.com/assets/334958/21744602/2eb9e6e6-d500-11e6-87d9-8afe7de0ef35.png)

The only difference you can see is that the field is stored before the property is set.

Concluding:
There is no intermediate variable in either scenario anymore.
The problem of the property throwing is still there.

We should actually create an analyzer that checks for those things in the constructor. That would be useful, as the other problem remains.

@haacked maybe you can update your article. :)

**Comment by Haacked** [comment]
Have you tried with a DEBUG build? I wonder if the debug and production compiled output differs. In any case, I may just link to this issue in my post. :smile:

**Comment by giggio** [comment]
@Haacked Yes, I did, no change there. That is good news, right? :)

**Comment by Haacked** [comment]
👍 Nice!
