### ISSUE TITLE
BUG: CC0060 - detected for nested struct in abstract class

### ISSUE THREAD

**Issue by kindermannhubert** [code-cracker/code-cracker#867]
Diagnostic ("Abstract class should not have public constructors") is incorrectly detected for nested struct in abstract class.

Example:
```c#
public abstract class C
{
    public struct S
    {
        private int x;

        public S(int x)
        {
            this.x = x;
        }
    }
}
```

**Comment by giggio** [comment]
Closed on 233cdf7474110d48144c0fe9083e37eca292386b, which cherry picked from #868.
