### ISSUE TITLE
BUG: CC0022 failed to show fix with null coalesce operator

### ISSUE THREAD

**Issue by sm-g** [code-cracker/code-cracker#870]
This line have warning at `new HttpClient(...)`:

````csharp
_httpClient = _httpClient ?? new HttpClient(...)
````

When trying to show fixes, `DisposableVariableNOtDisposedCodeFixProvider` failed.

Also, if [`HttpClient` should not be disposed](http://stackoverflow.com/a/15708633/3009578), maybe move such usage to Messages (along with `HttpClientHandler`)?

**Comment by giggio** [comment]
Bug confirmed.

**Comment by giggio** [comment]
Closed on #917.
