### ISSUE TITLE
Enable CodeCracker to work with .NET Core

### ISSUE THREAD

**Issue by BennieCopeland** [code-cracker/code-cracker#871]
When I build a .Net Core project (project.json/xproj) that includes the CodeCracker.CSharp nuget package (1.0.1), no code cracker results are reported. Additionally it prevents StyleCop.Analyzers results from reporting as well. I have not tested with other analyzers. I tried the following combinations of packages and the Visual Studio extension.

Project Type | CodeCracker.CSharp package | StyleCop.Analyzers package | CodeCracker Extension | Result
-- | - | - | - | -
.Net Core |  | X |  | StyleCop results reported
.Net Core | | X | X | StyleCope/CodeCracker results reported
.Net Core | X | X | | No results reported
.Net Core | X | | | No results reported
.Net Core | X | | X | CodeCracker results reported
.Net Core | X | X | X | CodeCracker results reported

Doing the same testing with a standard .Net 4.6 cproj produces the expected results without blocking StyleCop and without requiring the extension.

I'm running Visual Studio 2015 Update 3 with the .NET Core 1.1 SDK and Visual Studio 2015 Tools (Preview 2).

**Comment by carloscds** [comment]
@BennieCopeland CodeCracker it not compatible with .Net Core yet.

**Comment by walter-lopes** [comment]
Coders,  

Code Cracker Is not compatible with .NET Core yet ?

**Comment by carloscds** [comment]
@walter-lopes Not yet.

**Comment by pgrm** [comment]
@carloscds really? - We're using it with .net core on jenkins on a ubuntu machine and I think it was working fine ...

**Comment by carloscds** [comment]
@walter-lopes Sure ? Thanks for sharing this! I will do some tests on .Net Core. Are you using with VSIX or Nuget ?

**Comment by giggio** [comment]
It is, I just tried. It works with msbuild based projects without any problems, both as a Nuget reference, and as a vsix on VS directly. We do not support xproj/project.json, as that was preview tooling.
