### ISSUE TITLE
 CC0057 UnusedParametersAnalyzer should not be triggered on virtual methods

### ISSUE THREAD

**Issue by StefanTheiner** [code-cracker/code-cracker#872]
## Description

CC0057 gets triggered on virtual methods. In my opinion virtual methods don't need to use all the parameters available in the base class implementation, because the parameters serve just as interface for future extensibility in subclasses.

## Example: 

In my case the virtual method is just a dummy implementation that doesn't perform anything at all. Subclasses however might override the method and actually use the parameter.

````csharp
internal abstract class BaseClass
{

  // ...

  protected virtual void PreProcess(MyDataStructure ds)
  {
     // base implementation: don't do anything. Subclasses might override the method and implement custom behavior
  }
}
````

### Current output:

Warning CC0057 "UnusedParametersAnalyzer": Parameter "ds" not used.

### Expected output:

Occurrence should be ignored, because method is virtual.

**Comment by carloscds** [comment]
@StefanTheiner It make sense. Do you want to fix it ?

**Comment by StefanTheiner** [comment]
I have created a pull request
