### ISSUE TITLE
Replace getter only properties with backing readonly field with getter-only auto-property

### ISSUE THREAD

**Issue by MaStr11** [code-cracker/code-cracker#881]
#New analyzer:

I published an analyzer [here](https://github.com/ifpanalytics/Ifp.Analyzers) that 
finds getter only properties with backing readonly field and converts them to getter-only auto-properties.
Is there interest to port this one over to this library?

Before:

```cs
    class AwesomeService
    {
        private readonly ILogger _Logger;
        public AwesomeService(ILogger logger)
        {
            _Logger = logger;
        }

        protected ILogger Logger
        {
            get
            {
                return _Logger;
            }
        }
    }
```

After:

```cs
    class AwesomeService
    {
        public AwesomeService(ILogger logger)
        {
            Logger = logger;
        }

        protected ILogger Logger { get; }
    }
```

See [here](https://github.com/ifpanalytics/Ifp.Analyzers) for further details.

Diagnostic Id: `CC0125`
Category: `Refactoring`
Severity: `Hidden`

**Comment by carloscds** [comment]
@giggio What do you think about ?

**Comment by giggio** [comment]
I like it. Send a PR, @MaStr11!

**Comment by giggio** [comment]
@MaStr11 you are still missing the category, diagnostic id and severity. Feel free to propose them in this issue.

**Comment by giggio** [comment]
This is essentially a refactoring, so let's use `Hidden` for the Severity, and `Refactoring` for the Category.
