### ISSUE TITLE
Make CC0011 work with IQueryable and Async methods

### ISSUE THREAD

**Issue by pgrm** [code-cracker/code-cracker#905]
This is not a bug, rather aIf  very helpful extension to the [CC0011 rule](http://code-cracker.github.io/diagnostics/CC0011.html) to also skip `Where` conditions on `IQueryable` extension methods and when using for instance `FirstOrDefaultAsync()`

Example with EF Core code:

````csharp
await _context.MyTable.Where(t => t.Col1 == 1).FirstOrDefaultAsync();
````

Expected output after change applied:

````csharp
await _context.MyTable.FirstOrDefaultAsync(t => t.Col1 == 1);
````

If I read the rule correctly, than it should be enough to add `Async` suffix to the strings defined here: https://github.com/giggio/code-cracker/blob/master/src/CSharp/CodeCracker/Performance/RemoveWhereWhenItIsPossibleAnalyzer.cs#L20

Here are the latest EF-Core extension methods: https://github.com/aspnet/EntityFramework/blob/8bac118ee8b7ff5c30918e95682f454e0233c23e/src/EFCore/EntityFrameworkQueryableExtensions.cs - They seem to define all the async counterparts of the methods already used in the CC0011 rule

**Comment by pgrm** [comment]
Hey, I wanted to ask if you'd accept a PR where I'd just extend the above mentioned list

        static readonly string[] supportedMethods = new[] {
            "First",
            "FirstOrDefault",
            "Last",
            "LastOrDefault",
            "Any",
            "Single",
            "SingleOrDefault",
            "Count"
        };

with additional `Async` versions of each method - this would help us a lot. Thx

**Comment by carloscds** [comment]
@pgrm Please, send us a PR!
