### ISSUE TITLE
CC0049 SimplifyRedundantBooleanComparisonsAnalyzer detects false positive

### ISSUE THREAD

**Issue by Portikus** [code-cracker/code-cracker#915]
Hi everyone,

I have the following example:

````csharp
const string str = "";
if (string.IsNullOrEmpty(str) == false)
{
    Console.WriteLine(str);
}
````
The analyser gives me the hint that I can remove this comparison. If I use the analyser to remove the comparision I get the following result:

````csharp
const string str = "";
if (!string.IsNullOrEmpty(str))
{
    Console.WriteLine(str);
}
````

But this is just another way to write the same comparison and in my opinion this is much less readable. The explicit comparison with false is more fluent like I can read it like: if string is null or empty equals false then..... And on the other hand the small ! will often simply overseen. But this is just my opinion.
However the message that I can remove this comparison is simply false, it is the same comparision.

**Comment by carloscds** [comment]
@Portikus It's depend on point of view, as you talked, but idea of this analyzer it's remove this kind of comparision.

**Comment by MrPekel** [comment]
@carloscds The cause of this rule should be a redundancy of a comparision as stated in the [documentation](https://code-cracker.github.io/diagnostics/CC0049.html). The example of @Portikus is not redundant at all.

**Comment by giggio** [comment]
You can always disable the analyzer if you don't like it. That is the idea. We are sometimes a little opinionated, and this is one scenario. Others like "use var"  fall under the same category, they are opinionated. We expect some people won't want those analyzers, and can always disable them.
