### ISSUE TITLE
False postives and NullReferenceException when using eventhandler in code behind for UWP apps.

### ISSUE THREAD

**Issue by Portikus** [code-cracker/code-cracker#916]
Hi everyone,

I have the following situation:
I have a comnplete new created UWP App (with the Blank App template from VS2017).
I added a Button to the MainPage.xaml and created a Click event handler:

````xaml
<Button Click="ButtonBase_OnClick" />
````
In the code behind file I created the method for the event:

````csharp
private void ButtonBase_OnClick(object sender, RoutedEventArgs e)
{
}
````

The analyser will then report some warnings:

- CC0091 Make ButtonBase_OnClick method static
- CC0057 Parameter 'sender' is not used
- CC0057 Parameter 'e' is not used

As I tried to look what happens if I use the provided context action for this warnings Visual Studio informs me that: 'UnusedParametersCodeFixProvider' encountered an error and has been disabled. It also provides the following stack trace:

> System.NullReferenceException : Object reference not set to an instance of an object.
>    at async CodeCracker.CSharp.Usage.UnusedParametersCodeFixProvider.RemoveParameterAsync(<Unknown Parameters>)
>    at async CodeCracker.CSharp.Usage.UnusedParametersCodeFixProvider.RemoveParameterAsync(<Unknown Parameters>)
>    at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
>    at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputePreviewOperationsAsync(<Unknown Parameters>)
>    at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
>    at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
>    at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.PreviewChangesSuggestedAction.CreateAsync(<Unknown Parameters>)
>    at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.GetPreviewChangesFlavor(<Unknown Parameters>)
>    at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.CreateAllFlavors(<Unknown Parameters>)
>    at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)

It seems that UWP code behind event handler are not supported.

**Comment by giggio** [comment]
It makes sense. Moved to #933 and #934, for each analyzer.
