### ISSUE TITLE
Conditional run analysis with builds

### ISSUE THREAD

**Issue by GunterGlad** [code-cracker/code-cracker#920]
This may not be the right place to ask this and I apologies for this. But currently our build time was 20 seconds. After we install out build time is 2 minutes. Now this component produces amazing output and I would like to see the result. But I would like to only see on the build server and not for developer builds. Can you please tell me if this is possible? Or if we can have a configuration file? I can add/remove a config file during builds if required. I see mention of a "Rules" file but not sure how to use.

**Comment by GunterGlad** [comment]
Also just to add to this. I am running a .net core project. The code analysis is working but I cant seem to be able to apply the rules file. I can apply to a non .net core project.

**Comment by giggio** [comment]
Regarding your first comment, you could programatically change the csproj file during build time to add the analyzer reference. It shouldn't be too hard, you can do it with powershell, which has amazing xml manipulation capabilities.
.NET Core support is improving. I just tried a project and the code fix worked. I tried it as a Nuget reference and as a vsix.
