### ISSUE TITLE
Adding an "Async" method suffix should remove any embedded "Async" string in CC0061

### ISSUE THREAD

**Issue by KristianWedberg** [code-cracker/code-cracker#922]
# Enhancement

CC0061 is often triggered due to an additional suffix having been added to an `async` method name, resulting in an embedded "Async":

````csharp
public async static Task MyAsyncHelper()
{
    await Task.Delay(1);
}
````

Current output after fix applied, in v1.0.3:

````csharp
public async static Task MyAsyncHelperAsync()
{
    await Task.Delay(1);
}
````

Expected output after fix applied, where any embedded "Async" string have been removed:

````csharp
public async static Task MyHelperAsync()
{
    await Task.Delay(1);
}
````

**Comment by carloscds** [comment]
@KristianWedberg Correct is put Async suffix in method name. Look https://docs.microsoft.com/en-us/dotnet/articles/csharp/async

**Comment by jwooley** [comment]
It seems reasonable to pull "Async" out of the method name body if it exists there, but is not the name suffix and move it to the suffix position as appropriate. I did a similar implementation in my sample code at https://github.com/jwooley/RoslynAndYou/blob/master/ControllerDiagnostics/ControllerDiagnostics/ControllerNamingConventionCodeFixProvider.cs using a regex.replace.

**Comment by KristianWedberg** [comment]
@carloscds Yes, but in my example above we end up with _two_ "Async" strings in the name. It would be great to remove all existing embedded (and case sensitive, followed by a capital letter or underscore) "Async" strings, before adding a new "Async" suffix.

**Comment by carloscds** [comment]
@KristianWedberg I understand your point and it's move Async to end of method instead of add another Async, right ?

**Comment by KristianWedberg** [comment]
@carloscds Yes, that's correct.

**Comment by carlilord** [comment]
What would be a better approach in your opinion:
- Use a dictionary to exclude words that include "async"
- Check if name contains "async" and see if the 'A' is capital and the letter after the 'c' is also capital

**Comment by KristianWedberg** [comment]
@carlilord The latter, since that avoids having to come up with all exceptions, and should handle the vast majority of cases correctly. I'd suggest moving the "Async" sub-string to the end iff:

- It is case sensitive "Async"
- Is followed by a capital letter, underscore, or a digit

**Comment by carlilord** [comment]
@KristianWedberg seems ideal

do you mind if i take the ticket?

**Comment by KristianWedberg** [comment]
@carlilord of course not, go ahead :-)
