### ISSUE TITLE
BUG: CC0020 cannot be used 

### ISSUE THREAD

**Issue by sm-g** [code-cracker/code-cracker#930]
# Bug

Using CC 1.0.3:

````csharp
using System.Linq;
class Foo
{
    void M()
    {
        var xs = new System.Collections.Generic.List<int>();
        xs.Select(x => Func<int>(x));
    }
    object Func<T>(object x) => x;
}
````

After apply suggesting fix, got CS0123 `No overload for 'Foo.Func<int>(object)' matches delegate 'Func<int, object>'`

We should not offer a diagnostic in this situation.

**Comment by giggio** [comment]
Bug confirmed. I evolved the description to one that was independent of a specific library.

**Comment by Muppets** [comment]
@giggio I've got a PR for this bug. Let me know if this works for you guys. Feedback welcome.
