### ISSUE TITLE
Using Extension & NuGet package together causes VS2017 to crash

### ISSUE THREAD

**Issue by RogueJay** [code-cracker/code-cracker#944]
I have an existing solution in Visual Studio 2017 with a dozen C# projects, to which I want to begin applying coding standards.
I have the Code Cracker Visual Studio extension installed, because I want to do some tidying up of the project code before I enforce the standards as part of the build process.
After some time, I get the first project to a state that is acceptable to enforcing the standards as part of the actual build process, so I add the Code Cracker NuGet package to the project in question.

The package installs and then Visual Studio crashes. 

If I add the package to the project in VS2015 and then open the solution in VS2017, Visual Studio crashes as soon as the solution is opened.

I am using CC 1.0.3 for both the extension and NuGet package.
Latest version of Visual Studio - VS 15.2 (26430.16)

**Comment by carloscds** [comment]
@RogueJay You need to install package for VS 2017.

**Comment by RogueJay** [comment]
@carloscds Sorry, I don't understand what you are suggesting. 
I used the NuGet package manager in VS2017, searched for Code Cracker, and installed the only CSharp option that came up, which was v1.0.3.

Is there some other package I should be installing?

**Comment by carloscds** [comment]
@RogueJay Can you send a ActivityLog of Visual Studio ?

**Comment by sharwell** [comment]
@RogueJay Can you use the Send Feedback tool in Visual Studio 2017 (top right, next to the Quick Launch box) to report this crash? If it turns out to be a Visual Studio bug it will help us resolve it as quickly as possible.

**Comment by RogueJay** [comment]
After some investigating, I have narrowed down the situation a little more. 

You also have to have the Visuals Studio option Text Editor\C#\Advanced\Enable full solution analysis selected, which obviously causes VS to scan all the files on opening the solution. Guessing there's a problem with the project loading the CC analyser whilst the analysis is under way or something?

@sharwell I have submitted a feedback, but I didn't include this latest piece of information

@carloscds I've attached an ActivityLog, but I don't think it's got anything useful in it. The solution is loaded after entry 500

[ActivityLog.zip](https://github.com/code-cracker/code-cracker/files/1179129/ActivityLog.zip)

**Comment by RogueJay** [comment]
I have just confirmed that you DO need the VS extension installed and active as well. It may seem like a slightly contrived situation, but we have a LOT of projects that need tidying up, so it makes the process easier if we can use both methods during the transition. It must be possible because the other analyser we use (Refactoring Essentials) copes.

Also, I tried debugging VS and it threw an error about a key already existing in the data structure. Not sure if that had anything to do with it, but the problem was in the MS analyser assemblies somewhere.

**Comment by RogueJay** [comment]
What's slightly odd, is that adding a direct analyzer reference to a project in VS2017 seems to exclude it from the full solution analysis anyway. Another issue I'd like to report to MS, but can't because I'm behind a proxy....

**Comment by sharwell** [comment]
@RogueJay You can file issues for this on [dotnet/roslyn](https://github.com/dotnet/roslyn). Pretty much everything related to analyzers in the IDE is part of that open source repository. :smile:

**Comment by sharwell** [comment]
@RogueJay You can also find stack traces for crashes here:

1. Open Event Viewer
2. Go to the Windows Logs &rarr; Application view
3. Look for items with level **Error** and source **.NET Runtime**

**Comment by giggio** [comment]
Yes, even if CodeCracker threw an exception, VS should not crash.
@RogueJay if you build from msbuild, do you get any errors?
I am closing the issue as it is not a problem in CodeCracker, it is likely a problem in VS.
