### ISSUE TITLE
Support Hacktoberfest event adding hacktoberfest tag.

### ISSUE THREAD

**Issue by kidchenko** [code-cracker/code-cracker#949]
Hi folks, I think that you know about [hacktoberfest](hacktoberfest.digitalocean.com), I would be very happy to see this project supporting this event adding a `hacktoberfest` label, so when I search by #hacktoberfest in github I can see this repo.

## Actual Behavior
When I search by `#hacktoberfest language:C#` I don't see this repository in list of results.
![image](https://user-images.githubusercontent.com/5432753/31552144-cc89aeec-b060-11e7-8c81-4f94b9fe08c3.png)
 

## Steps to Reproduce the Problem

  1. Open [github](https://github.com/);
  1. Search by #hacktoberfest language:C# in global search input 
![image](https://user-images.githubusercontent.com/5432753/31552250-226349b8-b061-11e7-944e-6032b7c501b4.png)

**Comment by carloscds** [comment]
@kidchenko Done 👍

**Comment by kidchenko** [comment]
I had closed this issue, thanks a lot for all maintainers.
