### ISSUE TITLE
CC0061 shouldn't pop for async Main

### ISSUE THREAD

**Issue by Thieum** [code-cracker/code-cracker#958]
#Bug

In C# 7.1, you can have an async main. CC0061 suggests to rename to MainAsync, but that would lead to an unusable program.

https://blogs.msdn.microsoft.com/mazhou/2017/05/30/c-7-series-part-2-async-main/

````csharp
public static Task Main();
public static Task<int> Main();
public static Task Main(string[] args);
public static Task<int> Main(string[] args)
````

**Comment by steamos** [comment]
Hi,

I believe I have fixed this issue, however I see that it's not scheduled for release, so please let me know if you'd like me to create a Pull Request for review or if it'll be scheduled for a later release.

Thanks.
