### ISSUE TITLE
ConvertLambdaExpressionToMethodGroupAnalyzer null exception

### ISSUE THREAD

**Issue by sharethl** [code-cracker/code-cracker#969]
#Bug
Is there anyway to get more info from the build process? From the error msg cannot find out what is the cause.
`3>CSC : warning AD0001: Analyzer 'CodeCracker.CSharp.Style.ConvertLambdaExpressionToMethodGroupAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.`

Version: 1.0.3

**Comment by carloscds** [comment]
@sharethl You can catch InnerExceptions and StackTrace.

**Comment by giggio** [comment]
If you can find the specific method that threw the error we can try to repro. I am closing the issue until we can get code that we can verify, feel free to reopen with the example.
