### ISSUE TITLE
Binary for newbies

### ISSUE THREAD

**Issue by tazotodua** [code-cracker/code-cracker#972]
Well, it could have been nice if there was compiled program of code-cracker, for newbies like me. 
I've tried what I could, used VIsual Studio 2017 to compile these repository, but it fails, throws some dependency errors and etc...
why there is not simple a link to download latest compiled version, like all other programs on github, include a link to download the compiled version for people like me, that saves hours for us.

thanks.

**Comment by jwooley** [comment]
To use it, just add the nuget package to your project. See the steps for installing on the [main page](https://github.com/code-cracker/code-cracker).

**Comment by giggio** [comment]
Also, every release has a compiled version:
https://github.com/code-cracker/code-cracker/releases

And also, every build produces artifacts:
https://ci.appveyor.com/project/code-cracker/code-cracker/build/artifacts
