### ISSUE TITLE
Translate to Portuguese

### ISSUE THREAD

**Issue by carloshenriqueribeiro** [code-cracker/code-cracker#973]
Could I translate the Read.me file to Portuguese ?

What is the best way to expose it ? link on main read.me ?

**Comment by carloshenriqueribeiro** [comment]
@ElemarJR @giggio

**Comment by carloscds** [comment]
@carloshenriqueribeiro We do not plans at this moment. But you can help us. What do you think about?

**Comment by carloscds** [comment]
@carloshenriqueribeiro Sounds good!

**Comment by giggio** [comment]
The problem here is that we can't have 2 readme's. I think a link on the main readme would be fine. Maybe a `README.pt.md`?

**Comment by carloshenriqueribeiro** [comment]
to be real I thought to create a directory "docs-pt" something like on dotne GitHub.

**Comment by giggio** [comment]
Can you post a link to the repo you are referring to?

**Comment by carloshenriqueribeiro** [comment]
https://github.com/dotnet/docs.pt-br/

**Comment by giggio** [comment]
I think a whole repo is too much. If we are going to translate only one file (readme), then I believe it is better we just created this one file in pt, like `README.pt.md`.

**Comment by carloscds** [comment]
@carloshenriqueribeiro Only a readme.md.pt it's enough. And we can put a link in readme.md to this file.

**Comment by carloshenriqueribeiro** [comment]
Ok

**Comment by carloshenriqueribeiro** [comment]
could u change the label for "Working" ?

**Comment by carloscds** [comment]
@carloshenriqueribeiro Go ahread.

**Comment by carloshenriqueribeiro** [comment]
Is DoD still evolving as written in readme ?

**Comment by carloscds** [comment]
@carloshenriqueribeiro You can do creating a readme.md.pt and include a link in readme.md

**Comment by carloshenriqueribeiro** [comment]
Sorry @carloscds I did not understand. I asked about DoD.

**Comment by carloscds** [comment]
@carloshenriqueribeiro It's only a document, make changes and send a PR.

**Comment by carloshenriqueribeiro** [comment]
Sir yes Sir.
