### ISSUE TITLE
Outdated SonarQube Plugin

### ISSUE THREAD

**Issue by Lukas0101** [code-cracker/code-cracker#988]
The release v1.0.3 contains a SonarQube plugin. In the release v1.1.0 the plugin is missing. Will be a new version provided or must it be created by each user themselves? The first discussion of this topic was in https://github.com/code-cracker/code-cracker/issues/811.

**Comment by carloscds** [comment]
@Lukas0101 Hi Lukas, plugin was updated! Thanks!

**Comment by doodz** [comment]
hi,
@carloscds  I have the same problem, I am in 1.0.1. 
The marketplace don't show me an update for 1.1.0.
Moreover in[ https://docs.sonarqube.org/display/PLUG/Plugin+Version+Matrix]( https://docs.sonarqube.org/display/PLUG/Plugin+Version+Matrix) whe can see that last compatible version is 1.0.1.
best regard

**Comment by carloscds** [comment]
@doodz I'm still updating in Sonarqube site plugin. For now you need to update manually.

**Comment by doodz** [comment]
ok, I can't I am on Community Edition. :(.

**Comment by carloscds** [comment]
@doodz Sorry for this. I'm working to update plugin at SonarSource.

**Comment by carloscds** [comment]
@doodz I have submitted a new version to SonarQube. Now I'm waiting for approval

**Comment by doodz** [comment]
@carloscds  thank you, your release is passed.
